insolar/bus/bus.go, insolar/flow/dispatcher/dispatcher.go
=> NOISSUE: set/get traceID

functest/utils_test.go, insolar/flow/dispatcher/dispatcher.go, ledger/heavy/handler/handler.go, network/servicenetwork/servicenetwork.go
=> NOISSUE: use meta to save traceID via watermill, not ctx

network/hostnetwork/future/future_test.go, network/hostnetwork/hostnetwork_test.go
=> NOISSUE: fix network tests timeouts

ledger/light/handle/register_child.go
=> INS-2501: some procs in registerChild should be cancellable

functest/main_test.go
=> Ins 2488 functests print pulsewatcher

log/log.go, log/zerolog.go
=> INS-2519: new pretty formats

functest/main_test.go
=> INS-2490: attempt to remove CI teardown legacy

cmd/pulsard/main.go, insolar/utils/utils.go, instrumentation/inslogger/inslogger.go, network/controller/pulsecontroller.go, network/hostnetwork/packet/request.go, network/pulsenetwork/distributor.go, network/servicenetwork/servicenetwork.go, pulsar/networking.go, pulsar/pulsar.go, pulsar/pulsarbroadcasters.go, pulsar/pulsarconsensus.go, pulsar/pulsartimers.go, pulsar/statemachine.go, scripts/generate_insolar_configs.go, scripts/insolard/pulsar_template.yaml
=> Noissue pulsar rooted traces

Makefile
added the json output format as go test flag (-json) 
=> NOISSUE: change test output to json

functest/utils_test.go, logicrunner/artifacts/client.go, messagebus/senders.go
- retrying message on next pulse when received flow cancelled error
=> Ins 2538 flow cancelled retries

metrics/metrics_test.go, testutils/testmetrics/testmetrics.go
=> INS-2536: preserve output of sub command in metrics test

logicrunner/goplugin/goplugin.go
add logs that can save time while fixing bugs in CI
=> No issue more logs

contractrequester/contractrequester.go, logicrunner/handle_calls.go
=> INS-2572: tmp fix flow cancelled in logic runner

insolar/gen/reference.go
=> INS-2562: delete nilchance for jetid fuzz

logicrunner/logicrunner_unit_test.go
SetupLogicRunner() result in a new WaterMill that leaks goroutines if
is not stopped
=> INS-2594: change test to stop leaking goroutines

logicrunner/accessors.go, logicrunner/currentexecution.go, logicrunner/executionstate.go, logicrunner/handle_abandonedrequestsnotification.go, logicrunner/handle_calls.go, logicrunner/handle_executorresults.go, logicrunner/handle_pending_finished.go, logicrunner/handle_processqueue.go, logicrunner/handle_still_executing.go, logicrunner/logicrunner.go, logicrunner/logicrunner_rpc_methods.go, logicrunner/logicrunner_unit_test.go
(OOS stands for out-of-sequence)
* Current -> CurrentList (was remade for supporting of many parallel requests)
+ extracted to separate file
* Slightly modified comment for LogicRunner test cleanup
=> INS-1466: Preparation for OOS immutable requests processing

logicrunner/logicrunner_unit_test.go
I have failed to reproduce race (ran with -count=50000). But have made some changes to prevent racing in these tests.
=> INS-2602: attempt to fix race in LR tests

logicrunner/currentexecution.go, logicrunner/handle_processqueue.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
CallMethod message has nothing much but request record
=> INS-2002: delete message from CurrentExecution, duplicates Request

scripts/insolard/launchnet.sh
disable start of connected node in launchnet.sh if it is functests
=> NO_ISSUE-dont-start-conected-node-in-fuctests

ledger/light/artifactmanager/handler_test.go, ledger/light/handle/get_pending_request_id.go, ledger/light/handle/get_pending_requests.go
=> INS-2657 waiting for hot data for pendings

messagebus/messagebus.go, network/gateway/base.go, network/gateway/complete.go, network/gateway/gateway_test.go, network/gateway/nonetwork.go, network/interfaces.go, network/servicenetwork/servicenetwork.go, network/tests/gateway_test.go, network/tests/suite_test.go
Another liveable variant of locking.
=> INS-2584: move locks to SetGateway()

ledger/light/handle/init.go
=> NO_ISSUE_not_jet_executor_after_pass fix bug

api/seedmanager/seedmanager_test.go
- changed timeout to 10 minutes
=> INS-2600: timeout in TestSeedManager_Add changed to 10 minutes

network/controller/pulsecontroller.go, network/controller/pulsecontroller_test.go, network/tests/pulsar_test.go
Fixed pulsars signatures check on insolard side
Run tests, run launchnet
=> INS-2547: pulse sign fixes

Makefile
upgrade dep version in Makefile target **install-godep.**
this version fixes several bugs, [see changelog](https://github.com/golang/dep/blob/master/CHANGELOG.md)
=> upgrade dep version to v0.5.3

network/consensus/phases/hashstorage.go
Fixed race in consensus proof storage
Run integration tests with race detector
=> INS-2690: fix proof storage race

insolar/vm.go, logicrunner/currentexecution.go, logicrunner/executionstate.go, logicrunner/executionstate_test.go, logicrunner/goplugin/rpctypes/rpctypes.go, logicrunner/handle_calls.go, logicrunner/handle_executorresults.go, logicrunner/handle_ledgerpendingrequest.go, logicrunner/handle_processqueue.go, logicrunner/logicrunner.go, logicrunner/logicrunner_rpc_methods.go, logicrunner/logicrunner_unit_test.go
Since it's basically two sides of 1 coin
=> INS-1466: Unify ExecutionQueueElement and CurrentExecution

network/hostnetwork/future/handler.go, network/hostnetwork/handlers.go, network/hostnetwork/hostnetwork.go, network/hostnetwork/hostnetwork_test.go, network/hostnetwork/packet/packet_helper.go, network/hostnetwork/packet/packet_test.go, network/pulsenetwork/distributor.go, network/transport/fake.go, network/transport/tcp.go, network/transport/transport.go, network/transport/transport_test.go
- Switched flaky tests logging level to debug for future investigation
- Fixed context passing in network components
- Improved logging network request/responses
=> NOISSUE: debug for host tests

ledger/light/handle/get_object.go, ledger/light/handle/set_code.go, ledger/light/proc/executor.go
fixed flacked bug with object not found
=> NO_ISSUE_object_nott_found

logicrunner/casebind.go, logicrunner/handle_calls.go, logicrunner/procs.go
- "can't play role" rewrited to "flow cancelled" to force retry
=> INS-2649: cant-play-role rewrited to flow cancelled to force retry

api/main.go
don't use http.DefaultServeMux in api code
=> INS-2704: fix shared state in tests

scripts/README.md, scripts/generate_insolar_configs.go
remove jaeger by default for preventing log spam in CI
=> NOISSUE_remove_jaeger_by_default

api/seedmanager/seedmanager.go, api/seedmanager/seedmanager_test.go
Fix grouting leaking in seed manager test
=> Ins fix goroutine fix in seedmanager

insolar/message/logicrunner.go, logicrunner/executionstate.go, logicrunner/handle_calls.go, logicrunner/handle_ledgerpendingrequest.go, logicrunner/logicrunner_unit_test.go
1) launch queueProcessor for AdditionalCallFromPreviousExecutor
2) launch UnsafeGetLedgerPendingRequest in flow
=> Ins 2692 move get pending to proc

Makefile
add knobs to control concurrency level in CI environment
=> INS-2710: try to be more lean to resources in CI env

docs/source/architecture.rst, docs/source/features.rst, docs/source/index.rst, docs/source/integration.rst
- Removed references to tech paper's sections.
- Improved the Table of Contents.
=> Removed refs, improved ToC

internal/ledger/store/badger.go
- add async values garbage collection (https://github.com/dgraph-io/badger/tree/v1.5.3#garbage-collection)
- add method ForceValueGC to BadgerDB for manual GC triggering
- add logs to BadgerDB.Stop method
=> INS-2724: activate badger DB values garbage collection

ledger/light/artifactmanager/handler_test.go, ledger/light/proc/set_blob.go, ledger/light/proc/set_record.go, ledger/light/proc/update_object.go, ledger/light/proc/update_object_test.go, ledger/light/replication/gatherer_test.go, ledger/object/record_cmp_test.go, ledger/object/record_test.go, logicrunner/artifacts/tmpledger.go, utils/entropy/entropy_test.go
=> better errors checks for hot.WriteAccessor, remove unused code

logicrunner/preprocessor/main.go
=> INS-2741: guarantee oreder

ledger/light/proc/set_record.go
=> turn off filaments while they aren't in the working state

insolar/bus/bus.go, insolar/bus/bus_test.go
=> INS-2740: switch-off integrity hasher for watermill meta msg

ledger/light/pulsemanager/pulsemanager.go
=> INS-2747 zero indexes in hot data

logicrunner/currentexecution.go, logicrunner/executionstate.go, logicrunner/logicrunner.go
required for validation and parallel execution of immutable calls
=> INS-2008: obj desc into current, we get one for every request

docs/requirements.txt, docs/source/architecture.rst, docs/source/architecture.uml, docs/source/conf.py
- Beautified the architecture scheme.
- Upgraded the doc build to run on py3 + sphinx2.
=> [DOC] Scheme beautification & build upgrade

insolar/jet/jet.go, insolar/jet/tree.go, ledger/light/executor/jet_splitter.go, ledger/light/executor/jet_splitter_test.go, ledger/light/pulsemanager/pulsemanager.go
- move jet.Info to executor.JetInfo
- add jet.Siblings helper
- don't save left and right siblings in jet info struct (use new SplitPerformed flag)
=> INS-2746: refactor jet info structure

api/call_test.go, api/seedmanager/seedmanager.go
- increased seed timeout to 1 minute
=> INS-2757: callHandler_Timeout returns Incorrect seed

functest/utils_test.go
We have member with unique pk now. If request must be retried, we create new pair of keys for every attempt.
Run tests.
=> Ins 2781 create unique member if retry

logicrunner/currentexecution.go, logicrunner/currentexecution_test.go, logicrunner/executionstate.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
* Tests for execution broker
* Tests for immutable calls parallel execution
* Disable side effects of immutable calls
* Tests for immutable calls side effects
* Remove codeDescriptor/prototypeDescriptor from executionstate
=> INS-1466: tests for immutable calls

api/contract.go, ledger/light/proc/update_object.go, ledger/light/proc/update_object_test.go, logicrunner/artifacts/artifacts.go, logicrunner/artifacts/client.go, logicrunner/artifacts/client_mock.go, logicrunner/goplugin/goplugintestutils/utils.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
remove ObjectDescription from return values for ActivateObject, ActivetePrototype, UpdateObject and Deactivate Object
=> Ins 2652 client refactoring

logicrunner/logicrunner.go
we used to have method in artifact manager client that accepted such
slice as argument
=> INS-2008: remove unused lr.machinePrefs

logicrunner/executionstate.go, scripts/cmd/track/track.go
1) Send ExecutionResults on next executor if we did something with that object
2) flush line since they might be lost
=> Ins 2775 more correct lr pulse processing

logicrunner/artifacts/client.go
=> NOISSUE: update no reply err

logicrunner/artifacts/client.go
**What I did**
retryer for client.RegisterRequest was added
=> INS-2799: retryer for client.RegisterRequest added

logicrunner/artifacts/client.go
=> Revert "INS-2799: retryer for client.RegisterRequest added"

functest/logicrunner_test.go, logicrunner/casebind.go, logicrunner/executionstate.go, logicrunner/logicexecutor.go, logicrunner/logicexecutor_test.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go, logicrunner/procs.go, logicrunner/requestresult.go, server/internal/virtual/components.go
that can be shared between execution and validation
access to descriptors cache and LR, but only for executors
=> INS-2008: LogicExecutor with Execute(transcript)

insolar/bus/bus.go, insolar/bus/bus_test.go
=> NOISSUE: update msg hash logger field

ledger/light/proc/set_activation_request.go, ledger/light/proc/set_code.go, ledger/light/proc/set_request.go, ledger/object/index_memory.go
=> INS-2733: record override error for log without returning error

ledger/heavy/handler/store.go
Log message level changed from `ERR` to `DBG`
=> INS-2698: logmsg from err to dbg

network/controller/pinger/pinger_test.go
=> INS-2700: fix pinger test

api/call.go, api/main_test.go, api/requester/requester.go, functest/common_test.go, functest/new_api_test.go
Removed scheme; Refactored callHandler.
Removed scheme; Refactored callHandler, fixed tests
Look at callHandler
closes #INS-2774
=> Ins 2774 refactor callHandler

network/hostnetwork/hostnetwork_test.go, network/hostnetwork/pool/entry.go, network/interfaces.go
=> fix future leaks in test

certificate/authorization.go, certificate/certificate.go, cryptography/service.go, functest/register_node_test.go, insolar/platformpolicy.go, network/consensus/adapters/cryptography.go, network/consensus/adapters/cryptography_test.go, platformpolicy/cryptographyscheme.go, platformpolicy/cryptographyscheme_test.go, platformpolicy/internal/sign/helpers.go, platformpolicy/internal/sign/interfaces.go, platformpolicy/internal/sign/provider.go, platformpolicy/internal/sign/wrapper.go, platformpolicy/internal/wrapper_test.go, testutils/core.go
=> NOISSUE: refactor cryptography scheme

Makefile, insolar/jetcoordinator/jetcoordinator.go, ledger/light/artifactmanager/handler.go, ledger/light/artifactmanager/handler_test.go, ledger/light/executor/hot_sender.go, ledger/light/executor/jet_splitter.go, ledger/light/executor/jet_splitter_test.go, ledger/light/proc/hot_data.go, ledger/light/pulsemanager/pulsemanager.go, ledger/light/replication/cleaner.go, logicrunner/pulsemanager/pulsemanager.go, server/internal/light/components.go
* fix broken jet split logic
* better naming, add comments for clarity
=> INS-2789: fix jets split logic

insolar/bus/bus.go, logicrunner/logicrunner.go
=> INS-2838 MustSerialize -> Serialize

logicrunner/logicrunner_rpc_methods.go
It's rather tricky to cover these 3 lines of code with unit tests because they heavily depend on LogicRunner's internals. I will think on how this issue can be solved. Since like half of the team depend on this patch I suggest to accept this part without any tests except tests that already exist.
=> INS-2833: pass reason in IncommingRequest

ledger/heavy/pulsemanager/pulsemanager.go, logicrunner/pulsemanager/pulsemanager.go
=> INS-2789: get rid of obsolete genesis hack

insolar/message/logicrunner.go, logicrunner/executionstate.go, logicrunner/logic_executor_mock.go, logicrunner/logicexecutor.go, logicrunner/logicexecutor_test.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go, logicrunner/requests_executor_mock.go, logicrunner/requestsexecutor.go, logicrunner/requestsexecutor_test.go, server/internal/virtual/components.go
it deals with artifacts and message bus, feeds to LogicExecutor
=> INS-2008: RequestsExecutor component

insolar/jet/dbstore.go, insolar/jet/dbstore_test.go, insolar/jet/jet.go, insolar/jet/store.go, insolar/jet/store_test.go, insolar/jet/tree.go, ledger/light/executor/jet_splitter.go
jets are always actual in place they were split
=> INS-2825: mark split jets as active

ledger/light/executor/filament_calculator_mock.go, ledger/light/executor/filaments.go, ledger/light/executor/filaments_test.go
=> Ins 2829 result duplicate

ledger/light/handle/set_request.go, ledger/light/proc/set_request.go
=> INS-2762: make workaround better

scripts/insolard/defaults/insolard.yaml
disable consensus in launchnet. Don't forget enable it, when new consensus released
=> INS-2765 disable consensus in launchnet

api/call.go, api/requester/config.go, api/sdk/sdk.go, cmd/insolar/certgen.go
Change to actual API
Rename response field to callResult.
Moved traceId in error in data field
closes #WLT-677
=> Wlt 677 response struct

logicrunner/currentexecution.go, logicrunner/logicrunner_rpc_methods.go, logicrunner/rpc_methods_test.go
I know that tests are incomplete, but I think it's better to merge sooner.
=> INS-2008: partial proxy implementation for validation

network/consensus/common/hash_containers.go, network/consensus/common/misc.go, network/consensus/gcpv2/common/configs_test.go, network/consensus/gcpv2/common/hashes.go, network/consensus/gcpv2/common/hashes_test.go, network/consensus/gcpv2/common/node_profiles.go, network/consensus/gcpv2/common/node_profiles_test.go, network/consensus/gcpv2/common/node_roles_test.go, network/consensus/gcpv2/common/packet_data.go, network/consensus/gcpv2/common/packet_data_test.go, network/consensus/gcpv2/common/weight_scaler_test.go, network/consensus/gcpv2/core/announce_handler_test.go, network/consensus/gcpv2/core/candidate_feeder_test.go, network/consensus/gcpv2/core/node_appearance_test.go, network/consensus/gcpv2/packets/packet_readers.go, network/consensus/gcpv2/testutils/candidate_profile_mock.go, network/consensus/gcpv2/testutils/full_introduction_reader_mock.go, network/consensus/gcpv2/testutils/host_profile_mock.go, network/consensus/gcpv2/testutils/local_node_profile_mock.go, network/consensus/gcpv2/testutils/member_announcement_signature_mock.go, network/consensus/gcpv2/testutils/node_state_hash_evidence_mock.go, network/consensus/gcpv2/testutils/packet_parser_mock.go, network/consensus/testutils/foldable_reader_mock.go, network/consensus/testutils/host_identity_holder_mock.go, network/consensus/testutils/signature_verifier_factory_mock.go, network/consensus/testutils/signature_verifier_mock.go
I wrote some unit tests for a new consensus.
Call functions with different parameters to have different behaviour.
Run tests.
Unit tests for a new consensus.
=> Noissue consensus tests

logicrunner/artifacts/client.go
all saves we do from RequestsExecutor should be retried
=> INS-2835: retry flow canceled on activation as well

api/call.go, api/requester/config.go, functest/utils_test.go
grep -r "related" .
./discoverynodes/1/output.log:2019-07-04T19:03:53.452631000+03:00 INF Request related to **github.com/insolar/insolar/functest.TestCreateMember** file=usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1995 loginstance=inslog nodeid=1tJCe1eodyPAj894JaA1ANZczb79JC1GYRv3nzMHRS.11111111111111111111111111111111 role=heavy_material traceid=**4ec47fa9-0663-403e-9e9e-7c9789ed5d09**
=> INS-2885: log in nodes which functest started this request.

api/requester/config.go, api/requester/testdata/requestConfig.json, logicrunner/builtin/contract/helloworld/helloworld.go, logicrunner/builtin/contract/member/member.go, logicrunner/builtin/proxy/helloworld/helloworld.go, logicrunner/builtin/proxy/member/member.go
I fixed bug with an incorrect name field, bug INS-2904
Just renamed
Run tests and check API specification
=> INS-2904:updated to correct field name

api/call.go, api/contract.go, application/extractor/member_test.go, functest/helloworld_test.go, insolar/serialization.go, logicrunner/builtin/contract/helloworld/helloworld.go, logicrunner/builtin/contract/helloworld/helloworld.wrapper.go, logicrunner/builtin/proxy/helloworld/helloworld.go
Added return struct from smart contracts feature.
Added cast all map types to map[string]interface{} in serialization function.
Launch TestCallHelloWorldReturnObj.
Struct return from contract.
=> INS-2896: fixed return struct

api/call.go, api/call_test.go, api/requester/config_test.go, api/requester/requester.go, api/requester/testdata/requestConfig.json, api/sdk/sdk.go, functest/helloworld_test.go, functest/new_api_test.go, functest/utils_test.go
Fixed bug INS-2903 with the incorect method name
Checked each usage of this method and updated to correct
Run tests
=> INS-2903: fixed method name

api/call.go, api/contract.go, application/extractor/member_test.go, functest/helloworld_test.go, insolar/serialization.go, logicrunner/builtin/contract/helloworld/helloworld.go, logicrunner/builtin/contract/helloworld/helloworld.wrapper.go, logicrunner/builtin/proxy/helloworld/helloworld.go
=> Revert "INS-2896: fixed return struct"

api/call.go, api/contract.go, application/extractor/member_test.go, functest/helloworld_test.go, insolar/serialization.go, logicrunner/builtin/contract/helloworld/helloworld.go, logicrunner/builtin/contract/helloworld/helloworld.wrapper.go, logicrunner/builtin/proxy/helloworld/helloworld.go
Added return struct from smart contracts feature.
Added cast all map types to map[string]interface{} in serialization function.
Launch TestCallHelloWorldReturnObj.
Struct return from contract.
=> Revert revert 2055 ins 2896 struct return

api/contract.go, contractrequester/contractrequester.go, contractrequester/contractrequester_test.go, insolar/api/reason.go, insolar/contractrequester.go, logicrunner/goplugin/goplugintestutils/utils.go
- reason added to requests from ContractService
=> INS-2932: reason added to requests from ContractService

network/consensusv1/phases/communicator.go, network/consensusv1/phases/communicator_test.go, network/controller/bootstrap/authorization.go, network/controller/bootstrap/bootstrap.go, network/controller/pinger/pinger_test.go, network/controller/pulsecontroller.go, network/controller/pulsecontroller_test.go, network/controller/rpc_controller.go, network/gateway/complete.go, network/gateway/complete_test.go, network/hostnetwork/future/future.go, network/hostnetwork/future/future_test.go, network/hostnetwork/future/handler.go, network/hostnetwork/future/handler_test.go, network/hostnetwork/future/interfaces.go, network/hostnetwork/handlers.go, network/hostnetwork/hostnetwork.go, network/hostnetwork/hostnetwork_test.go, network/hostnetwork/packet/packet_helper.go, network/hostnetwork/packet/packet_test.go, network/hostnetwork/packet/received.go, network/interfaces.go, network/pulsenetwork/distributor.go, network/pulsenetwork/distributor_test.go, network/servicenetwork/servicenetwork.go, testutils/network/pulse_handler_mock.go
=> NOISSUE: pass packet bytes

api/info.go
Update API network.getInfo
a lowerCase field in return json
get request to insolar "network.getInfo"
Change format for naming json
=> INS-2940 updates api getInfo. Lowercase field in json

Gopkg.lock, Gopkg.toml, internal/ledger/store/badger.go, log/log.go, network/storage/storage.go, pulsar/storage/pulsestorage_badger.go
=> Ins 2925 badger ver upd

insolar/jet/dbstore_test.go, insolar/pulse/db_test.go, ledger/drop/db_test.go, ledger/object/index_db_test.go, ledger/object/record_test.go
decrease num iterations in tests for *TruncateHead*
А тони сильно выбиваются
=> decrease num iterations in tests for *TruncateHead*

api/sdk/sdk.go
fixed cast response from createMember in SDK
fixed cast response from createMember in SDK
launch benchmark
=> INS-2963: fixed cast response from createMember

api/contract.go
add handle of contract foundation error, it was not used
=> INS-2965 API return real contract foundation error

bootstrap/contracts/contracts.go, functest/member_get_test.go, logicrunner/builtin/contract/member/member.go, logicrunner/builtin/contract/member/member.wrapper.go, logicrunner/builtin/contract/rootdomain/rootdomain.go, logicrunner/builtin/proxy/member/member.go
added member get method except getReferenceByPublicKey
added member get method except getReferenceByPublicKey
launch TestMemberGet
added member.get
=> WLT-682: added member get method except getReferenceByPublicKey

network/hostnetwork/handlers.go, network/pulsenetwork/distributor.go, network/tests/bootstrap_test.go, network/tests/pinger_test.go
workaround for INS-2946
skip one ugly test which failed nightly, need to fix it after new bootstrap will be merged
=> Ins 2946 matching nodes not found

configuration/ledger.go, ledger/drop/drop.go, ledger/heavy/handler/handler.go, ledger/heavy/handler/handler_test.go, ledger/light/executor/jet_splitter.go, ledger/light/executor/jet_splitter_test.go, ledger/light/integration/server_test.go, scripts/generate_insolar_configs.go, server/internal/heavy/components.go, server/internal/light/components.go
- implement jet split based on thresholds
- update tests
=> Ins 2851 jet split by threshold

insolar/pulse.go, ledger/light/executor/filaments.go
=> INS-2826 additional checking

ledger/heavy/handler/handler.go, ledger/light/artifactmanager/handler.go, messagebus/messagebus.go
Move heavy msg types to async path
Run tests.
=> INS-2974: move heavy msg types to async path

insolar/payload/payload.go, instrumentation/introspector/pubsubwrap/decode_messages.go, instrumentation/introspector/pubsubwrap/middleware_locker.go, instrumentation/introspector/pubsubwrap/middleware_stat.go, instrumentation/introspector/pubsubwrap/pubsubwrap.go, instrumentation/introspector/pubsubwrap/pubsubwrap_test.go, server/internal/pubsub_introspect.go
fix panic on legacy messages decode in introspection API
=> Ins 2982: fix introspection message decode

configuration/pulsar.go, network/pulsenetwork/distributor.go, network/tests/bootstrap_test.go
=> Noissue revert workaround

insolar/bus/bus.go, insolar/bus/retryer.go, insolar/bus/retryer_test.go, insolar/bus/sender_mock.go, insolar/bus/waiter.go, insolar/bus/waiter_test.go, logicrunner/artifacts/client.go, logicrunner/logicrunner.go
add retry sender to LR
add getter for senders pulse accessor, remove pulse accessor from retry sender constructor, change mocks ant tests
run tests
=> INS-2973 add retryer sender to LR

ledger/drop/drop.go, ledger/heavy/handler/handler.go, ledger/light/executor/jet_splitter.go, ledger/light/executor/jet_splitter_test.go
- fix jet split on light
- add `Split` flag to jet drop
=> Ins 3000 fix jet split

docs/source/architecture.rst
**- What I did**:
- Removed child mentions from both text and schemes.
- Added cosmetic edits.
=> Remove child mentions

insolar/message/ledger.go, insolar/message/message.go, insolar/messagebus.go, insolar/messagetype_string.go, ledger/light/artifactmanager/handler.go, ledger/light/executor/filament_cleaner_mock.go, ledger/light/executor/filaments.go, ledger/light/executor/hot_sender.go, ledger/light/integration/server_test.go, ledger/light/replication/cleaner.go, ledger/light/replication/cleaner_test.go, messagebus/messagebus.go, server/internal/light/components.go
=> Ins 2865 cache clean up

ledger/drop/drop.go, ledger/heavy/handler/handler.go, ledger/light/executor/jet_splitter.go, ledger/light/executor/jet_splitter_test.go
=> Revert "Ins 3000 fix jet split"

api/requester/config.go, api/requester/testdata/requestConfig.json, logicrunner/builtin/contract/helloworld/helloworld.go, logicrunner/builtin/contract/member/member.go, logicrunner/builtin/proxy/helloworld/helloworld.go, logicrunner/builtin/proxy/member/member.go
Edited requester.Request struct field memberPublicKey to publicKey like in openAPI
Edited requester.Request struct field memberPublicKey to publicKey
Launch tests
requester.Request field publicKey
=> INS-3001: edited request memberPublicKey

insolar/flow/dispatcher/dispatcher.go, ledger/heavy/handler/handler.go
=> NOISSUE: remove doubled trace in logs

logicrunner/builtin/contract/wallet/wallet.go
fixed nil error panic 
fixed nil error panic
don't know
fixed nil error panic
=> INS-3040: fix panic

network/tests/pinger_test.go
=> INS-3041: skip TestPingerStress

logicrunner/result_matcher.go
Save unwanted responses in contract requester
=> NOISSUE: save unwanted responses

cmd/benchmark/main.go
Fixed bench error when repetition >= 1
Changed calculation of total balance after transfers. Now multi repetition with fee
launch ./scripts/bench.sh -r=2
bench fix
=> INS-3057: bench fix

logicrunner/logicrunner.go, logicrunner/result_matcher.go
=> NOISSUE: set traceID if resend to still execution

logicrunner/result_matcher.go
=> NOISSUE: save still execution for pulse

ledger/light/integration/requests_test.go
=> INS-3029 detached incoming fails with error

ledger/light/handle/init.go
=> NOISSUE:update meta for pass

functest/member_get_test.go, functest/utils_test.go
fixed create member in utils
fixed create member in utils
launch tests
=> INS-3084: fixed create member in utils

network/hostnetwork/hostnetwork.go
=> INS-2998: fix handlers race

insolar/message/message.go, insolar/messagebus.go, insolar/pulse/db.go, instrumentation/instracer/serialize.go, ledger/drop/drop.go, logicrunner/common/serialize.go, logicrunner/goplugin/ginsider/ginsider.go, messagebus/parcel.go, messagebus/senders.go, network/storage/pulse.go, pulsar/payload.go
Used insolar.[Must]Serialize/Deserialize everywhere
=> NOISSUE: use one serialization

logicrunner/artifacts/client.go
* copy repeated code into `send` method
* drop sendWithRetry method as it duplicates functionality of bus.RetrySender
=> refactor artifacts.client code

logicrunner/builtin/builtin.go, logicrunner/builtin/foundation/base_contract.go, logicrunner/builtin/foundation/context.go, logicrunner/builtin/foundation/error.go, logicrunner/builtin/foundation/helpers.go, logicrunner/builtin/proxyhelper.go, logicrunner/goplugin/ginsider/ginsider.go
- added new helper GetRequest()
- refactored foundation a bit
=> INS-3076: added helper to get request from global context

insolar/jet/coordinator_mock.go, insolar/jet/jet.go, insolar/jetcoordinator/jetcoordinator.go, logicrunner/executionbroker.go, logicrunner/executionbroker_test.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
simplifies code a bit, pulse accessor already dependancy of
the coordinator
=> IsMeAuthorizedNow method in jet.Coordinator

logicrunner/goplugin/goplugintestutils/utils.go
=> INS-3116: return result for deploy code

functest/main_test.go, functest/register_parent_test.go, logicrunner/artifacts/client.go
=> INS-3098: call to construct from constructor

logicrunner/rpc_methods.go
=> INS-3097: call on not exist object is not system error

logicrunner/handle_calls.go
If pulse changed in handle_call after request was registered
=> INS-2702: loop detection fixes

configuration/ledger.go, ledger/light/integration/server_test.go, ledger/light/replication/cleaner.go, ledger/light/replication/cleaner_test.go, server/internal/light/components.go
=> INS-3121 possible fix. add CleanerDelay

functest/upload_contract_test.go, testutils/core.go
TestCallUploadedContract upload contract only once
=> INS-3134 change upload with random string to upload once

functest/main_test.go, scripts/insolard/bootstrap_template.yaml
=> INS-3089: 11 nodes in tests

instrumentation/introspector/pubsubwrap/pubsubwrap.go
=> INS-3126 count only incoming

cmd/pulsard/main.go, insolar/pulse.go, network/tests/pulsar_test.go, pulsar/testpulsar.go
Left single source of truth about the first pulse number.
=> NOISSUE: use single source of thurth for first pulse

network/pulsenetwork/distributor.go
Fixed goroutine leak.
Added a stop method.
Run network tests.
Distributor is a stopper.
=> Distributor is a stopper.

api/status.go
add handling pulse.ErrNotFound in getStatus API
=> INS-3139 add handling pulse.ErrNotFound in getStatus API

Gopkg.lock
See https://github.com/insolar/go-actors/pull/1
=> INS-2771: upgrade go-actors to the latest version

logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go, server/internal/virtual/components.go
remove pulseAccessor from NewLogicRunner
move sender initialization from New to Init
run tests
=> INS-3150 pulseAccessor from injection

logicrunner/executionbroker_test.go
=> NO_ISSUE_fix_wait_time

insolar/bus/bus.go, insolar/flow/internal/thread/thread.go, instrumentation/instracer/tracer.go, ledger/heavy/proc/send_requests.go, ledger/heavy/pulsemanager/pulsemanager.go, ledger/light/executor/filaments.go, ledger/light/executor/hot_sender.go, ledger/light/executor/jet_fetcher.go, ledger/light/executor/jet_splitter.go, ledger/light/proc/send_requests.go, ledger/light/replication/lightreplicator.go, logicrunner/artifacts/client.go, messagebus/messagebus.go
=> Ins 2918 trace in flow

cmd/pulsewatcher/pulsewatcher.go
Print compact error string when a node is down
=> NOISSUE: compact error in pulsewatcher

api/call.go, api/call_test.go
Changed compare function from string to byte format
=> INS-3151: compare hashes in byte format

cmd/pulsewatcher/pulsewatcher.go
Added compact string for another error
=> NOISSUE: another pulsewatcher update

functest/logicrunner_test.go
=> INS-2798: TestRecursiveCallError retries timeouts for now

functest/send_money_test.go, logicrunner/builtin/contract/wallet/wallet.go
Returned balance check to TestTransferMoney functest.
=> INS-3070: check balance in TestTransferMoney

api/call.go, api/info.go, api/node_cert.go, api/seed.go, contractrequester/contractrequester.go, ledger/heavy/handler/handler.go, ledger/light/proc/ensure_index.go, ledger/light/proc/send_object.go, logicrunner/artifacts/client.go, messagebus/messagebus.go
=> Ins 2919 trace improvments

cmd/pulsewatcher/README.md
=> NO_ISSUE_update_pulsewatcher_readme

network/servicenetwork/servicenetwork.go
=> INS-3146 add additional log

functest/logicrunner_test.go
remove flacky code from test, we have TestNoWaitCall for this
=> INS-3144 remove flacky code

network/consensus/gcpv2/phasebundle/bundle_factory.go
=> NOISSUE: remove debug locking

network/tests/bootstrap_test.go, network/tests/main_test.go
=> NOISSUE: skip integration tests

functest/logicrunner_test.go, logicrunner/rpc_methods.go
remove restrict on external calls from  immutable
remove if, change test
run tests
=> INS-3172 remove restrict on external calls from  immutable

network/consensus/common/endpoints/addrs.go, network/consensus/gcpv2/core/errors/round_ctl_errors.go, network/consensus/gcpv2/core/realm_core.go, network/consensus/gcpv2/core/realm_full.go, network/consensus/gcpv2/core/realm_prep.go, network/consensus/gcpv2/core/round_controller.go
=> NOISSUE: Additional logging

logicrunner/executionbroker_test.go
=> INS-2798: skip test untill update

network/consensus/gcpv2/member_controller.go
=> INS-3174: possible fix for consensus didn't finish

api/status.go, cmd/pulsewatcher/pulsewatcher.go, network/consensus/adapters/profile.go, network/node/accessor.go, scripts/insolard/bootstrap_template.yaml, scripts/insolard/check_status.sh, scripts/insolard/launchnet.sh
=> NOISSUE: fix non discovery nodes

scripts/insolard/bootstrap_template.yaml
=> NOISSUE: disable joiner

logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go, logicrunner/pulsemanager/pulsemanager.go, server/internal/virtual/components.go
Move `ResultsMatcher.Clear()` under GIL section in `PulseManager`
Run tests
=> INS-2798: move clear resaltmatcher

configuration/hostnetwork.go, network/gateway/base.go, network/gateway/joiner_bootstrap.go, network/gateway/nonetwork.go, network/gateway/nonetwork_test.go, network/servicenetwork/servicenetwork.go
Added backoff for no network state.
Added exponential backoff with max timeout limit.
Launch net.
Backoff for no network state.
=> Backoff for no network state.

functest/deposit_transfer_test.go
added one pulse duration
added one pulse duration
test
TestDepositTransferToken
=> INS-3171: added one pulse duration

functest/deposit_migration_test.go, functest/deposit_transfer_test.go, functest/get_balance_test.go, functest/get_node_ref_test.go, functest/member_create_test.go, functest/member_get_test.go, functest/member_migration_create_test.go, functest/new_api_test.go, functest/register_node_test.go, functest/send_money_test.go
We need checks not nil before access methods
=> Add checks for not nil errors in functests

bootstrap/contracts/contracts.go, insolar/genesis.go, insolar/record/record.go, insolar/reply/base.go, insolar/reply/ledger.go, logicrunner/builtin/contract/member/member.go
remove unused code
remove delegate code
run tests
=> NO_ISSUE remove unused delegate frome code

functest/logicrunner_test.go, logicrunner/builtin/contract/costcenter/costcenter.go, logicrunner/builtin/contract/deposit/deposit.go, logicrunner/builtin/contract/member/member.go, logicrunner/builtin/contract/migrationshard/migrationshard.go, logicrunner/builtin/contract/nodedomain/nodedomain.go, logicrunner/builtin/contract/noderecord/noderecord.go, logicrunner/builtin/contract/pkshard/pkshard.go, logicrunner/builtin/contract/rootdomain/rootdomain.go, logicrunner/builtin/contract/wallet/wallet.go, logicrunner/builtin/proxy/costcenter/costcenter.go, logicrunner/builtin/proxy/deposit/deposit.go, logicrunner/builtin/proxy/member/member.go, logicrunner/builtin/proxy/migrationshard/migrationshard.go, logicrunner/builtin/proxy/nodedomain/nodedomain.go, logicrunner/builtin/proxy/noderecord/noderecord.go, logicrunner/builtin/proxy/pkshard/pkshard.go, logicrunner/builtin/proxy/rootdomain/rootdomain.go, logicrunner/builtin/proxy/wallet/wallet.go, logicrunner/preprocessor/main.go
Added space before immutable annotation and added this annotation to all immutable method 
Added space before immutable annotation and added this annotation to all immutable met
Launch tests
immutable methods
=> INS-2811: added immutable annotations

logicrunner/currentexecution.go, logicrunner/logicrunner.go
=> INS-3122: remove logicrunner.Ref

api/requester/config.go, api/requester/requester.go, functest/new_api_test.go, logicrunner/builtin/contract/member/member.go, logicrunner/builtin/proxy/member/member.go
added ommitempty to params and callparams
added ommitempty to params and callparams
TestNilParams
=> INS-3042: added ommitempty

scripts/insolard/trace.sh
=> Noissue trace sh

ledger/heavy/proc/replication.go
heavy node should fail for data consistency reason
(consistency should be achieved after node reload)
=> INS-3087: heavy node should raise fatal error on failed replication

configuration/hostnetwork.go, network/controller/common/options.go
Decreased network backoff.
Decreased network backoff.
Run tests.
Decreased network backoff.
=> Network backoff decrease.

logicrunner/handle_abandonedrequestsnotification.go, logicrunner/handle_executorresults.go, logicrunner/handle_executorresults_test.go, logicrunner/handle_pending_finished.go, logicrunner/handle_pending_finished_test.go, logicrunner/handle_still_executing.go, logicrunner/handle_still_executing_test.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go, logicrunner/state_storage_mock.go, logicrunner/statestorage.go, logicrunner/statestorage_test.go
Also add WriteController to handlers, since now there's no "objectState" and it can't be locked, so race-condition with OnPulse may occur
=> INS-3183: Split stateStorage map

network/hostnetwork/handlers.go
goroutine was waiting for TCP transport to begin stopping process
by canceling context. this code resulted in a goroutine for every
stream ever created. Fix leak by combining close by transport
and close by remote peer in one goroutine
=> INS-3212: goroutine in stream handling was leaking

network/consensus/gcpv2/censusimpl/population.go
=> INS-3204: possible fix

api/main.go, api/seedmanager/seedmanager.go, contractrequester/contractrequester.go, insolar/jet/store.go, insolar/node/node.go, insolar/store/badger.go, instrumentation/introspector/pubsubwrap/middleware_locker.go, instrumentation/introspector/pubsubwrap/middleware_stat.go, ledger/drop/memory.go, logicrunner/currentexecution/currentexecution.go, logicrunner/pulsemanager/pulsemanager.go, pulsar/neighbour.go
I don't know reason not to use defer
=> use `defer Unlock()` in every place where it's possible w/o many changes

server/internal/heavy/components_test.go, server/internal/light/components_test.go, server/internal/virtual/components_test.go
change some DB path's for tests 
=> Ins-3218 fix db path

network/transport/tcp.go
=> NOISSUE: Limit connection time

logicrunner/builtin/foundation/stablemap_test.go
=> NOISSUE: speedup stablemap tests

bootstrap/contracts/contracts.go, functest/deposit_migration_test.go, logicrunner/builtin/contract/account/account.go, logicrunner/builtin/contract/account/account.wrapper.go, logicrunner/builtin/contract/costcenter/costcenter.go, logicrunner/builtin/contract/costcenter/costcenter.wrapper.go, logicrunner/builtin/contract/deposit/deposit.go, logicrunner/builtin/contract/deposit/deposit.wrapper.go, logicrunner/builtin/contract/member/member.go, logicrunner/builtin/contract/member/member.wrapper.go, logicrunner/builtin/contract/wallet/wallet.go, logicrunner/builtin/foundation/helpers.go, logicrunner/builtin/proxy/account/account.go, logicrunner/builtin/proxy/costcenter/costcenter.go, logicrunner/builtin/proxy/deposit/deposit.go, logicrunner/builtin/proxy/member/member.go
…r third confirm
Transfer from account to deposit
Transfer from migration daemon account to deposit after third migration; changed TestMigrationToken; + some refactor;
TestMigrationToken
=> Ins 3221 transfer to deposit

logicrunner/executionbroker_test.go
fix race test
change mock functions behavior
run logicrunner tests with count 10.000 on master and on my branch
=> INS-3214 fix race, except another event

api/healthcheck.go, api/main.go, api/status.go, insolar/network.go, network/servicenetwork/status.go, network/servicenetwork/status_test.go
Added NetworkStatus interface.
Implemented GetNetworkStatus()
Run tests.
Implemented NetworkStatus interface.
=> Ins 3220 network status healthcheck

functest/deposit_migration_test.go
fixed migration test
fixed TestMigrationToken
launch tests
=> INS-3241: fixed migration test

insolar/bus/retryer.go, insolar/bus/retryer_test.go
Before retry, we set new UUID to message.
Run tests.
=> Noissue recreate msg in retry

network/consensus/common/pulse/pulse_number.go, network/consensus/common/pulse/pulse_number_test.go
fix calculation of pulse time
subtract base time pulse
run new unit test
=> NOISSUE: fix approximate pulse time

insolar/record.go, ledger/heavy/exporter/record_exporter_server_test.go, ledger/object/lock.go, ledger/object/record_test.go
Deleted all methods allowing to change IDs and References.
=> INS-3122: make ID and Reference immutable

functest/main_test.go, scripts/insolard/bootstrap_template.yaml
=> 5 nodes in functests

functest/deposit_transfer_test.go
fixed deposit transfer
Add waiting for saga received 
Launch test TestDepositTransferToken with count 100
=> INS-3171: fixed deposit transfer

functest/deposit_transfer_test.go, functest/utils_test.go, logicrunner/builtin/contract/deposit/deposit.go
Add partial release
Compare amount of transfer with available amount
TestDepositTransferToken
=> INS-3236: partial release realization

logicrunner/shutdown/flag.go, logicrunner/shutdown/flag_test.go
- no deadlocking in Stop
- no panicks in Done
=> NOISSUE: add ability for multiple calls of Stop/Done

ledger/heavy/executor/heavyreplicator.go, ledger/heavy/exporter/pulse_exporter_server.go, ledger/heavy/exporter/pulse_exporter_server_test.go, ledger/heavy/exporter/record_exporter_server.go, ledger/heavy/exporter/record_exporter_server_test.go, ledger/heavy/handler/handler.go, ledger/heavy/proc/replication.go
=> INS-3196 add a few logs to different places

insolar/bus/bus.go, insolar/bus/metrics.go, insolar/bus/retryer.go, instrumentation/insmetrics/insmetrics.go, ledger/light/executor/lightreplicator.go, ledger/light/executor/metrics.go, messagebus/metrics.go, scripts/monitor/grafana/dashboards/bus.json
add metrics for message bus and grafana dashboard for them
=> Ins 3195 ledger metrics

insolar/pulse/db.go
=> cache for pulse.DB on heavy. fix hot path

ledger/object/index_memory.go, ledger/object/index_memory_test.go, ledger/object/record_test.go
=> additional  checks for lifeline consistency

insolar/gen/reference.go, ledger/drop/memory_test.go, network/controller/pinger/pinger_test.go, network/controller/pulsecontroller_test.go, network/node/refset_test.go, network/node/snapshot_test.go, network/routing/table_test.go, utils/entropy/entropy_test.go
Refactored UniqueJetIDs and UniqueReferences
=> NOISSUE: refactor gen unique jetids and references

network/consensus/gcpv2/core/round_controller.go
=> Starting/Stopping consensus log to Warn level

network/transport/udp.go
=> udpMaxPacketSize = 1450

ledger/light/executor/filaments.go, ledger/light/integration/requests_test.go
- Add SetPulse method for requests integration tests. 
- Fix findFilament bug.
`go test ./ledger/light/integration`
=> Ins 3029 add some checks

ledger/heavy/executor/jetkeeper.go
=> remove useless calls for updateTopSyncPulse

insolar/bus/bus.go, insolar/bus/retryer.go, insolar/flow/dispatcher/dispatcher.go, insolar/flow/dispatcher/metrics.go, insolar/flow/internal/thread/metrics.go, insolar/flow/internal/thread/thread.go, ledger/light/executor/jet_splitter.go, ledger/light/executor/metrics.go, ledger/light/executor/pulsemanager.go, scripts/monitor/grafana/dashboards/flow-dispatcher.json, scripts/monitor/grafana/dashboards/flow-procedures.json
1. Add latency metrics to flow
2. Add jets and drops counter metrics to light node code
=> INS-3195: add metrics

Gopkg.lock, configuration/log.go, log/log.go, log/log_test.go, log/zerolog.go
pauses in File.Write may cause random system pauses for quite
a while
=> buffered logs using diodes, panic if system can not cope

network/consensus/adapters/feeder.go, network/consensus/adapters/handlers.go, network/consensus/adapters/pulse.go, network/consensus/serialization/context.go, network/consensus/serialization/globula_protocol.go, network/consensus/serialization/packet_reader.go, network/consensus/serialization/pulseserialization/serialization.go
=> NOISSUE: fix pulse data serialization

functest/logicrunner_test.go, logicrunner/logicexecutor/logicexecutor.go, logicrunner/logicexecutor/logicexecutor_test.go
- What I did
Made prototype mismatch logical error
=> INS-3017: Make prototype mismatch logical error.

log/log_env_test.go, log/log_test.go, metrics/metrics_test.go
move slow tests under `slowtest` tag
=> INS-3287: move slow tests under slowtest tag

network/gateway/base.go
=> Noissue bootstrap fixes

network/hostnetwork/hostnetwork.go
=> NOISSUE: network err -> warn

ledger/heavy/pulsemanager/pulsemanager.go, server/internal/heavy/components.go
Remove FIL from heavy pulse manager
=> INS-3281: remove gil from heavy pulsemanager

instrumentation/insmetrics/insmetrics.go, log/metrics.go, log/metrics_hook.go, log/zerolog.go, metrics/metrics.go, scripts/docker-compose.yml, scripts/monitor.sh
* add log metrics 
* dashboard for log metrics
* update monitor.sh tools
=> Ins 3195 logger metrics

insolar/bus/bus.go
=> INS-3267 err -> to warn

ledger/light/handle/get_request_info.go, ledger/light/proc/ensure_index.go, ledger/light/proc/ensure_index_test.go, ledger/light/proc/proc.go
=> Revert "INS-3296: Add hot waiting for request info."

ledger/light/handle/get_request_info.go, ledger/light/proc/ensure_index.go, ledger/light/proc/ensure_index_test.go, ledger/light/proc/proc.go
=> Revert "Revert "INS-3296: Add hot waiting for request info.""

functest/deposit_migration_test.go, functest/deposit_transfer_test.go, functest/test_utils.go
Activate daemon in every test, which expect they were activated.
Run tests
=> INS-3312: activate daemons in functests

functest/new_api_test.go
Add func tests for empty signature, signature with invalid structure, and signature from another user.
Run tests.
=> INS-3115: add new incorrect signature functests

functest/logicrunner_test.go, functest/pressure_test.go, insolar/utils/utils.go, logicrunner/logicrunner_unit_test.go, logicrunner/shutdown/flag_test.go, testutils/core.go
=> NOISSUE: Move SyncT to testutuils

logicrunner/common/transcript.go, logicrunner/executionregistry/execution_registry.go, logicrunner/handle_additional_call.go, logicrunner/handle_additional_call_test.go, logicrunner/handle_executorresults.go, logicrunner/logicrunner.go, logicrunner/procs.go, logicrunner/requestsfetcher.go
improve setting logger and context for transcript
=> INS-3219: try to maintain logger with object/request fields

ledger/light/executor/cleaner_test.go
=> #INS-3307 added time to test

network/gateway/base.go, network/gateway/complete.go, network/gateway/nonetwork.go, network/tests/main_test.go, network/tests/suite_test.go
test enabled and fixed: 
* TestNetworkConsensusManyTimes
* TestJoinerNodeConnect
* TestNodeLeave
* TestNodeGracefulLeave
=> INS-1634 enable and fix network integration tests

logicrunner/executionbroker.go, logicrunner/executionbroker_test.go, logicrunner/executionregistry/execution_registry.go, logicrunner/executionregistry/execution_registry_mock.go, logicrunner/executionregistry/execution_registry_test.go, logicrunner/logicrunner_unit_test.go
do our best to prevent parallel executions
=> INS-3219: don't start second execution if registry has record

functest/send_money_test.go, logicrunner/builtin/contract/costcenter/costcenter.go
What I did:
- changed fee calculation
=> WLT-911 changed fee calculation

scripts/dev/Dockerfile, scripts/dev/container.sh
Added container script for limiting resources.
=> NOISSUE: Add container script for limiting resources.

ledger/heavy/executor/backuper_test.go
=> fix goroutine leak

Gopkg.lock, logicrunner/logicrunner.go, logicrunner/outgoing_request_sender_mock.go, logicrunner/outgoingsender.go, logicrunner/rpc_methods_test.go
added force terminate in go-actors 
=> #INS-3293 fix goroutine leak in test

ledger/heavy/executor/initial_state_keeper.go, ledger/heavy/executor/initial_state_keeper_test.go
fix heavy restart without indexes
=> fix heavy restart without indexes

insolar/node/node_test.go, log/zerolog.go
=> Ins 3327 logger graceful exit

logicrunner/executionbroker_test.go, logicrunner/handle_calls_test.go
mc.Wait can't be less than 1 minute - CI can't handle it
=> NO_ISSUE_fix_wait

Gopkg.lock, Gopkg.toml, instrumentation/insmetrics/insmetrics.go, instrumentation/instracer/tracer.go, ledger/heavy/executor/finalize_pulse.go, ledger/heavy/executor/metrics.go, ledger/light/executor/lightreplicator.go, ledger/light/executor/metrics.go, ledger/light/proc/hot_data.go, ledger/light/proc/metrics.go, ledger/light/proc/set_request.go, ledger/light/proc/set_result.go, network/gateway/complete.go, network/gateway/metrics.go, scripts/dev/metrics-filter.py, scripts/dev/metrics-list-csv.sh, scripts/insolar_metrics.csv, scripts/monitor/grafana/dashboards/logging.json
* add some metrics
* updated opencensus dependencies
* add missed logs dashboard
=> Ins-3195: metrics

configuration/ledger.go, ledger/heavy/executor/backuper.go, ledger/heavy/executor/backuper_test.go, ledger/heavy/executor/intergration/backuper_test.go, ledger/heavy/executor/intergration/post_process_backup.sh
BackupMaker run command from config after creating backup
=> Ins 3348 bakuper notify about backup

insolar/network.go, insolar/networkstate_string.go, network/gateway/base.go, network/gateway/complete.go, network/gateway/gatewayer.go, network/gateway/gatewayer_test.go, network/gateway/wait_consensus.go, network/gateway/wait_minroles.go, network/gateway/wait_pulsar.go, network/gateway/wait_pulsar_test.go, network/interfaces.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/servicenetwork_test.go, network/tests/main_test.go, network/tests/suite_test.go, testutils/network/gateway_mock.go, testutils/network_mock.go
=> NOISSUE: complete network transition

cmd/benchmark/main.go, cmd/benchmark/scenario.go
What I did:
- fixed benchmark commission
=> INS-3353: fix benchmark commission

cmd/pulsard/main.go, cmd/testpulsard/main.go, server/internal/heavy/server.go, server/internal/light/server.go, server/internal/virtual/server.go
Node version now shows before config in logs
=> show version before config

functest/deposit_migration_test.go, functest/test_utils.go, logicrunner/builtin/contract/member/member.go
What I did:
- converted INS to XNS
=> WLT-926: convert INS to XNS

logicrunner/common/proxyctx.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
=> linting, nothing special

network/consensus/adapters/feeder.go, network/consensus/gcpv2/core/realm_prep.go, network/gateway/complete.go, network/gateway/gatewayer.go, network/gateway/wait_consensus.go, network/gateway/wait_consensus_test.go, network/gateway/wait_majority.go, network/gateway/wait_majority_test.go, network/gateway/wait_minroles.go, network/gateway/wait_minroles_test.go, network/gateway/wait_pulsar.go, network/gateway/wait_pulsar_test.go, network/interfaces.go, testutils/network/gatewayer_mock.go
=> NOISSUE: consensus stabilization

ledger/light/executor/waiter_test.go
=> INS-3329: Fix test race.

network/gateway/base.go, network/gateway/complete.go, network/gateway/gatewayer.go, network/gateway/wait_consensus.go, network/gateway/wait_consensus_test.go, network/gateway/wait_majority.go, network/gateway/wait_majority_test.go, network/gateway/wait_minroles.go, network/gateway/wait_minroles_test.go, network/gateway/wait_pulsar.go, network/gateway/wait_pulsar_test.go, network/interfaces.go, testutils/network/gatewayer_mock.go
=> NOISSUE: fail state refactoring

log/zerolog.go
=> INS-3327 trying to fix troubles with last row. it works

ledger/light/executor/pulsemanager.go, ledger/light/executor/waiter.go
Made jet check error more readable.
=> INS-3332: Simplify jet check.

logicrunner/logicexecutor/logicexecutor.go, logicrunner/logicexecutor/logicexecutor_test.go
add a few checks into logic executor component
=> check len of new state and returns in logic executor

contractrequester/contractrequester.go, contractrequester/contractrequester_test.go, insolar/bus/retryer.go, ledger/light/handle/init.go, logicrunner/handle_init.go
added error wrapper in contractrequester handler, fixed bad error handling in logicrunner
run tests
=> INS-3351: add coded error reply in contractrequester

network/gateway/wait_pulsar.go
=> NOISSUE: add missing code

network/gateway/base.go, network/nodenetwork/nodekeeper.go, network/termination/handler.go
=> INS-3345: network panic with context

Gopkg.lock
=> #INS-3371 fixed panic in go-actors, lock file updated

functest/logicrunner_test.go
fix test
write it correctly
run tests
=> INS-3370 check both saga methods

insolar/bus/retryer.go, ledger/light/proc/set_result.go, logicrunner/handle_abandonedrequestsnotification.go, logicrunner/handle_additional_call.go, logicrunner/handle_calls.go, logicrunner/handle_calls_test.go, logicrunner/handle_executorresults.go, logicrunner/handle_executorresults_test.go, logicrunner/handle_init.go, logicrunner/handle_pending_finished.go, logicrunner/handle_still_executing.go, logicrunner/handle_still_executing_test.go, logicrunner/logicrunner.go
review all message handlers in logic runner for replies inconsistencies
=> Ins 3368 review write controller uses

Gopkg.lock, Gopkg.toml
* Fixed branch of `insolar/rpc` package
* Updated other dependencies
`dep ensure -update`
`dep ensure` and run tests
=> NOISSUE: fixed version of insolar/rpc and updated other deps

logicrunner/handle_calls.go, logicrunner/handle_calls_test.go, logicrunner/handle_init.go, logicrunner/logicrunner.go, logicrunner/procs.go
=> no more LogicRunner in Dependencies struct

cmd/insolar/certgen.go
Update url in insolar cmd
Run not-discovery node via launchnet.sh
=> NOISSUE: update url in insolar cmd

network/consensus/adapters/tests/main_test.go
=> NOISSUE: fix joiner queue in tests

scripts/insolard/bootstrap_template.yaml
pulse can change between two requests and trigger situation.
switch to 20 gap
=> INS-3337: lokup is checked using pulse, 10 is not enough

ledger/heavy/executor/finalize_pulse.go, ledger/heavy/executor/finalize_pulse_test.go
Remove async logic from FinalizePulse since it's not needed there
Run tests
=> Ins 3264 refact finalize pulse

ledger/light/handle/activate_object.go, ledger/light/handle/activate_object_test.go, ledger/light/handle/deactivate_object.go, ledger/light/handle/deactivate_object_test.go, ledger/light/handle/get_code.go, ledger/light/handle/get_code_test.go, ledger/light/handle/get_jet.go, ledger/light/handle/get_jet_test.go, ledger/light/handle/get_object.go, ledger/light/handle/get_object_test.go, ledger/light/handle/get_pendings.go, ledger/light/handle/get_pendings_test.go, ledger/light/handle/set_outgoing_request_test.go, ledger/light/handle/set_result_test.go
Unit Tests for handlers:
- ActivateObject
- DeactivateObject
- GetCode
- GetJet
- GetObject
- GetPendings
=> Ins 2871 more unit tests for ledger

contractrequester/contractrequester.go, contractrequester/contractrequester_test.go, contractrequester/handle.go, ledger/heavy/integration/server_test.go, ledger/heavy/pulsemanager/pulsemanager.go, ledger/light/executor/pulsemanager.go, ledger/light/integration/server_test.go, logicrunner/pulsemanager/pulsemanager.go, server/internal/heavy/components.go, server/internal/light/components.go, server/internal/virtual/components.go
- moved contractrequester handling to flow
- added support for multiple dispatchers in pulse managers
using dispatcher dispatcher
make functest
=> INS-3354: moved contractrequester handling to flow

logicrunner/handle_abandonedrequestsnotification.go, logicrunner/handle_abandonedrequestsnotification_test.go
* no need in procedure because of write controller
* log object field not target
* log object reference, not ID
* write tests
=> refactor handler of abandoned requests notification

network/transport/transport_test.go
No panic in TestStreamTransport.
Added Require.
Added require.
Run tests.
No panic in TestStreamTransport.
=> Added Require.

Makefile, ledger/heavy/integration/pulsefinalization_test.go, ledger/heavy/integration/server_test.go
Fix heavy integral tests
Switch them on in MakeFile
=> Noissue fix heavy integral test

logicrunner/handle_update_jet.go, logicrunner/handle_update_jet_test.go
* unmarshal and type check in one go
* test error cases
=> cleanup handler of UpdateJet, more tests

network/consensus/gcpv2/core/population/node_appearance.go, network/consensus/gcpv2/core/population/realm_dyn_population.go, network/consensus/gcpv2/core/round_controller.go
=> INS-3325: races

network/tests/bootstrap_test.go, network/tests/main_test.go, network/tests/suite_test.go
remove fixtures, refactor
additional checkers
pulse delta increased 
waitForNodeJoin, waitForNodeLeave, assertNetworkInConsistentState
=> INS-2703 rework network integration tests

network/gateway/base.go, network/gateway/complete.go, network/gateway/watchers.go
=> INS-3400: add pulse watchdog

contractrequester/contractrequester.go, contractrequester/contractrequester_test.go, contractrequester/handle.go, functest/activatedaemon_test.go, logicrunner/logicrunner.go
- moved to pulse from flow
- removed currentexecutor check
run tests
=> INS-3408: proper flow pulse usage, better handling

ledger/light/handle/get_filament.go, ledger/light/handle/get_filament_test.go, ledger/light/handle/get_object.go, ledger/light/handle/get_request.go, ledger/light/handle/get_request_info.go, ledger/light/handle/get_request_info_test.go, ledger/light/handle/get_request_test.go, ledger/light/handle/init.go, ledger/light/proc/proc.go, ledger/light/proc/send_filament.go
Unit Tests for handlers:
- GetRequest
- GetRequestInfo
- GetFilament (GetRequests was renamed to GetFilament, with companion procedure - SendRequests to SendFilament)
=> Ins 2871 more tests coverage for ledger

cmd/benchmark/README.md, cmd/benchmark/main.go
=> INS-3397 update readme, add new line

bootstrap/bootstrap.go, functest/activatedaemon_test.go, functest/deposit_migration_test.go, functest/deposit_transfer_test.go, functest/helloworld_test.go, functest/member_get_test.go, functest/member_migration_create_test.go, functest/test_utils.go, testutils/launchnet/launchnet.go
What I did:
- added trimAddress
- added trimmedAddress to slice
=> WLT-950: fix bug with load migration address

ledger/drop/drop_cmp_test.go
=> INS-3402 fix problems, when gen creates two equal pulses and jets

scripts/monitor.sh, server/internal/heavy/server.go, server/internal/light/server.go
logging context fix
removed nodeRef and nodRole from logs
=> #INS-3380 heavy/light logging context fix

bootstrap/bootstrap.go, bootstrap/config.go, bootstrap/keys.go, scripts/insolard/bootstrap_template.yaml, testutils/launchnet/launchnet.go
Add to bootstrap path to not discovery nodes keys for generation
Run tests
=> INS-3365: add param to bootstrap, create certs for not-discovery

bootstrap/bootstrap.go
Update log in bootstrap
Run tests
=> NOISSUE: update log

ledger/light/executor/filaments_test.go
=> INS-3403: Fix test.

cmd/insolar/README.md, cmd/insolar/main.go
What I did:
- added migrationAdmin asCaller to insolar utility
=> WLT-953: added migrationAdmin asCaller to insolar utility

Gopkg.lock
dep ensure -update github.com/insolar/go-actors
=> #INS-3371 lock update

logicrunner/handle_calls.go, logicrunner/handle_calls_test.go, logicrunner/procs.go
ensured index not found as logical error
with helper
run tests
=> INS-3321: index not found should be final error

insolar/bus/metrics.go, insolar/flow/dispatcher/metrics.go, insolar/flow/internal/thread/metrics.go, instrumentation/insmetrics/insmetrics.go, ledger/drop/metrics.go, ledger/heavy/executor/finalize_pulse.go, ledger/heavy/executor/finalize_pulse_test.go, ledger/heavy/executor/jet_keeper_gen_mock.go, ledger/heavy/executor/jetinfo.go, ledger/heavy/executor/jetkeeper.go, ledger/heavy/executor/metrics.go, ledger/heavy/proc/metrics.go, ledger/light/executor/metrics.go, ledger/light/proc/metrics.go, ledger/object/index_db.go, ledger/object/index_memory.go, ledger/object/metrics.go, log/metrics.go, logicrunner/artifacts/metrics.go, logicrunner/goplugin/metrics.go, network/controller/metrics.go, network/gateway/metrics.go, network/metrics.go, pulsar/metrics.go, scripts/dev/metrics-filter.py, scripts/dev/metrics-list-csv.sh, scripts/insolar_metrics.csv, scripts/monitor/grafana/dashboards/heavy-node.json, scripts/monitor/grafana/dashboards/light-material-nodes.json, scripts/monitor/grafana/dashboards/network.json
refresh metrics and dashboards
=> Ins 3415 dashboards and metrics

docs/source/integration.rst
Added hardware requirements for POC private networks.
=> [DOC] hardware requirements for POC private nets

scripts/insolard/launchnet.sh
added trap SIGCHLD
with jobs commang
kill node while running tests
=> add chld trap

ledger/object/index_memory.go, scripts/monitor/grafana/dashboards/light-material-nodes.json
* fix indexes counter
* update dashboard
=> Ins 3415 dashboards and metrics 2

scripts/generate_insolar_configs.go, scripts/monitor/grafana/dashboards/bus.json, scripts/monitor/grafana/dashboards/consensus.json, scripts/monitor/grafana/dashboards/flow-dispatcher.json, scripts/monitor/grafana/dashboards/flow-procedures.json, scripts/monitor/grafana/dashboards/heavy-node.json, scripts/monitor/grafana/dashboards/light-nodes.json, scripts/monitor/grafana/dashboards/logging.json, scripts/monitor/grafana/dashboards/network.json
=> Ins 3447 normalize dashboards

api/call_wrapper.go, functest/deposit_transfer_test.go, functest/member_create_test.go, functest/member_get_test.go, functest/member_migration_create_test.go, functest/new_api_test.go, functest/register_node_test.go, functest/send_money_test.go
=> Fix errors

scripts/insolard/launchnet.sh
=> NOISSUE: killing with buffer flushing

instrumentation/instracer/serialize.go, instrumentation/instracer/tracer.go
And even never save it. Everithing is in external traceid
=> INS-3278: Do not transfer TraceId via network in SpanData

cmd/benchmark/main.go, functest/main_func_test.go, insolar/defaults/defaults.go, testutils/DiscoveryNodesLogReader.go, testutils/discovery_nodes_log_reader.go
=> INS-3373 check log errors refactor

api/call_wrapper.go
Added more correct returning error format
By testing
=> WLT-984: return more concrete error

cmd/insolard/main.go, cmd/pulsard/main.go, scripts/insolard/launchnet.sh, server/internal/heavy/server.go, server/internal/light/server.go, server/internal/virtual/server.go, server/server.go
Control jaeger behaviour via config parameters and env
=> Ins 3278 jaeger control

insolar/gen/reference.go, ledger/light/executor/request_checker.go, ledger/light/executor/request_checker_test.go
=> INS-3227: Add request checker tests.

scripts/changelog.py
Added changelog generator script.
Requires Python 3, Jinja 2, requests, logzero.
```
pip3 install jinja2 requests logzero
``` 
Usage:
```
scripts/changelog.py v0.9.0-rc3 v0.9.0-rc4 -e <your email> -t <JIRA api token> --html=.artifacts/release.html
```
You can generate the token here: https://id.atlassian.com/manage/api-tokens
=> NOISSUE: added changelog generator script

functest/0_test.go, scripts/_logger/.gitignore, scripts/_logger/README.md, scripts/_logger/go.mod, scripts/_logger/main.go, scripts/insolard/launchnet.sh, testutils/launchnet/launchnet.go
* add tool for log rotation
* rotate logs on every functest start
=> Ins 3050 functest logs rotate

cmd/pulsard/main.go, network/pulsenetwork/distributor.go, network/pulsenetwork/metrics.go, pulsar/metrics.go, pulsar/pulsar.go
=> Ins 3448 pulsar metrics

testutils/launchnet/launchnet.go
cause pkill is not available in CI
=> NOISSUE: use killall instead of pkill

network/controller/rpc_controller.go, network/hostnetwork/future/handler.go
Added future logs for network.
=> NOISSUE: Add future logs.

contractrequester/contractrequester.go
=> additional log for unwanted result

api/status.go, insolar/jetcoordinator/jetcoordinator.go, insolar/jetcoordinator/jetcoordinator_test.go, ledger/heavy/integration/server_test.go, ledger/light/integration/server_test.go, network/interfaces.go, network/nodenetwork/nodekeeper.go, server/internal/heavy/components.go, server/internal/light/components.go, server/internal/virtual/components.go
origin now updates every consensus
remove OriginProvides dependency from JetCoordinator
=> Ins 3213 origin power status

cmd/insolar/create_default_configs.go
=> generator creates default config for bootstrap

configuration/log.go, log/log.go, log/zerolog.go, scripts/insolard/launchnet.sh
NOISSUE: Ticking every second and dumping log ever faster
=> NOISSUE: Ticking every second and dumping log ever faster

configuration/ledger.go
=> NOISSUE: Limit jets to 32.

api/call_wrapper.go, cmd/benchmark/scenario.go, functest/send_money_test.go, logicrunner/builtin/contract/costcenter/costcenter.go
Updated fee size
By testing
Fee size has increased from 0.001 to 0.1 XNS
=> WLT-1026: update fee size

bootstrap/config.go, cmd/insolar/create_default_configs.go, cmd/insolar/main.go
=> Noissue configs for devops

network/hostnetwork/future/handler.go, network/hostnetwork/pool/pool.go
remove unnecessary network debug logs
=> remove debug logs

Makefile, functest/bloat_test.go, functest/logicrunner_test.go
move bloat tests to a separate tag.
=> INS-3465: move bloat tests to a separate tag.

functest/deposit_transfer_test.go, logicrunner/outgoingsender.go, logicrunner/outgoingsender_test.go
=> INS-3476: refactor OutgoingSender

api/healthcheck.go, insolar/network.go, network/servicenetwork/status.go
remove healthchecker from network
=> Noissue remove healthchecker

network/transport/transport_test.go
Fixed a test. 5555 port was dialled in a previous test.
Removed test case
Run test.
=> INS-3338: 5555 port was dialled in a previous test

cmd/insgorund/insgorund.go, log/log.go, server/internal/heavy/server.go, server/internal/light/server.go, server/internal/virtual/server.go
INS-3483: logger waits till metrics will be initialized
=> INS-3483: logger waits till metrics will be initialized

scripts/monitor/grafana/dashboards/light-nodes.json
=> NOISSUE: Update metrics.

log/log_test.go, log/zerolog.go
=> NOISSUE: No logs for the dead node.

Makefile
=> NOISSUE: Fix makefile functest.

ledger/light/executor/metrics.go, ledger/light/executor/pulsemanager.go, scripts/monitor/grafana/dashboards/light-nodes.json
=> NOISSUE: Change dashboards.

scripts/monitor/grafana/dashboards/bus.json
Fix legends on messagebus dashboard
=> INS-3415: fix legends on messagebus dashboard

network/gateway/wait_majority_test.go, network/gateway/wait_minroles_test.go
Fixed races in TestWaitMinroles_MinrolesHappenedInETA(), TestWaitMajority_MajorityHappenedInETA()
Moved Set() in minimocks.
Run tests.
Fixed test minimock races.
=> INS-3420: And INS-3421 minimock test races.

ledger/light/executor/metrics.go, ledger/light/executor/pulsemanager.go, scripts/monitor/grafana/dashboards/bus.json
=> Noissue light metrics

insolar/record/helperproto.go, logicrunner/artifacts/artifacts.go, logicrunner/artifacts/client.go, logicrunner/artifacts/client_mock.go, logicrunner/artifacts/client_proc.go, logicrunner/artifacts/client_test.go, logicrunner/common/serialize.go, logicrunner/goplugin/goplugintestutils/utils.go
Wrote tests for Artifacts.Client, fixed couple of bugs
=> INS-3433: artifacts.client tests

insolar/payload/error_code.go, ledger/light/integration/requests_test.go, ledger/light/proc/set_result.go
=> INS-3494 add checking for open outgoings while closing incoming

cmd/benchmark/main.go, cmd/benchmark/scenario.go, contractrequester/contractrequester.go, functest/get_balance_test.go, logicrunner/builtin/contract/costcenter/costcenter.go, logicrunner/builtin/contract/member/member.go, logicrunner/builtin/contract/wallet/wallet.go, logicrunner/builtin/proxy/wallet/wallet.go
=> Ins 3490 fix bank tests

log/zerolog.go
INS-3494: Remove hooks from logger
=> INS-3494: Remove hooks from logger

ledger/light/handle/get_request.go, ledger/light/handle/get_request_test.go, ledger/light/proc/get_request.go, ledger/light/proc/get_request_test.go
=>  adding checking for jet when virtuals calls for a request

ledger/heavy/executor/db_rollback_test.go, ledger/object/index_db.go, ledger/object/index_db_test.go
=> INS-3499: fix forPulse in index DB

ledger/heavy/executor/db_rollback.go, ledger/heavy/executor/initial_state_keeper.go, ledger/object/index_db.go
=> debug logs -> info logs

api/call_test.go
=> INS-3352: remove suite from TestTimeout api

cmd/insolar/README.md, cmd/insolar/main.go
What I did:
- added to insolar utility admin url, and wrote readme
=> added to insolar utility admin url, and wrote readme

insolar/gen/reference.go, logicrunner/requestsfetcher.go, logicrunner/requestsfetcher_test.go
=> INS-3497: limit max abandoned requests fetched in requestsfetcher

cmd/benchmark/main.go
Update benchmark to use custom dir to members
Run tests
=> INS-3510: update bench to provide dir to member

contractrequester/contractrequester.go, insolar/bus/bus.go, scripts/cmd/README.md, scripts/cmd/log_stat/log_stat.go, scripts/cmd/logstat/logstat.go
=> INS-3500: Add log statistics tool.

metrics/metrics_test.go
fetch until all expected metrics in exporter output
=> INS-3532: fix metrics test

api/call_wrapper.go, functest/send_money_test.go, logicrunner/builtin/contract/member/member.go
What I did:
- fix returned error message 
- fix error wrapper
=> Fix return error

.mergify.yml
=> new checks for auto-merge

configuration/log.go, log/zerolog.go
=> remove poller

logicrunner/builtin/contract/deposit/deposit.go
What I did:
- fix transfer bug
=> WLT-1067: fix transfer bug

metrics/network.go, network/hostnetwork/future/future.go, scripts/monitor/grafana/dashboards/ins-network.json
=> INS-3431: make futures irate instead of gauge

insolar/bus/bus.go, insolar/bus/metrics.go, scripts/monitor/grafana/dashboards/ins-bus.json
=> NOISSUE: Add bus error metric.

ledger/heavy/executor/heavyreplicator.go
=> NOISSUE: Fix heavy abandon metric.

scripts/monitor/grafana/dashboards/ins-bus.json, scripts/monitor/grafana/dashboards/ins-consensus.json, scripts/monitor/grafana/dashboards/ins-flow-dispatcher.json, scripts/monitor/grafana/dashboards/ins-flow-procedures.json, scripts/monitor/grafana/dashboards/ins-heavy-node.json, scripts/monitor/grafana/dashboards/ins-light-nodes.json, scripts/monitor/grafana/dashboards/ins-logging.json, scripts/monitor/grafana/dashboards/ins-network.json, scripts/monitor/grafana/dashboards/ins-pulsar.json, scripts/monitor/grafana/dashboards/ins-virtual.json
Another metric dashboards update
=> INS-2448: another metrics update

api/sdk/sdk.go, cmd/apirequester/request.go, cmd/benchmark/README.md, cmd/benchmark/create_members_scenario.go, cmd/benchmark/main.go, cmd/benchmark/scenario.go, cmd/benchmark/transfer_different_members_scenario.go
Create benchmark for member create
Edited scenario interface; Created new scenario; edited benchmark main.go; added new flag
Launch benchmark with flag -z
Create benchmark for member create
=> WLT-515: benchmark for create member

bootstrap/bootstrap.go, cmd/insolar/main.go, functest/deposit_migration_test.go, functest/test_utils.go, logicrunner/builtin/contract/migrationadmin/migrationadmin.go, logicrunner/builtin/foundation/helpers.go
What I did:
- added ethereum address verifier
- added to insolar utility fake address generator
=> Wlt-1072: added eth address verifier

insolar/bus/bus.go
Close spans with on defer -> little code restructure for that
=> INS-3533: close spans on defer

network/consensus/adapters/config.go, network/consensus/adapters/feeder.go, network/consensus/gcpv2/api/injects.go, network/consensus/gcpv2/phasebundle/ph3ctl/phase3.go, network/consensus/tests/local_config_test.go, pulsar/pulsar.go
fix consensus timings for ephemeral mode
=> INS-3555: consensus timings

scripts/monitor/grafana/dashboards/ins-virtual.json
Updated INS-Virtual dashboard in Grafana
=> INS-2448: Updated virtual dashboard

cmd/benchmark/create_members_scenario.go, cmd/benchmark/main.go, cmd/benchmark/scenario.go, cmd/benchmark/transfer_different_members_scenario.go, insolar/errors.go
Remove "Pending retries" and ErrTooManyPendingRequests error check - its no longer used in system.
Run benchmark.
=> NOISSUE: remove pen retry

insolar/node/node_db.go, insolar/node/node_db_test.go, ledger/heavy/executor/db_rollback.go, ledger/heavy/executor/db_rollback_test.go, ledger/heavy/integration/server_test.go, ledger/light/executor/pulsemanager.go, server/internal/heavy/components.go
=> INS-3548 adding truncate head

insolar/pulse/start_pulse.go, insolar/pulse/start_pulse_test.go
added mutex for startpulse to avoid race
run test
=> INS-3166: start pulse with mutext

ledger/light/proc/get_request.go
=> INS-3551: Fix GetRequest procedure.

logicrunner/builtin/contract/account/account.go, logicrunner/builtin/contract/costcenter/costcenter.go, logicrunner/builtin/contract/deposit/deposit.go, logicrunner/builtin/contract/migrationdaemon/migrationdaemon.go
=> INS-3436: some contracts cleanup

functest/new_api_test.go
=> INS-3561: fix tests conflict

scripts/monitor/grafana/dashboards/ins-network.json
NOISSUE: beautify network dashboard
=> NOISSUE: beautify network dashboard

Makefile, configuration/ledger.go, ledger/light/handle/hot_objects.go, ledger/light/integration/server_test.go, ledger/light/proc/hot_objects.go, ledger/light/proc/hot_objects_test.go, ledger/light/proc/proc.go, server/internal/light/components.go
=> INS-3549 add limiter for abandoned notifications

ledger/light/executor/filaments.go, ledger/light/executor/metrics.go, scripts/monitor/grafana/dashboards/ins-light-nodes.json
=> INS-3569: Add filament metrics.

api/functest_contract.go, contractrequester/contractrequester.go, functest/test_utils.go, logicrunner/goplugin/goplugintestutils/utils.go, logicrunner/handle_init.go
=> INS-2682: Caller is mutually exclusive with APINode, not Reason

bootstrap/bootstrap.go, ci/local-dev/manifests/ks/components/insolar/launch.sh, insolar/genesis.go, insolar/genesisrefs/refs.go, insolar/genesisrefs/refs_test.go, ledger/genesis/genesis.go, scripts/insolard/launchnet.sh
Updated distribution params
By testing
=> WLT-1033: added entity generation on genesis

network/gateway/base.go, network/gateway/complete.go, network/gateway/wait_majority.go, network/gateway/wait_minroles.go, network/gateway/wait_pulsar.go, network/rules/rules.go, network/rules/rules_test.go
Improved logs for majority and minRole fail.
Added nodes hosts to logs.
Run tests.
Improved logs for majority and minRole fail.
=> INS-3552: Added nodes to majority and minRole fail.

scripts/monitor/grafana/dashboards/ins-network.json
=> INS-3431: consensus packets

configuration/log.go
=> Turn off buffer's size

network/consensus/adapters/roundstrategy.go, network/consensus/gcpv2/api/configs.go, network/consensus/gcpv2/core/realm_full.go, network/consensus/gcpv2/core/round_controller.go, network/consensus/tests/consensus_test.go
logging consensus timings every round
=> INS-3555 - log consensus timings

network/consensus/adapters/handlers.go, network/consensus/common/warning/warning.go, network/consensus/gcpv2/core/errors/packet_errors.go, network/consensus/gcpv2/core/realm_full.go, network/consensus/gcpv2/core/realm_prep.go
=> NOISSUE: consensus errors

functest/deposit_transfer_test.go
fixed bug https://insolar.atlassian.net/browse/INS-3572
By tests
=> INS-3572: fix bug

logicrunner/common/sync.go, logicrunner/executionbroker.go, logicrunner/executionbroker_test.go
Limit concurrent immutable execution queue
=> INS-3571: limit concurrent immutable execution

insolar/bus/bus.go, insolar/bus/metrics.go
=> NOISSUE: Add reply stats.

insolar/bus/bus.go, insolar/bus/metrics.go
=> NOISSUE: Add reply taqs.

api/call_wrapper.go
log message for easy api error grep
=> log api error

cmd/insolard/instrument_gops.go, cmd/insolard/main.go
* fix usage print on start
* cleanup insolard launch code (remove not needed abstractions and types)
=> INS-3574: cleanup insolard launch code, fix usage print on start

ledger/light/proc/set_request.go
Dump request body on registration.
=> NOISSUE: Dump request body on registration.

insolar/record_test.go, reference/encoder.go, reference/local.go
Change ID string method to use base64.
=> NOISSUE: Change ID string method to use base64.

logicrunner/executionbroker.go
obsoletes https://github.com/insolar/insolar/pull/2829
=> NOISSUE: remove added by mistake debug log

insolar/payload/error_code.go, ledger/light/proc/set_request.go, ledger/light/proc/set_request_test.go
=> Ins 3597 filament limit

insolar/payload/error_code.go, ledger/light/proc/set_request.go, ledger/light/proc/set_request_test.go
=> Revert "Ins 3597 filament limit"

network/consensus/adapters/context.go
=> Noissue critical logger consensus

bootstrap/bootstrap.go, bootstrap/config.go, bootstrap/contracts/contracts.go, insolar/genesis.go, ledger/genesis/genesis.go, logicrunner/builtin/contract/account/account.go, logicrunner/builtin/contract/costcenter/costcenter.go, logicrunner/builtin/contract/costcenter/costcenter.wrapper.go, logicrunner/builtin/proxy/costcenter/costcenter.go, scripts/insolard/bootstrap_template.yaml
I added a fee to bootstrap.yaml; make don't send fee if it is equal 0
Changed bootstap_template.yaml and bootstrap config. Added fee parameter to costcenter. Changed Transfer logic.
Remove fee member from transfer benchmark; launch transfer benchmark; got balance mismatch; set fee to zero; launch benchmark again; got success
Added a fee to bootstrap.yaml; make don't send fee if it is equal 0
=> WLT-1126: add fee to bootstrap.yaml; dont send fee if it is equal 0

configuration/ledger.go, ledger/light/executor/cleaner.go, ledger/light/executor/cleaner_test.go, ledger/light/executor/filament_cleaner_mock.go, ledger/light/executor/filaments.go, ledger/light/integration/server_test.go, server/internal/light/components.go
=> INS-3603 filament limiter

api/admincontract.go, api/call_wrapper.go, api/contract.go, api/info.go, api/instrumenter/instrumenter.go, api/instrumenter/metrics.go, api/node_cert.go, api/seed.go, scripts/monitor/grafana/dashboards/ins-api.json
Also refactored logging/tracing/spanning; created separate component to orchestrate span begin/end and metrics push
=> INS-3594: added metrics for API

scripts/monitor/grafana/dashboards/ins-network.json, scripts/monitor/grafana/dashboards/ins-virtual.json
=> NO_ISSUE_fix_metrics - remove subtractions

api/call_wrapper.go, api/instrumenter/instrumenter.go, api/seed.go, api/seedmanager/seedgenerator.go
Changed code and message error
https://insolar.atlassian.net/browse/INS-3593
=> INS-3593: update error message and code

scripts/monitor/grafana/dashboards/ins-api.json
=> INS-3594: fix variables for api metrics dashboard

testutils/launchnet/launchnet.go
=> show killall output on error

ledger/light/executor/request_checker.go, ledger/light/executor/request_checker_test.go
Check immutable request reason appropriately.
=> Check immutable request reason appropriately.

ledger/light/executor/request_checker.go
=> NOISSUE: Simplify check.

functest/deposit_migration_test.go, logicrunner/builtin/contract/deposit/deposit.go, logicrunner/builtin/contract/migrationdaemon/migrationdaemon.go, logicrunner/builtin/proxy/deposit/deposit.go
fix bug with double transfer 
delete annotation from getUnHold in Deposit Contract and move check status deposit from migrationDaemon to Deposit
start new func  test
depost , migrationdaemon - contract
=> WLT-1123: fix bug

ledger/light/proc/set_result.go, ledger/light/proc/set_result_test.go
added check that closing request is mutable, before check in filaments
=> NOISSUE: added check in set result

cmd/keeperd/config.go, cmd/keeperd/json.go, cmd/keeperd/keeper.go, cmd/keeperd/main.go, scripts/insolard/keeper_template.yaml
Created `keeperd` daemon.
Daemon reads PromQL queries from config, constantly queries Prometheus, and checks if each metric equals 1 and that last metric point is not older than a certain limit.
=> INS-3617: Implemented keeperd

keystore/internal/privatekey/loader.go, platformpolicy/keys.go
changed the export-import of private key to support different type of keys
save compatibility with old configs
don't show private keys in error messages
PKCS#8
tests
=> NOISSUE: PKSC8 private key export import

scripts/monitor/grafana/dashboards/ins-general.json
save json for prod grafana metrics
=> NO_ISSUE add json for grafana prod metrics bord

scripts/monitor/grafana/dashboards/ins-go-metrics.json
add grafana board (json) for go metrics
=> NO_ISSUE add grafana board for go metrics

Makefile
Added keeperd build to makefile
=> NOISSUE: added keeperd to makefile

ledger/light/proc/set_result_test.go
before investigation would be closed
=> INS-3612 race in minimock. Try using Inspect instead of Set

log/critlog/backpressure_buffer.go, log/critlog/backpressure_buffer_test.go, log/critlog/buffer_slow_test.go
=> Slow test fix

README.md, docs/requirements.txt
- Added the Golang version to readme
- Added a forgotten dependency to docs
=> Add Go version to readme and dependency to docs

insolar/record_test.go, reference/local.go
Reverted Local.String() to base58 encoding
=> HOTFIX: return id stringification to base58

ledger/light/proc/hot_objects.go, ledger/light/proc/metrics.go
=> INS-3632: Add oldest abandoned request metric

ledger/heavy/handler/handler.go, ledger/heavy/proc/search_index.go, ledger/heavy/proc/search_index_test.go
=> INS-3630 not return an error, when there are no pulses

cmd/backupmanager/backupmanager_test.go
Note: no idea what BIN_DIR was used for.
=> NOISSUE: always rebuild backupmanager during slow_tests

functest/pressure_test.go
pass one coin in parallel, make sure balance settles
=> add test that passes a coin from account to another in parallel

functest/pressure_test.go
=> test was not refreshing balance from ledger on retries

log/critlog/backpressure_buffer_test.go, log/logadapter/log_cfg.go
* It was turned off by default
=> NOISSUE: return logger caller value

logicrunner/builtin/contract/member/member.go
=> NOISSUE: update err msg if recipient not exist

cmd/benchmark/main.go
wait 2 ticks for balance changes
=> INS-3641: wait until balance mismatches

Makefile, cmd/heavy-badger/fix.go, cmd/heavy-badger/main.go
* add badger binary v1.6 compilation
* badger heavy tool initial version
=> NOISSUE: add badger tool for heavy

cmd/benchmark/README.md, cmd/benchmark/main.go, cmd/benchmark/migration_scenario.go, cmd/benchmark/wallet_to_wallet_transfer_scenario.go
We can run transfer scenario on members, that was created and migrate by migration scenario.
Write to file fee member and migration admin in both scenarios.
Run migration scenario with -s, than transfer scenario with -m
=> INS-3566: fee member and migration admin in every file

configuration/ledger.go, insolar/store/badger.go, server/internal/heavy/components.go
It's nice to have ability to configure Badger Values GC and not run it just on database open.
=> NOISSUE: make badger GC configurable

ledger/light/executor/filaments.go, ledger/light/executor/filaments_test.go
=> NOISSUE: Fix creation deduplication.

network/pulsenetwork/distributor.go
Fix pulsar TraceID already set
by creating a new context with `pulse_*`  traceID
=> INS-3545: fix pulsar TraceID already set

cmd/backupmanager/backupmanager.go
=> INS-3624: Run GC during `backupmanager merge`

cmd/backupmanager/README.md
=> INS-3411: backupmanager - fix README

cmd/benchmark/README.md, cmd/benchmark/main.go, cmd/benchmark/wallet_to_wallet_two_sides_scenario.go
=> INS-3641: new scenario

docs/source/index.rst, docs/source/migration-test.rst
Added migration test instruction.
=> [DOC] Add migration test instruction

contractrequester/contractrequester.go, logicrunner/result_matcher.go
* also drop and notify about requests with empty Reason
=> NOISSUE: add more logging information for unwanted results

scripts/build/install_build_tools.sh
=> NOISSUE: try to fix codegen

ledger/heavy/exporter/record_exporter_server.go, ledger/heavy/exporter/record_exporter_server_test.go, server/internal/heavy/components.go
=> remove limiter from exporter

Makefile, cmd/heavy-badger/main.go, scripts/build/realpath.go
* fix badger binary build on MacOS 
* fix heavy tool `dir` flag name
=> fix badger binary build on MacOS 

insolar/record.go, logicrunner/builtin/contract/deposit/deposit.go, logicrunner/builtin/contract/member/member.go, logicrunner/builtin/contract/migrationadmin/migrationadmin.go, logicrunner/builtin/contract/rootdomain/rootdomain.go, logicrunner/builtin/contract/wallet/wallet.go, logicrunner/builtin/proxy/account/account.go, logicrunner/builtin/proxy/costcenter/costcenter.go, logicrunner/builtin/proxy/deposit/deposit.go, logicrunner/builtin/proxy/helloworld/helloworld.go, logicrunner/builtin/proxy/member/member.go, logicrunner/builtin/proxy/migrationadmin/migrationadmin.go, logicrunner/builtin/proxy/migrationdaemon/migrationdaemon.go, logicrunner/builtin/proxy/migrationshard/migrationshard.go, logicrunner/builtin/proxy/nodedomain/nodedomain.go, logicrunner/builtin/proxy/noderecord/noderecord.go, logicrunner/builtin/proxy/pkshard/pkshard.go, logicrunner/builtin/proxy/rootdomain/rootdomain.go, logicrunner/builtin/proxy/wallet/wallet.go, logicrunner/preprocessor/templates/proxy.go.tpl
Add NewObjectReferenceFromBase58 func and use it in contract
Run tests
=> INS-3652: add new obj record func and use it in contract

ledger/light/executor/cleaner.go, ledger/light/executor/cleaner_test.go, ledger/light/executor/filament_cleaner_mock.go, ledger/light/executor/filaments.go
Remove all non-existent objects from cache.
=> INS-3649: Remove all non-existent objects from cache.

api/call_wrapper.go, insolar/flow/dispatcher/dispatcher.go, insolar/payload/message.go, ledger/light/handle/init.go, ledger/light/proc/get_pendings.go, ledger/light/proc/get_pendings_test.go, ledger/light/proc/send_object.go
Trim some logs and pass ErrNoPendings as a normal reply.
=> Ins 3515 trim logs

ledger/light/executor/cleaner.go, ledger/light/executor/cleaner_test.go, ledger/light/executor/filament_cleaner_mock.go, ledger/light/executor/filaments.go
=> Revert "INS-3649: Remove all non-existent objects from cache."

scripts/monitor/grafana/dashboards/ins-go-metrics.json, scripts/monitor/grafana/dashboards/ins-light-nodes.json
* insolar light metrics
* insolar go metrics
=> NOISSUE: add more metrics

ledger/light/executor/filaments.go
=> NOISSUE: Add deduplication logs.

logicrunner/handle_calls.go
=>  NOISSUE: let not self scope ref run: part 1

ledger/light/integration/requests_test.go
=> NOISSUE: Fix creation integration test.

functest/send_money_test.go, insolar/record.go, logicrunner/handle_calls.go
=> Hotfix fix self scope refs part 2

ledger/light/proc/set_request.go
=> NOISSUE: add logging of request in SetRequest

scripts/monitor/grafana/dashboards/ins-general.json
=> NOISSUE: update general dashboard

scripts/monitor/grafana/dashboards/ins-general.json
=> NOISSUE: fix legend

scripts/monitor/grafana/dashboards/ins-general.json
=> NOISSUE: another dashboard update

logicrunner/handle_calls.go, logicrunner/outgoingsender.go, logicrunner/procs.go, logicrunner/requestsexecutor.go, logicrunner/rpc_methods.go
added more logs, as a step to be able to better parse logs
=> improve logging for better logic parsing

instrumentation/inslogger/inslogger_ext_test.go, log/caller_test.go
=> Avoid test sensitivity to env settings

scripts/log-parser.py
log parser, made by @bigbes, I've added couple of logs format
=> loparser for debug issues

ledger/light/executor/cleaner.go, ledger/light/executor/cleaner_test.go, ledger/light/executor/filament_cleaner_mock.go, ledger/light/executor/filaments.go
This reverts commit d6f9273e22a5fc86a4430340c8f6dce406229f13.
=> Revert "Revert "INS-3649: Remove all non-existent objects from cache.""

scripts/monitor/grafana/dashboards/ins-general.json
Another INS-General board update
=> NOISSUE: another board update

ci/local-dev/manifests/ks/components/insolar/insolard_config.libsonnet, ci/local-dev/manifests/ks/components/pulsar/pulsar_config.libsonnet, ci/local-dev/manifests/ks/components/pulsar/pulsar_statefull_set.libsonnet, configuration/testdata/default.yml, docker/testnet-node/insolard.yaml.default, scripts/insolard/pulsar_template.yaml
- remove obsolete config fileds: versionmanager, pulsar storage
=> NOISSUE: remove obsolete config fileds

cmd/backupmanager/backupmanager.go
=> profiler for backup manager

docs/source/migration-test.rst
=> [DOC] Fix typo

ledger/light/executor/filaments.go
=> fix data-race in filaments cache

ledger/light/handle/init.go
added error reply for GetFilament
=> INS-3670: reply with error in getfilament handling

cmd/insolar/README.md, cmd/insolar/main.go, logicrunner/builtin/contract/migrationadmin/migrationadmin.go, logicrunner/builtin/proxy/migrationadmin/migrationadmin.go
What I did:
- Added PublicKey automatic substitution in the insolar utility
- fixed readme in the insolar utility
- added filter for 10 shards during loading migration addresses
=> Wlt-1020: filter for 10 shards

ledger/heavy/proc/search_index.go, ledger/light/executor/filaments.go
=> additional logs for search_index + fixes for deduplication

contractrequester/contractrequester.go, logicrunner/requestsexecutor.go, logicrunner/result_matcher.go
improved logging around unwanted results
=> NOISSUE: fix logging for unwanted results

ledger/light/executor/filaments.go, ledger/light/executor/filaments_test.go
=> NOISSUE: Fix deduplication from heavy.

logicrunner/artifacts/client.go, logicrunner/artifacts/instrument.go
* combine everything in one place: spans, timings, logs
* don't log "error", use "debug", so cases are recovered
* split RegisterRequest into two: one for incoming, other for outgoing
=> cleanup artifacts.Client instrumentation

Makefile
=> NOISSUE: Remove slow tag from coverage.

api/sdk/sdk.go, cmd/benchmark/README.md, cmd/benchmark/create_member_scenario.go, cmd/benchmark/deposit_transfer_scenario.go, cmd/benchmark/main.go, cmd/benchmark/migration_scenario.go, cmd/benchmark/scenario.go, cmd/benchmark/wallet_to_wallet_transfer_scenario.go, cmd/benchmark/wallet_to_wallet_two_sides_scenario.go
Add new benchmark scenario - deposit transfer
Add new benchmark scenario - deposit transfer
Launch
Add new benchmark scenario - deposit transfer
=> Ins 3376 deposit transfer scenario

cmd/benchmark/README.md, cmd/benchmark/wallet_to_wallet_two_sides_scenario.go
=> NOISSUE:update transfer two sides

scripts/monitor/grafana/dashboards/ins-general.json
=> NOISSUE: update boards

cmd/backupmanager/backupmanager_test.go
=> Fix TestNoMergeToEmptyDb

ledger/light/proc/set_result_test.go
fixed bug on NewSenderMock initialisation 
=> INS-3612 race fixed

ledger/genesis/genesis.go
Updated dates
Changed the constants
=> WLT-1192: update the dates for deposits

cmd/heavy-badger/scan.go
fix value fetch if histogram not created
=> NOISSUE: fix value fetch if histogram not created

Gopkg.lock
=> dep ensure

Gopkg.lock, cmd/backupmanager/README.md, cmd/backupmanager/backupmanager.go, cmd/backupmanager/daemon.go
Implement backupmanager daemon. Tests are implemented in https://github.com/insolar/insolar-jepsen/pull/75
=> INS-3679: backupmanager daemon

cmd/backupmanager/backupmanager.go
Add --run-gc and  --run-compact flags; disable compaction by default.
=> INS-3679: more backupmanager flags

cmd/keeperd/config.go, cmd/keeperd/keeper.go, cmd/keeperd/main.go, cmd/keeperd/metrics.go
=> NOISSUE: add metrics to keeperd

reference/decoder_test.go, reference/encoder.go, reference/encoder_test.go
* Updated schema name
* Added separate FormatSchema and EncodingSchema flags processing
=> WLT-1243: new reference schema name

bootstrap/contracts/contracts.go, ledger/genesis/genesis.go, logicrunner/builtin/contract/deposit/deposit.go, logicrunner/builtin/proxy/deposit/deposit.go
What I did:
- fix member.getBalance to doc
=> 3653: fix member.getBalance to doc

insolar/pulse/db.go, insolar/store/db.go, insolar/store/db_gen_mock.go, ledger/heavy/executor/db_rollback_test.go
TestDBRollback_HappyPath was changed a little because it doesn't rely on a mocked method anymore. Hopefully I didn't do anything wrong in that test.
=> INS-3683: get rid of unecessary rwlock

functest/migration_shard_test.go, logicrunner/builtin/contract/migrationadmin/migrationadmin.go
fix test TestGetFreeAddressCount
calculate shard in test( like it's done in smart contract ), and ask range of shards, which include this shard
=> Ins 3692 fix test get free address count changes after migration

network/gateway/base.go, network/gateway/utils.go, network/gateway/watchers.go, network/gateway/watchers_test.go, network/interfaces.go, network/servicenetwork/servicenetwork.go, testutils/network/gateway_mock.go
=> INS-3669 INS-2703: pulse watchdog data race

functest/migration_shard_test.go
index in test might be less then zero. Just use shard index
=> INS-3692: fix incorrect index

cmd/backupmanager/backupmanager.go, insolar/pulse/db.go, insolar/store/db.go, insolar/store/db_gen_mock.go, ledger/heavy/executor/db_rollback_test.go
=> INS-3713 remove backend from store.DB interface

ledger/heavy/executor/finalize_pulse.go
Tail recursion is not optimized in go, better avoid it.
=> INS-3718: get rid of tail recursion which is not optimized in Go

scripts/_logger/main.go, scripts/insolard/launchnet.sh
* fix reopening with enabled buffer
* concurrent safe stop of work
=> NOISSUE: fix logger tool

configuration/ledger.go, insolar/store/badger.go, ledger/heavy/executor/finalize_pulse.go, ledger/heavy/executor/finalize_pulse_test.go, ledger/heavy/executor/heavyreplicator.go, ledger/heavy/handler/handler.go, ledger/heavy/integration/server_test.go, server/internal/heavy/components.go
1. Drop old logic with background running of badger's value GC
2. Run GC only after pulse finalization with given( in config ) frequency
=> Ins 3735 new backup scheme

network/transport/fake.go
fix data race by copying buffer slice in fake transport
=> INS-3707: fix integration test data race

application/functest/fund_test.go, application/functest/test_utils.go, application/genesis/genesis.go, application/genesisrefs/refs.go, application/testutils/launchnet/launchnet.go
What I did:
- found why they got an error on methods `member.get` and `member.getBalance`
=> Wlt 1260 fix fund bugs

scripts/insolard/launchnet.sh
=> WLT-1310: update foundation contracts params from xns

insolar/jet/dbstore_test.go, pulse/pulse_number.go
=> NOISSUE: update pulse constants

Makefile
Added `make applictaion-git-config` that changes the remote repo URL from HTTPS to SSH in the `application` submodule.
=> NOISSUE: added `make application-git-config`

network/gateway/base.go
=> INS-3707: fix TestComponents

ledger/light/handle/get_pendings_test.go
=> INS-3693 fixed data race in tests

ledger/heavy/exporter/record_exporter_server_test.go
=> INS-3746 added observer rpc test cases

insolar/record.go
=> ins ref check for record

application/builtin/contract/deposit/deposit.go, application/builtin/contract/deposit/deposit.wrapper.go, application/builtin/contract/migrationdaemon/migrationdaemon.go, application/builtin/proxy/deposit/deposit.go
=> INS-3775: Add toMember ref to TransferToDeposit call.

network/consensus/adapters/upstream.go, network/gateway/complete.go
fix pulse append and read race
=> INS-3796: fix pulse append and read race

scripts/build/ls-tools.go, scripts/build/realpath.go
=> hide tools sources from standard go tools

ledger/heavy/executor/finalize_pulse.go, ledger/heavy/executor/finalize_pulse_test.go
Its fix for INS-3827
fix TestBadgerGCRunInfo stucking
=> fix TestBadgerGCRunInfo stucking

insolar/utils/utils.go, instrumentation/instracer/tracer.go, network/consensus/adapters/tests/init_test.go, network/pulsenetwork/distributor.go, network/tests/suite_test.go, network/utils.go, scripts/cmd/logstat/logstat.go, server/internal/heavy/server.go, server/internal/light/server.go, server/internal/virtual/server.go, virtual/integration/main_test.go
fixed trace propagation for custom traces
=> INS-3761: fix traceID propagation

ledger/heavy/executor/finalize_pulse.go, ledger/heavy/executor/metrics.go
Add gc and backup time metrics to heavy
=> INS-3437: add metrics for badger GC and backup

Makefile
=> NOISSUE: temporary disable goproxy until goproxy.insolar.io will be up

application/builtin/contract/deposit/deposit.go
=> INS-3841: Pass correct migration admin.

application/functest/activatedaemon_test.go, application/functest/deposit_migration_test.go, application/functest/deposit_transfer_test.go, application/functest/fund_test.go, application/functest/get_balance_test.go, application/functest/get_node_ref_test.go, application/functest/member_create_test.go, application/functest/member_get_test.go, application/functest/member_migration_create_test.go, application/functest/migration_shard_test.go, application/functest/new_api_test.go, application/functest/register_node_test.go, application/functest/send_money_test.go, application/functest/test_utils.go
=> INS-3572: show real error text in functest

application/functest/deposit_migration_test.go, application/functest/send_money_test.go, application/functest/test_utils.go
=> NOISSUE: fix unchecked requester.error conversions

application/api/sdk/sdk.go
=> NOISSUE: flatten retry code in DoRequest

network/gateway/watchers.go
=> NOISSUE: remove watchdog warn logs

log/test/log_test.go
=> INS-3818: test for logger

application/api/admincontract.go
removed old methods from api whitelist
=> removed old methods from api whitelist

logicrunner/goplugin/goplugintestutils/build_test.go, logicrunner/goplugin/goplugintestutils/utils.go
Added ContractBuilder cleanup when the test finishes
=> INS-3685: ContractBuilder cleanup

application/genesis/genesis.go
=>  WLT-1310: update hold periods

Makefile, cmd/insgorund/insgorund.go, scripts/insolard/launchnet.sh
Fixed tmpdir bloating in functests
Added tmpdir cleanup. Changed SIGABRT to SIGTERM in launchnet to stop daemons gracefully
=> INS-3685: fixed tmpdir bloating in functests

application/api/admincontract.go, application/api/contract.go, cmd/backupmanager/backupmanager.go, cmd/keeperd/main.go, cmd/pulsard/main.go, cmd/testpulsard/main.go, insolar/logger.go, instrumentation/inslogger/inslogger.go, ledger/light/handle/init.go, log/logadapter/builder.go, log/zlogadapter/zerolog_adapter.go, log/zlogadapter/zerolog_adapter_test.go, logicrunner/artifacts/client.go, logicrunner/common/transcript.go, logicrunner/executionbroker.go, logicrunner/outgoingsender.go, logicrunner/request_fetcher.go, network/consensus/adapters/tests/init_test.go, network/tests/suite_test.go, server/internal/heavy/components.go, server/internal/heavy/server.go, server/internal/light/components.go, server/internal/light/server.go, server/internal/virtual/components.go, server/internal/virtual/server.go, virtual/integration/main_test.go
* To avoid duplication of fields in logging output i've removed "..._main" traceid, fixed usage of old contextes/loggers.
* Also added callSite of incoming requests to log and returned roles/nodeids in logs.
* Added inheritance of log fields (in LoggerBuilder implementation)
=> NOISSUE: logging improvements

application/bootstrap/contracts/contracts.go, application/builtin/contract/deposit/deposit.go, application/functest/deposit_migration_test.go
=> Ins 3879 update confirm logic

application/builtin/contract/deposit/deposit.go
=> INS-3879: add confirm flag

application/functest/fund_test.go, application/functest/test_utils.go, application/genesis.go, scripts/insolard/bootstrap_template.yaml
fixed amount in genesis deposits, according to business requirements
by one zero down
=> NOISSUE fixed amount in genesis deposits

application/functest/fund_test.go, application/functest/test_utils.go
=> NOISSUE test const added

ledger/heavy/executor/backuper.go, ledger/heavy/executor/finalize_pulse.go, ledger/heavy/executor/integration/backuper_test.go
1. Add more logging to pusle finalization logic
2. Remove unused code
=> Add more logging to pusle finalization logging

Makefile, go.mod, go.sum
=> insolar build enhancements

Makefile
=> NOISSUE: Makefile refactoring

Makefile
change the make targets naming  
=> NOISSUE: Makefile refactoring. Change the make targets naming

ledger/heavy/executor/backuper.go, ledger/heavy/executor/finalization_keeper.go, ledger/heavy/executor/finalize_pulse.go, ledger/heavy/pulsemanager/pulsemanager.go
This will help to investigate an issue.
=> INS-3891: tydy Heavy logs a little more

.github/mergeable.yml
Allow merging only with approve from @ita-sammann  or @shayenblue
=> NOISSUE: restrict merge

logicrunner/executionbroker.go, logicrunner/executionbroker_test.go
=> INS-3849: fix VM race condition

insolar/store/badger.go, server/internal/heavy/components.go
Add logic of open-and-close-on-start to compact badger in case of non graceful stop
=> and badger open-close-on-start logic

application/builtin/contract/deposit/deposit.go
proper check deposit confirmation
=> proper check deposit confirmation

ledger/heavy/executor/backuper_test.go, ledger/heavy/executor/integration/backuper_test.go
Use tmp dirs in tests instead of patches
=> INS-3921: use tmp dirs for test

scripts/monitor/grafana/dashboards/ins-general.json
=> NOISSUE: updated dashboard

.github/mergeable.yml
Removed @ita-sammann and @shayenblue merge restrictions
=> NOISSUE: disable restrictions

network/consensus/adapters/handlers.go
=> INS-3941: temporary hide pulse number mismatch error

application/api/seedmanager/seedmanager.go, application/api/seedmanager/seedmanager_test.go
=> INS-3530: use monotonic timer in SeedManager

ledger/light/executor/metrics_registry.go
=> INS-3950: lock for metric added

virtual/integration/virtual_test.go
set random rpc port in vm integratiion tests
because for multirun we could not release port
=> Ins 3923 vm integration fix

application/bootstrap/bootstrap.go, application/bootstrap/config.go, application/bootstrap/contracts/contracts.go, application/builtin/contract/costcenter/costcenter.go, application/builtin/contract/costcenter/costcenter.wrapper.go, application/builtin/proxy/costcenter/costcenter.go, application/genesis.go, application/genesis/genesis.go, scripts/insolard/bootstrap_template.yaml
CostCenter uses constant as fee
=> Ins 3644 change fee without bootstrap

application/genesis/discovery_nodes_test.go, insolar/secrets/keys.go, insolar/secrets/keys_test.go, insolar/secrets/testdata/public_only.json, scripts/insolard/launchnet.sh
No bootstrap could work with files which contains only public keys
=> WLT-1356: add support woking with public keys only on boostrap

ledger/heavy/exporter/record_exporter_server.go
=> INS-3961 ignore context cancelled error

docs/source/architecture.rst, docs/source/basics.rst
**- What I did**:
- Introduced some punctuation and capitalization guidelines and started following them.
- Switched from passive to active voice where possible.
- Fixed minor typos.
=> [DOC] writing style hardening

application/functest/fund_test.go, application/functest/test_utils.go, application/genesis.go, application/genesis/genesis.go, application/genesisrefs/refs.go
no deposits for these 5, directly on accounts.
=> INS-3931: we think that it's more correct to have this funds on account

application/api/admincontract.go, application/api/contract.go
added incoming params logging for api contact calls
=> INS-3946: log contract input params

ledger/heavy/executor/jetkeeper.go
=> INS-3948: Change log level to debug.

logicrunner/builtin/foundation/helpers.go
Remove lowercase from TrimPublicKey
=> HOTFIX: fix trim public key

application/api/functest_contract.go, application/builtin/contract/account/account.wrapper.go, application/builtin/contract/costcenter/costcenter.wrapper.go, application/builtin/contract/deposit/deposit.wrapper.go, application/builtin/contract/member/member.wrapper.go, application/builtin/contract/migrationadmin/migrationadmin.wrapper.go, application/builtin/contract/migrationdaemon/migrationdaemon.wrapper.go, application/builtin/contract/migrationshard/migrationshard.wrapper.go, application/builtin/contract/nodedomain/nodedomain.wrapper.go, application/builtin/contract/noderecord/noderecord.wrapper.go, application/builtin/contract/pkshard/pkshard.wrapper.go, application/builtin/contract/rootdomain/rootdomain.wrapper.go, application/builtin/contract/wallet/wallet.wrapper.go, application/cmd/insgocc/insgocc.go, application/functest/bloat_test.go, application/functest/logicrunner_test.go, application/functest/test_utils.go, logicrunner/builtin/builtin.go, logicrunner/common/error.go, logicrunner/goplugin/goplugintestutils/build_test.go, logicrunner/goplugin/goplugintestutils/utils.go, logicrunner/preprocessor/main.go, logicrunner/preprocessor/main_test.go, logicrunner/preprocessor/templates/wrapper.go.tpl
* also make panics in contract execution as user error (store it in DB
as part of response)
=> INS-3655: recover panics in contracts

scripts/monitor/grafana/dashboards/ins-general.json
=> INS-3957: fix observer delta metric

application/api/spec/api-exported.yaml, application/functest/deposit_migration_test.go, application/functest/deposit_transfer_test.go, testutils/core.go
- updated platform API json specification
- fixed functests for platform according to spec
run functests
=> INS-3969: bump json schema for platform API

application/api/availability.go
=> INS-3985: network is not available log message is warning

logicrunner/builtin/foundation/helpers.go, logicrunner/builtin/foundation/helpers_test.go
fixed TrimPublicKey so it accepts already trimmed keys
run tests
=> trimpublickey accepts keys without pem wrapper

manifest.yaml
=> bump insolar-api version

application/api/spec/api-exported.yaml, application/functest/deposit_migration_test.go, application/functest/send_money_test.go, manifest.yaml
Depends on https://github.com/insolar/insolar-api/pull/32
new ref validation
=> INS-3986 ref regexps updated

application/api/availability.go, application/api/availability_test.go
=> INS-3985: update availability test

log/logadapter/output.go
syslog tag changed to name of executing file
=> INS-3797 syslog tag changed to name of executing file

ledger/heavy/exporter/record_exporter_server.go
=> INS-3961 less dirty checking for context cancelling

application/api/admincontract.go, application/api/contract.go
add logging of seed to join logs migrator and platform
=> INS-3935: add logging of seed

application/api/seed.go, application/api/seed_test.go, application/api/seedmanager/seedmanager.go, application/api/validator.go
add tests for GetSeed
update var names (linter)
remove unused requestBody
=> INS-3959: add seed_test, linter fix names

application/cmd/benchmark/deposit_transfer_scenario.go, application/cmd/benchmark/migration_scenario.go
fixed benchmark ethHash params
=> fix benchmark ethHash accodring to spec

application/builtin/contract/migrationadmin/migrationadmin.go
=> INS-4004: don't jump between shards when looking for an address

application/api/spec/api-exported.yaml, testutils/core.go
allow only lowercased incoming ethTxHash to prevent possible errors in platform
=> restrict only lowercase ethTxHash

application/builtin/contract/migrationadmin/migrationadmin.go, application/functest/migration_shard_test.go
so it's harder to empty a shard from outside on purpose
=> INS-4005: use entropy to salt shard picking

application/api/spec/api-exported.yaml, application/api/validator.go, application/functest/test_utils.go
- updated spec with incompatible case
- added validator panic handler
=> INS-4013 update spec

application/api/spec/api-exported.yaml, application/cmd/benchmark/migration_scenario.go, testutils/core.go
- updated spec with proper ethTxHash validation and examples
- fixed ethTxHash generator
=> INS-4014: updated spec and fixed ethTxHash length

manifest.yaml
=> bump API specification version, 1.0.5

application/functest/deposit_migration_test.go, application/functest/test_utils.go
=> INS-3995: new migration test, remove unused param from utils func

.github/mergeable.yml
Added @shayenblue or @ita-sammann approval requirement
=> NOISSUE: restrict merges

application/api/contract_test.go, application/api/main.go, application/api/main_test.go, application/functest/common_test.go, configuration/apirunner.go, server/internal/heavy/components_test.go, server/internal/light/components_test.go, server/internal/virtual/components_test.go
=> openAPI spec file is mandatory

application/genesis/genesis.go
make it clear how we calculated these numbers
=> INS-3143: change vesting params as closes to requirements as possible

testutils/core.go
=> INS-3686 added RandomEthMigrationAddress for autotests

application/api/spec/api-exported.yaml, application/functest/deposit_migration_test.go, application/functest/test_utils.go
updated internal api spec according to 
https://github.com/insolar/insolar-api/pull/39
=> INS-3686: addMigrationAddress spec api validation

ledger/heavy/exporter/errors.go, ledger/heavy/exporter/pulse_exporter_server.go, ledger/heavy/exporter/pulse_exporter_server_test.go, ledger/heavy/exporter/record_exporter_server.go, ledger/heavy/exporter/record_exporter_server_test.go
=> INS-3961: context.Canceled test

application/api/sdk/sdk.go, application/builtin/contract/member/member.go, application/cmd/benchmark/create_member_scenario.go, application/cmd/benchmark/main.go, application/functest/get_balance_test.go, application/functest/send_money_test.go, scripts/insolard/bootstrap_template.yaml
=> INS-3518: set balance to 0

application/functest/fund_test.go, application/genesis/genesis.go
=> INS-4035 unskip fixed tests

application/builtin/contract/deposit/deposit_vesting_test.go
Added test for minimal vesting amount
=> INS-4035: added minimal amount test

insolar/store/badger.go
run openAndClose procedure in badger with Truncate=true
=> INS-4069: run openAndClose procedure in badger with Truncate=true

application/genesis/genesis.go
change unhold date for 2 weeks because we move release for 2 weeks
=> INS-4071 2 week release date change

application/cmd/benchmark/main.go
- simplify createMembers logic
- fixed SIGSEGV if transfer error happened
run jepsens
=> NOISSUE: simplify createMembers logic

application/cmd/benchmark/main.go
Wait for fee transfer before start scenario
Run tests
=> INS-4073: wait for fee in bench

application/functest/fund_test.go
remove 'for range' from tests for speed up
=> remove 'for range' from tests for speed up

.dockerignore, docker/Dockerfile, docker/build.sh
we forgot to change a build in the dockerfile
Changed the build, create the run.sh which passes needed args to build 
=> NOISSUE: refactor dockerfile

scripts/monitor/grafana/dashboards/ins-heavy-node.json, server/internal/heavy/components.go, server/internal/heavy/metrics.go
added metric on opening badger
=> INS-3971 badger start time metric added

application/cmd/insolar/main.go
=> INS-4085 x2 genesis migration addresses

insolar/store/badger.go, ledger/heavy/integration/server_test.go, server/internal/heavy/components.go
added badger logger adapter that wraps badger logs to insolar logger
=> INS-4066: badger logger adapter for insolar logger

ledger/light/integration/abandoned_notification_test.go
Fix race in abandons test (Test_AbandonsMetricValue)
Atomic read for expectAbandoned value instead of standard read.
Run tests integration tests
=> INS-4098: fix race in abandons test

application/api/contract.go, application/api/contract_test.go, application/api/main.go, application/api/requester/config.go, application/api/requester/requester.go, application/api/requester/requester_test.go, application/api/sdk/sdk.go, application/api/seedmanager/seedgenerator.go, application/api/seedmanager/seedmanager.go, application/bootstrap/bootstrap.go, application/cmd/insolar/main.go, application/functest/new_api_test.go, ci/local-dev/manifests/ks/components/insolar/launch.sh, ci/local-dev/manifests/ks/components/pulsar/pulsar_statefull_set.libsonnet, insolar/secrets/keys.go, insolar/secrets/xkeys.go, scripts/insolard/launchnet.sh
=> Test increase seed ttl

scripts/monitor/grafana/dashboards/ins-general.json
=> Update ins-general dashboard

application/testutils/launchnet/launchnet.go
use pkill in functests, print external tools output on error and in verbose mode
=> INS-4074: use pkill in functests

application/bootstrap/bootstrap.go, application/functest/fund_test.go, application/genesis.go, application/genesis/genesis.go, application/genesisrefs/refs.go, application/testutils/launchnet/launchnet.go
change allocations for genesis after the decision of removing funds and make allocation period shorter
=> INS-4095 new allocation after removing fund

manifest.yaml
=> NOISSUE: update api version in manifest

application/builtin/contract/costcenter/costcenter.go, application/cmd/benchmark/main.go, application/functest/send_money_test.go
=> WLT-1480: fix fee

logicrunner/builtin/foundation/helpers.go, logicrunner/builtin/foundation/helpers_test.go
- fixed ybit calculation
- fixed base64 encoding
- TrimPublicKey removed
=> INS-4129 public key calc fixes

docs/source/index.rst, docs/source/landing-page.html
Added a better landing page to the documentation.
=> [DOC] Add the landing page to docs

insolar/jet/dbstore.go, insolar/node/node_db.go, insolar/pulse/db.go, ledger/drop/db.go, ledger/heavy/executor/backuper.go, ledger/heavy/executor/jetkeeper.go, ledger/object/index_db.go, ledger/object/record_db.go
Fix misleadings in comments for methods TruncateHead in all DBs
=> INS-4139: fix misleadings in comments

ledger/drop/db.go, ledger/drop/db_test.go, ledger/drop/drop_cmp_test.go, migration/0007_drops.sql, server/internal/heavy/components.go
=> INS-4113: drop storage on postgres

.github/workflows/pr-func.yaml, .github/workflows/run-tests.yaml, tests/common/common.go
Add GitHub Actions Integration.
=> Add GitHub Actions Integration

.github/workflows/tag.yaml
Fixed tagging for docker images for dockerhub
=> fix dockerhub image upload

docs/source/index.rst, docs/source/migration-test.rst, docs/source/swap.rst
Added swap instructions and links to API reference.
=> [DOC] Swap instructions and links to API reference

.github/workflows/pr-func.yaml, .github/workflows/tag.yaml
Simplified dockerhub upload part of github actions workflow
=> dockerhub-image upload

docs/source/architecture.rst, docs/source/basics.rst, docs/source/exchanges.rst, docs/source/index.rst, docs/source/integration.rst, docs/source/migration-test.rst, docs/source/requester.rst, docs/source/swap.rst
=> [DOC] Add section for exchanges

docs/source/exchanges.rst, docs/source/index.rst
Mentioned on the landing page that wallet devs should read the same API docs.
=> Landing page for wallet devs

cmd/insolard/main.go, scripts/insolard/launchnet.sh, server/internal/heavy/components.go, server/internal/heavy/components_test.go, server/internal/heavy/server.go, server/server.go
=> INS-4154: --genesis-only flag

.github/workflows/pr-func.yaml
Changed checkout path for func tests
=> remove-custom-checkout-path-in-func

.github/workflows/pr-func-badger.yaml, .github/workflows/pr-func-postgresql.yaml
=> remove all path-related customizations

.github/mergeable.yml
=> edit approvals list

application/api/main.go, application/api/requester/config.go, application/api/requester/requester.go
Goland has corrupted them during the last license update
=> NOISSUE: update crypto import

insolar/jet/postgres_dbstore.go, ledger/heavy/executor/finalize_pulse.go
1) Don't write an "error" that happens on regular basis.
2) Quick fix of nil pointer dereference (will be refactored properly later)
=> NOISSUE: various fixes after Badger + PostgreSQL merge

insolar/jet/postgres_dbstore.go, ledger/heavy/executor/finalize_pulse.go
=> Backport #3227 to v1.4.0

insolar/jet/postgres_dbstore.go, ledger/heavy/executor/finalize_pulse.go
=> Backport #3227 to release/1.4

Dockerfile, Makefile, application/cmd/insolar/bootstrap.go, applicationbase/bootstrap/bootstrap.go, applicationbase/bootstrap/config.go, applicationbase/bootstrap/keys.go, scripts/insolard/bootstrap_template.yaml, scripts/insolard/launchnet.sh, scripts/kube/README.md, scripts/kube/bootstrap/insolard.yaml, scripts/kube/bootstrap/kustomization.yaml, scripts/kube/bootstrap/run.sh
add kubernetes deploy support for https://github.com/insolar/kube
=> Penv 69 kube deploy support

application/cmd/benchmark/main.go
Add --delay-before-getting-balance flag in benchmark.
=> MN-126: add --delay-before-getting-balance flag in benchmark

.github/workflows/common.yaml
Added cleanup steps to self-hosted jobs
=> cleanup steps for self-hosted jobs

Dockerfile, insolar/defaults/defaults.go
support functest running without launchnet
=> Penv 84 kube support

.github/workflows/build_canceller.yaml
=> build_canceller

.github/workflows/common.yaml
Added artifact upload for failed func tests
Added artifact upload action
Check artifacts for any build with failed  func (pgsql/badger)
=> debug directories

Makefile
Little Makefile fix for MacOS Catalina.
=> NOISSUE: little makefile fix for MacOS Catalina

application/cmd/requester/capturer_test.go, application/cmd/requester/utils_test.go
fixed the data race in the tests  
=> PENV-105: fixed data race in the tests

.github/workflows/common.yaml, Makefile
=> Penv 118 functests on actions

.github/workflows/tag_processing.yml
Add [slack notification](https://github.com/insolar/git-tag-handler/) job
=> OPS-112: add git-tag-handler job configuration

cmd/insolard/main.go
=> PENV-3 fixed nil error

go.mod, go.sum, vendor/modules.txt
=> PENV-65: update insolar rpc lib

Makefile, scripts/kube/bootstrap/Dockerfile, scripts/kube/bootstrap/insolard.yaml, scripts/kube/bootstrap/run.sh
added image with func tests for kube deploy
=> PENV-21 docker image for kube deploy

application/builtin/contract/first/first.wrapper.go, application/builtin/contract/member/member.wrapper.go, application/builtin/contract/panicAsLogicalError/panicAsLogicalError.wrapper.go, application/builtin/contract/rootdomain/rootdomain.wrapper.go, application/builtin/contract/second/second.wrapper.go, application/builtin/contract/third/third.wrapper.go, application/functest/logicrunner_test.go, applicationbase/builtin/contract/nodedomain/nodedomain.wrapper.go, applicationbase/builtin/contract/noderecord/noderecord.wrapper.go, insolar/vm.go, logicrunner/preprocessor/templates.go
Allow to call GetPrototype and GetCode for any builtin contracts
Run functests
=> PENV-164: update call to gen contract methods

insolar/pulse/postgres_db_test.go
=> PENV-248: fix multiple run TestPostgresWriteReadAndLatest

.github/workflows/common.yaml, Makefile, application/functest/pressure_test.go, application/functest/test_utils.go, applicationbase/testutils/testrequest/request.go
Fixed data race in nightly runs
Test `TestPressureOnSystem` still fails on nightly, see https://insolar.atlassian.net/browse/PENV-251
=> PENV-248 fix datarace in nightly functests

ledger/heavy/executor/heavyreplicator.go, ledger/heavy/executor/metrics.go
add metrics for calculate record in jet https://insolar.atlassian.net/browse/MN-298
add in prometheus metrics in method sync in heavy
call  endpoint  /metrics
add metric in heavyreplicator.go and declare metric in  executor/metrics.go
=> MN-298: add metrics count record in jet

ledger/heavy/exporter/postgres_pulse_exporter_server_test.go, ledger/heavy/exporter/pulse_exporter.pb.go, ledger/heavy/exporter/pulse_exporter.proto, ledger/heavy/exporter/pulse_exporter_server.go, pulse/pulse_epoch.go
GetNextFinalizedPulse(int pulseno) FullPulse
tests
=> PENV-347: exporter of full pulses

README.md
Add links to mainnet and assured ledger repos, remove bench mention.
=> MN-478: upd README

insolar/vm.go, logicrunner/builtin/builtin.go, logicrunner/logicexecutor/logicexecutor.go
=> MN-490: not exist method is logic error

ledger/heavy/exporter/metrics.go, ledger/heavy/exporter/pulse_exporter_server.go, server/internal/heavy/components.go
I have added a new metric in the PulseServer.Export method.
=> MN-471: last exported pulse metric

ledger/heavy/executor/finalize_pulse.go, ledger/heavy/executor/heavyreplicator.go, ledger/heavy/executor/metrics.go
added saving jet drop time mteric
=> MN-504 added metric

ledger/heavy/exporter/metrics.go
commented potentially bad code, harcoded observer id
=> MN-488 test without FromContext

ledger/heavy/executor/heavyreplicator.go, ledger/heavy/executor/metrics.go, ledger/heavy/exporter/metrics.go, ledger/heavy/exporter/pulse_exporter_server.go, ledger/heavy/exporter/record_exporter_server.go
=> Mn 488 reverting

ledger/heavy/executor/finalize_pulse.go, ledger/heavy/executor/heavyreplicator.go, ledger/heavy/executor/metrics.go, ledger/heavy/exporter/badger_pulse_exporter_server_test.go, ledger/heavy/exporter/badger_record_exporter_server_test.go, ledger/heavy/exporter/metrics.go, ledger/heavy/exporter/postgres_pulse_exporter_server_test.go, ledger/heavy/exporter/postgres_record_exporter_server_test.go, ledger/heavy/exporter/pulse_exporter_server.go, ledger/heavy/exporter/record_exporter_server.go, server/internal/heavy/components.go
returned statRecordInDrop and statJetDropStoreTime
returned observerId in metric tags
added check that auth required in config
=> Mn 559 observer metrics

ledger/heavy/executor/heavyreplicator.go, ledger/heavy/executor/metrics.go
fixed cpu usage on heavy
actually only tag context changes matters
=> MN-599 fix heavy cpu usage

ledger/heavy/executor/heavyreplicator.go
=> MN-599 fix new problem with cpu usage in heavy

ledger/heavy/executor/heavyreplicator.go, ledger/heavy/executor/metrics.go, ledger/heavy/exporter/record_exporter_server.go
fixed record in jetdrop metric
fixed logs
=> Mn 640 fix metric

server/internal/heavy/components.go, server/internal/heavy/components_auth_test.go
I have changed the gRPC server interceptors to the correct one.
=> MN-650: fix gRPC server metrics

ledger/heavy/executor/heavyreplicator.go, ledger/heavy/executor/metrics.go
=> Merging release 1.5 and 1.6 into master

ledger/heavy/exporter/client_type.go, server/internal/heavy/components_validate_version_test.go
**What I did**
I've just replaced an underscore to dash.
=> MN-733: fix headers naming

configuration/exporter.go, server/internal/heavy/components.go
The 'required' option has been added.
The rate-limiting interceptors included only if the 'required' equals true.
Some useful comments have been added.
=> MN-771: make a rate-limiting optional

.github/workflows/common.yaml
=> OPS-385 send notification to slack if workflow job fails

.github/workflows/common.yaml, .github/workflows/tag.yaml, Dockerfile, README.md, api/requester/requester_test.go, docs/source/integration.rst, go.mod, go.sum, scripts/inslogrotator/go.mod, scripts/kube/bootstrap/Dockerfile
=> MN-828: use go 1.12
