- logicrunner/goplugin/ginsider/ginsider.go
- logicrunner/goplugin/girpc/girpc.go
- logicrunner/goplugin/goplugin.go
- logicrunner/goplugin/goplugin_test.go
- logicrunner/logicrunner.go
- logicrunner/types.go
this CBOR is serialized array of empty interfaces ([]interface{}{}) with
every element holding interface{} to one argument of the method
in case method has a variadic argument at the end of its signature then
the last element in the array should be an array with all variadic
values
> INS-108: all arguments in one CBOR blob

- ledger/artifactmanager/artifactmanager_test.go
- ledger/artifactmanager/descriptor_object_test.go
- ledger/storage/badgerdb/storage_test.go
parallelize tests which uses unique temporary store database
(because BadgerDB Close() method no so fast and significally slow down sequental tests)
> Speedup ledger tests

- ledger/storage/transaction_test.go
fix race condition in database tests
removed wrong code
fails in CI with text:
> WARNING: DATA RACE
Read at 0x0000022ba7c0 by goroutine 73:
github.com/insolar/insolar/ledger/storage_test.genuniqkey()
should gone
> NOISSUE: remove wrong code

- .travis.yml
> NOISSUE: disable CGO in CI for builds consistency on different platforms

- .travis.yml
> NOISSUE: remove go 1.10 from travis

- .golangci.yml
disable CI linter in some dirs with generated code and samples
> NOISSUE: CI linter should skip generated code and samples

- logicrunner/logicrunner.go
**use only initialized machintypes when processing calls**
> INS-413: use actual configured list of executors when obtaining object

- logicrunner/goplugin/preprocessor/main_test.go
sometimes we can get
can't build contract: 2018/10/04 20:47:35 cannot determine
current directory: getwd: no such file or directory
this happens when one test grabbed CWD from other test (tmp directory)
and it's been removed
> chdir - change of global state and doesn't work with parallel tests

- ledger/storage/transaction.go
clear transaction updates map right away after usage
> INS-606: clear transaction updates map right away after usage

- functest/main_test.go
- logicrunner/goplugin/goplugintestutils/insgorund.go
- logicrunner/logicrunner_test.go
- testutils/insgorund.go
* start with log message and random identifier
* report random identifier when stopping
* log a error if insgorund is running for a minute with stack trace,
helps find runaway daemons
* run Wait() so we don't leave zombies
* first .Kill(), then Wait() 3 seconds, then SIGTERM
should help us find hang insgorund processes that we either forgot to
stop or that are in deadlock
> improve greatly handling of insgorund in tests

- ledger/storage/lock_test.go
NOISSUE: fix flaky ledger test
'after' is not reliable because lack of synchronization
> NOISSUE: fix flaky ledger test

- logicrunner/logicrunner.go
* use closures with local variable rather than state struct,
local variable makes it clear that this thing is not used elsewhere
and makes problem isolated
* make only one defer conditional the one in the beginning, less logic
-> less chances of error
> simplify how we deal with lock during execution

- logicrunner/casebind.go
- logicrunner/logicrunner.go
low level common point of validation and execution.
we need this as first step towards executing or validating at the same
time. We should avoid detection in Execute method, this method should be
named HandleCalls.
> INS-834: executeOrValidate method

- certificate/manager.go
- network/servicenetwork/integr_test.go
multinode test suite
Using SetupSuite and TearDownSuite feature.
The main idea is to create a selected size network once from scratch before runs all integration test cases, and then shutdown it. Each test creates testNode with wrappers and hacks as needed
Now we can to run tests in the large and small networks
nope, tests do not pass, debug needed
> NET-12 NET-69 multinode test suite

- logicrunner/accessors.go
- logicrunner/logicrunner.go
os looks too much like abreviation from 'operating system', especially
when it's 'os.Lock()'
> INS-956: rename 'os' variable to 'st'

- logicrunner/logicrunner.go
- logicrunner/logicrunner_test.go
- logicrunner/logicrunner_unit_test.go
these were false positives: just call 1000 NoWaits on one object, they
all will be with the same TraceID and on executor and in one queue
> INS-1022: don't apply loop detection to NoWait calls

- logicrunner/logicrunner.go
> FIX: Use validable MessageBuss when sending ReturnResults message

- core/message/message.go
change gob to cbor because gob on different nodes give different results
> NO_ISSUE_change_message_serialyzer

- core/messagebus.go
- core/reply/base.go
- logicrunner/casebind.go
- messagebus/messagebus.go
- messagebus/player.go
- messagebus/player_test.go
- messagebus/recorder.go
- messagebus/recorder_test.go
- messagebus/sender_mock_test.go
- messagebus/tape.go
- messagebus/tape_mock_test.go
- messagebus/tape_test.go
- testutils/message_bus_mock.go
- store send errors on tape and returns it on replay
- remove unuse code
> Ins-976: store errors on tape

- core/vm.go
- logicrunner/casebind.go
- logicrunner/logicrunner.go
- logicrunner/logicrunner_test.go
- testutils/logic_runner_mock.go
**Refactor all logic runner message handlers to Handle<MessageName>Message, but Execute, it is legacy**
> Fix rename handlers

- logicrunner/logicrunner.go
state.ExecutionState.xxx
is not the same as:
es:= state.ExecutionState
es.xxx
> INS-1075: crrectly work with locks and subfields

- Gopkg.lock
- Gopkg.toml
- functest/create_member_test.go
- messagebus/tape.go
we had an issue with lock in CBOR codec, in code that finds
encoder/decoder implementation by argument type. New commits on git
has this problem fixed. We confirmed with mutex pprof'ing.
> INS-1077: update CBOR version to the latest, get rid of lock issue

- logicrunner/accessors.go
- logicrunner/logicrunner.go
we access the map when contracts do sub-calls and we never write
there, so we can take RLock and all concurrent contracts can do
this at the same time. WLock is held when we insert new records
and on pulse change.
> rw mutex for state map in logic runner should be more effective

- network/servicenetwork/servicenetwork.go
NetworkSwitcher.OnPulse() should be executed before PulseManager.Set()
> NOISSUE: fix HandlePulse

- core/networkcoordinator.go
- network/servicenetwork/servicenetwork.go
- networkcoordinator/interface.go
- networkcoordinator/networkcoordinator.go
- networkcoordinator/real.go
- networkcoordinator/zero.go
- testutils/network_coordinator_mock.go
Removed legacy method `WriteActiveNodes` from NetworkCoordinator
> NOISSUE: remove legacy method `WriteActiveNodes` from NetworkCoordinator

- logicrunner/logicrunner.go
it shouldn't happen, but it feels that some code replaces es.Current
while we are executing "call constructor". We start with one es.Current.Request
and return different one. Protect this code by making a copy of
*es.Current into a local variable, so data stays the same within one
function. Do it for call constructor and for call method as well.
> es.Current is a pointer, es is a pointer, protect from change under us

- cmd/exporter/main.go
- ledger/exporter/exporter.go
- ledger/exporter/exporter_test.go
- ledger/ledger.go
We don't need data from current pulse, because of
not all data for this pulse is persisted at this moment.
Only ended pulses data for exporter.Export 
break for-loop when current pulse number equals iteration pulse number
> INS-1032: only ended pulses data for exporter.Export

- messagebus/messagebus.go
checkPulse thinks that it's a message from future, but pulse changes
before it can block on old pulse channel (barrier), we already swiped it
with a new one, so message stays in the queue for pulse duration
> it's possible that a message stays in message bus queue for a pulse

- metrics/insolar.go
- metrics/metrics_test.go
- metrics/network.go
- network/controller/rpc_controller.go
- network/transport/base.go
- network/transport/future.go
- network/transport/handler.go
- network/transport/pool/connectionpool.go
prometheus metrics for network
```golang
// NetworkParcelSentTotal is total number of sent messages metric
var NetworkParcelSentTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
Name:      "parcel_sent_total",
Help:      "Total number of sent parcels",
Namespace: insolarNamespace,
Subsystem: "network",
}, []string{"messageType"})
// NetworkParcelReceivedTotal is total number of received messages metric
var NetworkParcelReceivedTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
Name:      "parcel_received_total",
Help:      "Total number of received parcels",
Namespace: insolarNamespace,
Subsystem: "network",
}, []string{"messageType"})
// NetworkPacketSentTotal is total number of sent packets metric
var NetworkPacketSentTotal = …
```
> Noissue network metrics

- configuration/servicenetwork.go
- core/network.go
- network/controller/bootstrap/bootstrap.go
- network/pulsenetwork/distributor.go
- network/servicenetwork/servicenetwork.go
- network/transport/base.go
- pulsar/pulsar_integration_test.go
- pulsar/pulsarbroadcasters.go
- scripts/generate_insolar_configs.go
- scripts/insolard/launchnet.sh
- scripts/insolard/pulsar_template.yaml
- testutils/pulse_distributor_mock.go
1. Fixed bug in pulsar distributor that caused timeouts
2. Now pulsar sends pulses only to the nodes from `pulsedistributor.bootstraphosts` configuration params (getRandomHosts is not called)
3. Added magic number `Skip` to servicenetwork configuration that allows to skip a couple of pulses before network bootstrap to have synchronized first pulse on all nodes (very helpful on short pulses < 3000ms)
4. Pulsar config in launchnet is now generated based on `pulsar_template.yaml` (all settings except bootstraphosts) and `genesis.yaml` (bootstraphosts)
Run launchnet.sh on 20+ nodes and check with script `ag -m1 'persist' scripts/insolard/nodes/*/output.log 2>/dev/null | awk '{print $4}' | sort -u` that all nodes start from one pulse
ps: previous pull …
> NOISSUE: fix pulsar distribution

- ledger/exporter/exporter.go
- ledger/exporter/exporter_test.go
Error for exporter api when fromPulse bigger then current was added
```
if fromPulsePN > currentPulse.PulseNumber {
return nil, errors.New("failed to fetch data: from-pulse > current-pulse")
}
```
> INS-1167: add error for exporter api when fromPulse bigger then current

- logicrunner/logicrunner_test.go
request could reach panic before socket close as closing socket may be
slow, travis CI showed us such situation
> close socket before sending request

- core/vm.go
- logicrunner/logicrunner.go
- logicrunner/logicrunner_unit_test.go
- testutils/machine_logic_executor_mock.go
* also added mocks for MachineLogicExecutor
if state wasn't changed (cbor byte representation is the same), then we won't create new amend for current object.
test included
> INS-1235: do not send state back to light, if it wasn't changed

- scripts/docker-compose.yml
- scripts/insolard/launchnet.sh
- scripts/insolard/profile.sh
* allow redefine logging level for `launchnet.sh`
* make profiling time configurable in `profile.sh`
* issue with insolard configs parsing in `profile.sh` fixed
* issue with Prometheus config path conflict with docker compose dir creation solved
> Noissue instruments improvements

- consensus/packets/data_test.go
- consensus/packets/phase1packet.go
- consensus/packets/phase2packet.go
- consensus/packets/phase3packet.go
- consensus/phases/communicator.go
- consensus/phases/communicator_mock.go
- consensus/phases/firstphase.go
- consensus/phases/phasemanager.go
- consensus/phases/secondphase.go
- consensus/phases/thirdphase.go
- network/controller/bootstrap/authorization.go
- network/controller/bootstrap/bootstrap.go
- network/controller/bootstrap/challenge_response.go
- network/controller/controller.go
- network/controller/pulsecontroller.go
- network/controller/rpc_controller.go
- network/hostnetwork/transport_consensus_test.go
- network/interfaces.go
- network/servicenetwork/communicator_mock.go
- network/servicenetwork/servicenetwork.go
- network/servicenetwork/suite_test.go
Nodes now resend pulse on first consensus phase. If the pulse is received via first phase, the consensus starts if not started yet. Also fixed races on start of the network components.
Run unit and integration tests.
> INS-1291: start consensus when receive first phase packet

- ledger/storage/cleaner.go
it's just a precaution as "PrefetchSize = 0" should have the same
effect, but it's not clear from documentation and PrefetchValues
is clearly documented
> INS-1331: PrefetchValues = false as we don't need values

- .gitignore
- Makefile
- scripts/dev/cover-filter.sh
- scripts/dev/cover-tool.sh
move .PHONY close to target itself, it is too easily forget to add a target to .PHONY if use lists
(without .PHONY it could be painful to figure out why your go binary doesn't compile)
> Add to all non file targets a .PHONY directive, improve coverage calculation

- logicrunner/accessors.go
- logicrunner/casebind.go
- logicrunner/executionstate.go
- logicrunner/logicrunner.go
- logicrunner/logicrunner_unit_test.go
* delete Ref from ObjectState, it was not used
* add Ref to ExecutionState, it was needed in a few places
* take Ref from E.S. in a few methods instead of passing as argument
* logicrunner/executionstate.go file with one type
* ClarifyPendingState that checks Parcel and converts Unknown pending
state into known
* no more need for message in StartQueueProcessorIfNeeded, message was
needed in one place only
> INS-1493: refactor LR a bit

- ledger/pulsemanager/pulsemanager.go
- ledger/storage/metrics.go
- ledger/storage/pulsetrackermemory.go
Add DeletePulse in cleanLightData
add 2 metrics
metrics
```
statPulseDeleted = "lightcleanup/pulses/removed/total" - "How many pulses deleted from pulseTracker on LM cleanup"
statPulseAdded   = "lightcleanup/pulses/added/total" - "How many pulses added to pulseTracker"
```
> INS-1416: clean in-memory pulseTracker pulses

- ledger/ledger.go
Change pulseTracker storage for nodes:
```
HEAVY-MATERIAL - DB
LIGHT-MATERIAL - in-memory
VIRTUAL        - in-memory
```
```
if certificate.GetRole() == core.StaticRoleHeavyMaterial || certificate.GetRole() == core.StaticRoleUnknown {
pulseTracker = storage.NewPulseTracker()
} else {
pulseTracker = storage.NewPulseTrackerMemory()
}
```
> INS-1533: change pulseTracker storage for nodes

- core/ledger.go
- ledger/artifactmanager/artifactmanager.go
- ledger/artifactmanager/middleware.go
New method named Pulse added for ArtifactManager.
m.PulseManager.Current() replaced with m.Pulse()
```
func (m *LedgerArtifactManager) Pulse(ctx context.Context) (pn core.PulseNumber, err error) {
pulse, err := m.PulseStorage.Current(ctx)
if err != nil {
return
}
pn = pulse.PulseNumber
return
}
```
> INS-1238: refactoring AM with new method - Pulse(...)

- cmd/insolard/main.go
- cmd/pulsard/main.go
- configuration/configuration.go
- configuration/configuration_test.go
- configuration/testdata/changed.yml
- configuration/testdata/default.yml
- scripts/generate_insolar_configs.go
* remove prefix 'insolar' from yaml configuration (in Save/Load
functions)
* register names of env variables at start, load them simultaniously
with configuration file in Load/LoadFrom functions
* make Save/SaveAs to save in expected file format
* in configuration test - stash all 'INSOLAR_' before test and load them
after again (may be a problem in parallel testing)
> INS-1612: make Save/SaveAs to work as expected

- Makefile
Increase timeout for network tests up to 40 minutes
> INS-1196: increase go test timeout up to 40 min

- network/hostnetwork/transport_base.go
- network/hostnetwork/transport_consensus.go
- network/hostnetwork/transport_resolvable.go
- network/hostnetwork/transport_test.go
- network/interfaces.go
- network/pulsenetwork/distributor.go
- network/servicenetwork/servicenetwork.go
- network/transport/transport.go
- testutils/network/host_network_mock.go
Now error from transport.Listen is passed up to ServiceNetwork so we know early when Insolar network module can't occupy a network port for its needs.
Run unit and integration tests
> INS-2043: pass listen error up to ServiceNetwork

- ledger/artifactmanager/artifactmanager.go
- logicrunner/logicrunner.go
* wrap error so it's clear what operation we do
* warn when we failed to execute a contract
> INS-2025: improve logging in all users of UpdateObject message

- scripts/bench.sh
- scripts/build/fetchdeps
- scripts/dev/codecov.py
- scripts/dev/cover-filter.sh
- scripts/dev/cover-tool.sh
- scripts/glogs
- scripts/insolard/check_status.sh
- scripts/insolard/launchnet.sh
- scripts/insolard/profile.sh
- scripts/insolard/start_nodes.sh
- scripts/monitor.sh
- scripts/prom/run.sh
- scripts/stats
`/bin/{sh,bash}` is not available in some distributions
> NOISSUE: cross-distro shebangs

- network/servicenetwork/suite_test.go
Increased integration tests initialization timeout to 30s. This can decrease number of false failing tests.
run integration tests
> NOISSUE: increase integration tests initialization timeout to 30s

- cmd/pulsewatcher/pulsewatcher.go
Fixed error when we get out of available TCP ports.
Run `launchnet.sh`, run `sudo lsof -i -n -P | grep TCP | cut -f1 -d' ' | sort | uniq -c` and verify that pulsewatcher does not waste TCP ports
> INS-2176: do not create a new transport in each request iteration

- pulsar/pulsar_integration_test.go
> skipped one integration test

- log/zerolog.go
- metrics/metrics.go
- metrics/status.go
An API for changing loglevel without restarting a node was added. A corresponding test will be added to integration (junit+java) tests after merging.
```
$ curl 'http://localhost:8005/debug/loglevel?level=warn' 2>&1
OK, new log level: 'warn'
$ curl 'http://localhost:8005/debug/loglevel?level=debug' 2>&1
OK, new log level: 'debug'
$ curl 'http://localhost:8005/debug/loglevel?level=info' 2>&1
OK, new log level: 'info'
$ curl 'http://localhost:8005/debug/loglevel?level=ololo' 2>&1
Invalid level 'ololo'
$ curl 'http://localhost:8005/debug/loglevel' 2>&1
Invalid level '(nil)'
$ tail -n 25 .//scripts/insolard/discoverynodes/5/output.log
```
> INS-2219: change log level "on the flight"

- Makefile
versions of gopkg.com/x/net used in godep and in stringer are
two years apart from each other (July 2017 for godep and March 2019 for
stringer).
`go cache -modclean` deletes old net module (used for building godep)
and refetching of net repo works just fine.
cherry-pick of master commit
> NOISSUE: fix building of insolar in case of clean installation

- internal/ledger/artifact/descriptors.go
- internal/ledger/artifact/object_descriptor_mock.go
- logicrunner/artifacts/artifacts.go
- logicrunner/artifacts/client.go
- logicrunner/artifacts/descriptors.go
- logicrunner/artifacts/object_descriptor_mock.go
- logicrunner/goplugin/goplugintestutils/utils.go
this makes descriptors passive, just data holders, Children method, I
deleted, was just a syntax sugar for method in A.M. client
> INS-2002: remove A.M/ctx from descriptors

- insolar/vm.go
- logicrunner/builtin_test.go
- logicrunner/logicrunner.go
- logicrunner/logicrunner_test.go
- logicrunner/logicrunner_unit_test.go
all message handlers should start from Handle. This is handler for two
messages: CallMethod and CallConstructor, so we name it HandleCalls
> INS-2002: rename LR.Execute to HandleCalls, we agreed earlier on this

- insolar/gen/reference.go
c.Fuzz(id) was resulting in recursive call as `id` has type jetID.
fuzzer is smart and just ignores the call and jetID is filled with
zeroes. We had very good chance that fuzzer generates the same jetID
during one test multiple times.
For example the following tests was falling quite fast:
go test ./ledger/storage/drop/... -count 1000 -run TestDropStorageMemory_Delete -failfast
> INS-2351: jetID generator was using the same zero data all the time

- insolar/flow/handler/handler.go
- ledger/proc/proc.go
- ledger/proc/send_object.go
don't close channel, just make sure no user of the channel blocks by
also accounting ctx.Done() channel as a signal. All users go away
and channel goes garbage collected.
> INS-2352: fix send to closed channel panic during reply to message

- ledger/replication/cleaner_test.go
- ledger/replication/lightreplicator_test.go
- logicrunner/logicrunner_unit_test.go
- network/termination/handler_test.go
you expect them to happen and if they don't then test FAILS, 10ms
is TOO SMALL duration, it randomly fails under -race flag, on slow
machines, on C.I, on virtual nodes....
> INS-2375: wait for expected minimock calls for a minute at least

- insolar/gen/reference.go
- ledger/storage/drop/memory_test.go
- testutils/core.go
fix tests that use more than one generate jet by making sure used jets
are not the same as it expected by the tests
> INS-2363: it was possible to generate two JetIDs that are the same

- scripts/insolard/launchnet.sh
after implementing parallel kill and final wait, we see tests hanging
from time to time on our test agents. let's rollback to previous
solution.
my idea is that we either start a child and don't kill it or order of
kills is important
> INS-2393: I believ that in some situation `wait` never finishes

- insolar/record/record_test.go
looks like fuzzer creates an instance of math.Rand and this object can
not be accessed concurrently and fuzzer doesn't protect it with a lock
```
WARNING: DATA RACE
Read at 0x00c0001a4000 by goroutine 15:
math/rand.(*rngSource).Int63()
/opt/local/lib/go/src/math/rand/rng.go:239 +0x3e
math/rand.(*Rand).Int63()
/opt/local/lib/go/src/math/rand/rand.go:85 +0x50
math/rand.(*Rand).Int()
/opt/local/lib/go/src/math/rand/rand.go:103 +0x38
github.com/insolar/insolar/vendor/github.com/google/gofuzz.randBool()
/Users/ruz/go/src/github.com/insolar/insolar/vendor/github.com/google/gofuzz/fuzz.go:449 +0x38
github.com/insolar/insolar/vendor/github.com/google/gofuzz.glob..func1()
/Users/ruz/go/src/github.com/insolar/insolar/vendor/github.com/google/gofuzz/fuzz.go:414 +0x38 …
```
> INS-2397: fuzzer can not be used concurrently, causes race

- version/manager/utils_test.go
- version/manager/versionmanager_test.go
test uses shared package variable, so second pass uses data from
previous pass and test was not ready for that.
> INS-2424: make it possible to run version/manager tests with -count 10

- ledger/light/artifactmanager/handler_test.go
test suite can start preping next test case when callback triggers and
runs suite.T() function that may result in a race
> INS-2461: wait for expected minimock tests to happen before leaving

- insolar/flow/internal/thread/controller.go
In case when controller.Cancel is called on pulse change - it may take
broken data. Fix it with locking cancel mutex inside `.Cancel`.
> NOISSUE: fix for race condition in flow contoller

- logicrunner/logicrunner.go
- logicrunner/logicrunner_unit_test.go
```
$ time go test -failfast -race ./logicrunner/ -run 'TestLogicRunner/TestCallMethodWithOnPulse/pulse_change_in_CallMethod' -count 10000
ok  	github.com/insolar/insolar/logicrunner	201.612s
real	3m24.203s
user	8m6.812s
sys	0m28.378s
```
> INS-2493: fix goroutines leak and data races in LR tests

- logicrunner/artifacts/client.go
all pending requests should be tracked by object, requests should be
executed in order and object should be able to tell which one goes first
and which is last. results also go next to requests, so next to objects.
> request should be stored next to object it belongs to

- network/tests/suite_test.go
Increased integration tests pulse duration to decrease frequency of tests failures. This is not a complete solution for flaky integration tests, only a temporary mitigation.
Run integration tests
> NOISSUE: Mitigating integr tests problems until consensus is reworked

- ledger/light/artifactmanager/middleware.go
- ledger/light/hot/waiter.go
- ledger/light/hot/waiter_test.go
- ledger/light/proc/wait_jet.go
- ledger/light/pulsemanager/pulsemanager.go
- testutils/jet_releaser_mock.go
a message can come close to the end of the current pulse, spend some
time figuring out jet and jet tree and then hang waiting for hot data
until next pulse. this happens when waiter for hot data was refreshed
as pulse has been changed while we were figuring out jet and jet tree.
we discussed this and decided that we wouldn't be saving hot data
history for older pulses. we just make hot data waiter PULSE aware and
make it relase waiter immediately if message is from older pulse.
> INS-2515: account for pulse in hot data waiter

- network/hostnetwork/consensus_network_test.go
- network/hostnetwork/hostnetwork_test.go
- network/interfaces.go
Fixed network tests to prevent data races. Also fixed all teardown methods to guarantee that all occupied ports are released after test.
Run network tests with big count
> INS-2503: network tests stabilization

- component/manager.go
- component/manager_test.go
Prevent call Stop() before Start() on component manager
> INS-1635: CM: don't call Stop() in Start() is not called yet

- Makefile
Tests in /server/internal/ are tagged with `+build slowtest`. I've added them to `test_slow` and `ci_tests_slow` targets in Makefile.
> NOISSUE: added /server/internal/ to slow tests

- internal/ledger/store/badger_test.go
- internal/ledger/store/db_cmp_test.go
- network/storage/cloudhash_test.go
- network/storage/pulse_test.go
- network/storage/snapshot_test.go
- network/storage/storage_test.go
- server/internal/heavy/components.go
fix INS-2550
Added missed db.Stop call
```shell
go test -timeout 1200s -v ./internal/ledger/store -run "TestBadgerDB_Set" -count 1000 -failfast -race
```
> INS-2550: fix missed db.Stop

- logicrunner/handle_calls.go
- logicrunner/logicrunner_unit_test.go
* Remove outdated comment
* executeActual in fact doesn't always execute anything, thus handleActual is a better name.
> NOISSUE: Minor LR refactoring

- logicrunner/accessors.go
- logicrunner/handle_ledgerpendingrequest.go
- logicrunner/handle_processqueue.go
- logicrunner/logicrunner.go
* doesn't create empty ObjectState what fixes a TODO
* placed in correct place next to other accessors
* keep deserializing concern out of accessor method, do it in caller
> GetExecutionState returns ES only if it exists or NIL

- pulsar/pulsar_integration_test.go
`pulseDistributor.MinimockWait(1 * time.Second)` instead of `pulseDistributor.MinimockWait(100 * time.Millisecond)`
> INS-2526: more timeout for test

- logicrunner/preprocessor/main_test.go
- logicrunner/preprocessor/real_contracts_test.go
Moved `logicrunner/preprocessor/main_test.go` and `logicrunner/preprocessor/real_contracts_test.go` under `+build slowtest` build tag.
> INS-2593: move preprocessor tests under slowtest tag

- logicrunner/handle_calls.go
fix NPD due to wrong init of ExecutionState
> INS-2627: fix NPD due to wrong init of ExecutionState

- logicrunner/handle_calls.go
Fix NPD in messagebase which is caused by returning (nil, nil) from HandleCall
> INS-2627: fix panic if return nil, nil

- network/servicenetwork/servicenetwork.go
Stop setting traceID from response message to context, i.e. network already done it.
Run bench and check for logs
> NOISSUE: dont set traceid for net resp

- api/contract.go
- insolar/message/ledger.go
- ledger/light/artifactmanager/handler.go
- ledger/light/proc/update_object.go
- ledger/light/proc/update_object_test.go
- logicrunner/artifacts/artifacts.go
- logicrunner/artifacts/client.go
- logicrunner/artifacts/client_mock.go
- logicrunner/builtin_test.go
- logicrunner/goplugin/goplugintestutils/utils.go
- logicrunner/logicrunner.go
- logicrunner/logicrunner_test.go
- logicrunner/logicrunner_unit_test.go
ActivateObject, UpdateObject and DeactivateObject now send result record
along with update record
a few things that were in the way:
* delete DOMAIN argument from a few methods in artifact manager client,
this field is not used
* AM client loses not used methods: DeclareType, UpdatePrototype,
RegisterResult
> INS-2660: send side effect and result record in one message

- functest/helloworld_test.go
Test checks not builtin contracts, but everything around:
* child creation, iteration over child
* exactly call count checking
> INS-2693: partially disable builtin test

- server/internal/heavy/components_test.go
- server/internal/light/components_test.go
- server/internal/virtual/components_test.go
it doesn't matter which port to use in initialization tests
> INS-2704: fix the same port bind in server initialization tests

- api/call_test.go
the fix is in mc.Wait() that makes sure we don't change mocked function
while running code of the function
got rid of suite as one test was testing "no timeout" and other "with
timeout" and these required different configuration
> INS-2612: fix race in TestTimeoutSuite

- functest/reconnect_test.go
No child related calls in InsgorundReload test
> INS-2739: TestInsgorundReload with no childs

- logicrunner/artifacts/artifacts.go
- logicrunner/artifacts/cache_mock.go
- logicrunner/artifacts/client.go
- logicrunner/artifacts/decriptors_cache.go
- logicrunner/artifacts/decriptors_cache_test.go
- logicrunner/artifacts/descriptors_cache_mock.go
- logicrunner/logicrunner.go
- logicrunner/logicrunner_rpc_methods.go
- logicrunner/logicrunner_unit_test.go
- server/internal/virtual/components.go
* new immutable calls introduce races in old implementation
* old code could make parallel requests for the same object
* old code was fetching the same prototype many times, new code cache
prototypes
> INS-2008: introduce DescriptorsCache

- ledger/light/replication/cleaner.go
- ledger/light/replication/cleaner_test.go
- ledger/light/replication/lightreplicator.go
- ledger/light/replication/lightreplicator_test.go
Set new traceId to LightCleaner's and LightReplicatorDefault's background processes
> INS-2558: set new trace id to backgound processes on light

- network/controller/pinger/pinger_test.go
- network/hostnetwork/hostnetwork.go
Here is special protobuf message ResponseError
And we will send it if error was returned from handler.
> NOISSUE: send error via network rpc if generated

- logicrunner/executionstate.go
- logicrunner/handle_calls.go
- logicrunner/logicrunner.go
- logicrunner/logicrunner_unit_test.go
once WrapError methods are gone then ExecutionState is not required in
execute{Method,Constructor}Call methods
> INS-2008: delete custom WrapError methods and as result ES argument

- logicrunner/handle_abandonedrequestsnotification.go
- logicrunner/logicrunner_unit_test.go
they don't work at the moment, we wait for a branch to be merged that
should change drastically how pending requests work.
the current problem is that we get notification, handle it, record
result, ask for next request from ledger, get the same, repeat this loop
forever.
our tests at this moment shouldn't suffer
> disabling notifications from ledger regarding abandoned requests

- api/requester/requester.go
- functest/create_member_test.go
- functest/utils_test.go
Rewrite retry func for create member requests
Update logic for setting public key to params
Delete TestCreateMemberWithoutBurnAddresses (it will be rewrite in WLT-600)
Run tests
> Wlt 601 update create member tests

- logicrunner/currentexecution.go
- logicrunner/executionstate.go
- logicrunner/logicrunner.go
- logicrunner/logicrunner_unit_test.go
we were not deleting executed transcript from list of current
executions before sending result. this could lead to new incoming
request to the same object with the same APIRequestID and false loop
detection.
new code deletes request from list of currently executed queries right
after saving everything to ledger and before sending a reply
> INS-2008: SentResult was a workaround, get rid of it

- logicrunner/executionstate.go
- logicrunner/handle_executorresults.go
- logicrunner/logicrunner.go
if we next executor on pulse change and decided that execution died
then we should start queue processor. otherwise we could wait more than
one pulse if execution stayed on the same virtual for several pulses
> we were not restarting local execution when we think previous died

- logicrunner/logicrunner.go
- logicrunner/logicrunner_rpc_methods.go
our RPC service in L.R. helps machines executors to interract with other
contracts and system around them, we need two implementations here.
Without implementing validating split original.
> INS-2008: implement two implementations of proxy helper methods

- logicrunner/currentexecution_test.go
Sometimes QueueProcessor (for example, if we have nothing to process)
finishes before we're checking "processActive" value.
Will be fixed in the future using mocks and channels
> INS-2868: remove faulty checks in tests

- logicrunner/goplugin/goplugintestutils/insgorund.go
fix insgorund cleaner call in tests with count
change sigkill to sigterm, sigkill doesn't handle as expected https://github.com/golang/go/issues/9463
run tests, now contractcache-* directories remove after each test iteration
> INS-2870 fix insgorund cleaner call

- Makefile
That's needed to check in CI that we've commited new versions of
proxy/wrapper/initializer for builtin contracts
> INS-2714: Add regen-builtin to pre-build

- functest/logicrunner_test.go
this test became outdated  after moving to builtin contracts without allowance
> INS-2706 remove outdated test

- api/contract.go
- functest/logicrunner_test.go
- functest/utils_test.go
- logicrunner/handle_calls.go
because of pulse change recursive call can go to different executor that
would fail to detect loop and hit timeout.
we don't to fix this special case right now and for quite a while, but
test disabling is not an option too.
> INS-2905: allow a few timeouts in "loop detection" test

- logicrunner/executionbroker_test.go
Race condition was introduced (we've changed pending state in runtime)
and processTranscript + Execute (finishPendingIfNeeded) sends pending
state when it shouldn't
> INS-2921: fix for flaky TestExecutionBroker/TestImmutable

- logicrunner/currentexecution.go
- logicrunner/executionbroker.go
- logicrunner/executionbroker_test.go
- logicrunner/executionstate_test.go
- logicrunner/handle_calls.go
- logicrunner/handle_executorresults.go
- logicrunner/handle_ledgerpendingrequest.go
- logicrunner/logicexecutor.go
- logicrunner/logicrunner.go
- logicrunner/logicrunner_rpc_methods.go
- logicrunner/logicrunner_rpc_methods_test.go
- logicrunner/logicrunner_unit_test.go
- logicrunner/requestsexecutor.go
- logicrunner/requestsexecutor_test.go
- logicrunner/rpc_methods_test.go
this field is required and it's easy to do the following mistake:
for _, qe := range p.msg.Queue {
transcript := NewTranscript(ctx, &qe.RequestRef, qe.Request)
...
}
all transcripts in above code have the same request reference as all
pointers point at the same reference.
> request reference in transcript is not pointer

- insolar/message/logicrunner.go
- logicrunner/executionbroker.go
- logicrunner/executionbroker_test.go
- logicrunner/handle_calls.go
- logicrunner/handle_executorresults.go
- logicrunner/logicrunner.go
* cover ExecutorResults containing requests for execution
* cover AdditionalCallFromPreviousExecutor
* correctly switch to transcript.Context in the broker when executing
> INS-2944: restore ServiceData when we pass requests between virtuals

- ledger/light/proc/activate_object.go
- ledger/light/proc/activate_object_test.go
1) this should be an error with or without deduplication
2) the old code wasn't returning anything, resulted in watermill timeout
on the caller side
3) our tests setup doesn't execute duplicated requests at the moment
> INS-2798: return error if we try to activate duplicate record

- contractrequester/contractrequester.go
- contractrequester/contractrequester_test.go
* inject platform cryptography, don't create a new one every time
* make sure registered request have the same hash
> a few improvements in contract requestor

- api/requester/requester.go
- api/requester/requester_test.go
- logicrunner/goplugin/foundation/crypto.go
Replaced handmade ECDSA signature serialization with stdlib ASN.1 marshaling.
I've found an unmarshaling example in [crypto/openpgp](https://github.com/golang/crypto/blob/master/openpgp/packet/signature.go#L563) library and implemented serialization the same way.
> INS-2981: correct signature marshalling

- api/call.go
- api/sdk/sdk.go
- functest/member_create_test.go
- functest/member_get_test.go
- functest/member_migration_create_test.go
Added root member reference auto set in request.
Check in API what method in request. If it is `member.create, member.migrationCreate, member.get` then set reference to genesisrefs.ContractRootMember. 
Also edited tests and sdk
Launch tests and bench
API RootRef auto set
> INS-3008: added root member reference auto set

- Makefile
> [INS-3025] delete hardcoded INSOLAR_LOG_LEVEL from Makefile

- functest/get_balance_test.go
- functest/register_node_test.go
- functest/send_money_test.go
these tests result in forever open requests on ledger that affect other
tests, result in timeouts. we're fixing root cause right now.
> INS-3096: skip tests while we waiting for a few fixes landing in master

- functest/new_api_test.go
- logicrunner/builtin/contract/member/member.go
Fixed panic if call with invalid params
Added comparison statement
launch TestIncorrectParams
> INS-3109: fixed panic if incorrect params

- functest/pressure_test.go
- functest/utils_test.go
- insolar/utils/utils.go
- logicrunner/logicrunner_unit_test.go
fix concurrency test
move SyncT to testutils and reuse it
run 
go test ./logicrunner/ -run '^TestLogicRunner$' -timeout 0 -count 100000 -failfast -v -race
and wait 2 hours
> INS-3011 use thread safe t in concurency test

- logicrunner/currentexecution.go
- logicrunner/requestsexecutor_test.go
RequesterNode is not used anymore, we use fields from the request
it was a duplication
> drop unused field Transcript.RequesterNode

- logicrunner/logicrunner_unit_test.go
fix race in test code
use syncT.Require instead of suite.Require
> INS-3011 suite.Require isn't tread safe

- logicrunner/executionbroker.go
Previously this code was needed to protect execution queue from taking the task, that shouldn't be executed; now it's replaced by WriteAccessor barrier
> NOISSUE: remove obsolete code (fixed by WriteAccessor)

- insolar/bus/retryer.go
- insolar/bus/waiter.go
- insolar/bus/waiter_test.go
- logicrunner/artifacts/client.go
- logicrunner/logicrunner.go
- Change `tries` field in `RetrySender` struct to `retries` - now max number of attempts to send request is 1+retries (one send+amount of retries).
- _flow cancelled_ error retries only one time
Runs tests.
> INS-3141: one retry on flow cancelled

- certificate/manager_test.go
- insolar/jetcoordinator/jetcoordinator_test.go
- insolar/record_test.go
- ledger/light/executor/jet_fetcher_test.go
- ledger/object/index_db_test.go
- ledger/object/record_test.go
- logicrunner/handle_abandonedrequestsnotification_test.go
- logicrunner/logicrunner_unit_test.go
- testutils/core.go
Removed testutils.Random<Whatever> functions and replaced their usages with gen.* alternatives.
> INS-3122: get rid of testutils.Random<Whatever> functions

- insolar/bus/retryer.go
- insolar/bus/retryer_test.go
- insolar/bus/waiter.go
- logicrunner/artifacts/client.go
- it'll allow us to eliminate WaitOKSender/WaitOKWithRetrySender
- removed premature `done()` check that'll lead to request won't be send
at all
side-effect: if someone'll send us `payload.Error` - it'll be the last message in the queue
> INS-3237: added new option for RetrySender (number of messages to wait)

- server/internal/heavy/server.go
- server/internal/light/server.go
- server/internal/virtual/server.go
because metrics should be service-wide, not process-wide and we already have
server type in collected metrics (added by Prometheus server)
> Use insolar prefix for all insolar servers invocations

- log/log.go
getwd system call is very expensive
we know that we don't change working directory
we also know that we trim "...github.com/insolar/insolar"
this should work and cut ConsoleLogger penalty very much
> default logger trims CWD prefix from "file" field

- logicrunner/pulsemanager/pulsemanager.go
- logicrunner/result_matcher.go
- logicrunner/result_matcher_mock.go
* delete(rm.unwantedResponses, reqRef) in correct place when
recieved still executing message, not when we recieved unwanted
results
* improve logging
* log all not matched unwanted results, this means still executing
didn't come during the pulse
* use less pointers
> INS-3219: changes in results matcher

- ledger/object/lock_test.go
use the same prefix for locker test, increase timeouts for hostile environments (like CI)
> INS-3301: refactor locker tests

- ledger/heavy/executor/jetkeeper.go
- ledger/heavy/executor/jetkeeper_test.go
…ferent: it's ok situation
Don't do error logging in case of different length of topSync jets and incoming jets, since it's possible situation when not all jets still come.
Run tests
> INS-3277: fix logging in jetkeeper: don't logError if lengthes are different

- ledger/light/executor/request_checker.go
- ledger/light/integration/server_test.go
- server/internal/light/components.go
Fix hasher for request checker
Change arguments for singleton constructor of request checker - from `hash.Hasher` to `Insolar.PlatformCryptographyScheme` (because we need new `hasher` every time when we use id calculation)
> INS-3308: fix hasher for request checker

- logicrunner/executionbroker.go
- logicrunner/executionbroker_test.go
old code was not accounting existing of registry and that broker
is new every pulse.
new reality is that object is in pending even if pending execution
is on this node
old code was starting second mutable execution on the same node
and if it was the same request then context on outgoing calls was
shared resulting in different Nonce values and creating new
requests.
> INS-3219: when execution returns to node executing pending

- logicrunner/executionbroker.go
- logicrunner/executionbroker_test.go
- logicrunner/logicrunner_unit_test.go
deduplicate using registry as well, pulse ends - new broker, never
put into queue what we're executing right now
> INS-3219: execution broker has no all knowledge anymore

- Makefile
Mark light integration tests with slow tag (for CI)
> NOISSUE: move light integration tests to slow tag

- functest/activatedaemon_test.go
Skipped `TestActivateDaemonDoubleCall` until it is fixed by @sansaian
> INS-3344: skip test until it is fixed

- logicrunner/executionbroker.go
- logicrunner/executionbroker_test.go
- logicrunner/logicrunner_unit_test.go
* unify mutable and immutable processing, the only difference
is parallel or not
* introduce sub-structure processorState
* start only one immutable processor as well as mutable
* release 'active' flag in the same function we take it
I tried to create a new struct with methods, but it ended
up very interconnected with broker code. Gave up on this
for now.
> rework queue processors starting in execution broker

- logicrunner/executionbroker.go
- logicrunner/handle_calls.go
- logicrunner/requests_executor_mock.go
- logicrunner/requestsexecutor.go
- logicrunner/requestsexecutor_test.go
* not all callers of the method have Transcript around
* extract two sending functions to simplify code
* check that either reply is not empty or error is not empty
* test more cases
> change signature of SendReply, refactor and more tests

- logicrunner/handle_executorresults.go
- logicrunner/handle_executorresults_test.go
- logicrunner/handle_init.go
* no need in procedure due to presense of WriteController
* add object field to logger
* cover with tests
> cleanup handle of ExecutorResults

- logicrunner/handle_still_executing.go
- logicrunner/logicrunner.go
- logicrunner/logicrunner_unit_test.go
- logicrunner/result_matcher.go
- logicrunner/result_matcher_mock.go
- logicrunner/result_matcher_test.go
* don't inject whole LR into ResultsMatcher, just required comps
* use less pointers, more values
* method couldn't return error, change signature
* add tests
> cleanup results matcher

- logicrunner/outgoingsender.go
- logicrunner/outgoingsender_test.go
- logicrunner/rpc_methods_test.go
How to  test:
```
$ INSOLAR_LOG_LEVEL=warn go test ./logicrunner -run '^TestLogicRunner/TestConcurrency$' -count=10000 -race -v &>2
$ cat 2 | grep 'go-actors/actor/mailbox/mailbox.go' | wc -l
0
```
> INS-3293 / INS-3371: stop OutgoingRequestSender

- Gopkg.lock
`dep ensure` adds this single line to Gopkg.lock which is a little annoying.
> NOISSUE: fix Gopkg.lock

- api/call_wrapper.go
Return err.Error() in json2.Error.Message, otherwise the real failure is hidden during execution of tests.
> INS-3465: return err.Error() in json2.Error.Message

- api/call_test.go
- api/contract.go
- api/functest_contract.go
- contractrequester/contractrequester.go
- contractrequester/contractrequester_test.go
- functest/logicrunner_test.go
- insolar/contractrequester.go
- ledger/light/proc/set_request_test.go
- logicrunner/goplugin/goplugintestutils/utils.go
- logicrunner/handle_init.go
- logicrunner/logicrunner_unit_test.go
- logicrunner/outgoingsender.go
- logicrunner/outgoingsender_test.go
- logicrunner/rpc_methods_test.go
- network/gateway/complete.go
- network/gateway/complete_test.go
- network/gateway/gateway_test.go
- testutils/contract_requester_mock.go
* ContractRequester methods are renamed: Call -> SendRequest,
SendRequest -> Call
* Returned back check for Reason/APINode
> INS-3449: Reason and APINode are mutually exclusive, now

- ledger/heavy/handler/handler.go
heavy use common func for sending error, not custom
Run tests
> NOISSUE: heavy update send error with code

- logicrunner/artifacts/client.go
- logicrunner/common/queue.go
- logicrunner/common/transcript.go
- logicrunner/executionbroker.go
- logicrunner/executionbroker_test.go
- logicrunner/executionregistry/execution_registry.go
- logicrunner/handle_pending_finished.go
- logicrunner/handle_still_executing.go
- logicrunner/logicrunner_unit_test.go
- logicrunner/requestsqueue/requests_queue_mock.go
- logicrunner/requestsqueue/requestsqueue.go
* when we first send PendingFinished we won't move our state (in some
situations) to InPending
* when OnPulse happens, sometime, we won't move our state to InPending,
too
* Added some more verbose logging
> NOISSUE: fix bug re bad PendingFinished and StillExecution messages

- Makefile
Changed `covermode` from `atomic` to `count`. This speeds up coverage tests a little bit.
> NOISSUE: change covermode from atomic to count

- insolar/flow/dispatcher/dispatcher.go
- insolar/flow/dispatcher/dispatcher_test.go
fixed flow log level fix for FlowCancelled
with test (but only for manual testing, because it is really hard to get into dispatcher interface)
run 
`go test ./insolar/flow/dispatcher -run TestDispatcher_Process_ReplyFlowCancelled -v`
and see only unfo message
> fix flow log level

- virtual/integration/main_test.go
Before that patch result of running virtual integration test was:
```
[ 09/23/19 | 14:09:20 ] $ go test -timeout 1200s -tags slowtest ./virtual/integration
flag provided but not defined: -test.testlogfile
Usage of /var/folders/9g/lwhn2csx7rn66b_rg_905wq00000gn/T/go-build606332186/b001/integration.test:
-verbose-wm
flag to enable watermill logging
FAIL    github.com/insolar/insolar/virtual/integration  0.021s
FAIL
```
Bug was re order of loading modules:
1) virtual functest (added `verbose-wm` and running `Parse` function), error was here due to absence of `test.testlogfile` command line argument
2) test.testlogfile and other arguments were added later in testing module
> NOISSUE: make virtual integration test to support go1.13

- logicrunner/rpc_methods.go
- logicrunner/rpc_methods_test.go
1) remove some useless code
2) add check for already processed outgoing requests
3) add check for Saga's outgoing requests with results (it must never happen)
write code and tests
run tests
> INS-3628_outgoing_deduplication no more double call of outgoing

- logicrunner/rpc_methods.go
- logicrunner/rpc_methods_test.go
If result for request already exist, we get virtual record from it and set it as result.
Run Jepsen test with kill_under_load case.
> INS-3639: return existed result as virtual record

- ledger/light/proc/ensure_index.go
- ledger/light/proc/ensure_index_test.go
- ledger/light/proc/proc.go
- ledger/light/proc/send_request_info.go
- ledger/light/proc/send_request_info_test.go
- ledger/object/index.go
- ledger/object/index_memory.go
- ledger/object/memory_index_modifier_mock.go
- ledger/object/memory_index_storage_mock.go
> INS-3656: Don't acquire object lock in ensureIndex and GetRequestInfo.

- docs/source/integration.rst
- docs/source/migration-test.rst
Removed obsolete TestNet 1.1 instructions
> [DOC] Remove obsolete TestNet 1.1 instructions

- functest/deposit_migration_test.go
fixed TestMigrationTokenDoubleSpend test
with logic
run test
original test could lead to temporary deadlock. Will deal with it later
> INS-3638: fix test

- logicrunner/execution_broker_i_mock.go
- logicrunner/executionbroker.go
- logicrunner/executionbroker_test.go
fetch at least one more time, it's possible that there is a logic
race between fetch, insert into ledger and setting flag.
If channel is not empty then we will start another fetch right away,
so it's sort of double commit
> don't flush ledgerHasMoreRequests when we had incomming during fetch

- logicrunner/executionbroker.go
- logicrunner/executionbroker_test.go
- logicrunner/handle_init.go
- logicrunner/logicrunner_unit_test.go
- logicrunner/requestsexecutor.go
fixed leaking goroutines in executionbroker tests
with leaktest
run tests
> INS-3633: fix in executionbroker tests leaking goroutines

- cmd/backupmanager/backupmanager.go
Write more logs (with timestamps) during `backupmanager merge`. It will help to measure how much time each step takes.
> INS-3679: write more logs (with timestamps) during `backupmanager merge`

- logicrunner/executionbroker.go
- logicrunner/executionbroker_test.go
- logicrunner/logicrunner_unit_test.go
- logicrunner/request_fetcher_test.go
- fixed goroutine test leak
- fixed TestExecutionBroker_AddFreshRequestWithOnPulse logic
> INS-2921: fixed leak in ImmutableOrder and fixed OnPulse tests behaviour

- scripts/insolard/bootstrap_template.yaml
10k shards should take 10GB of space for 1M users, way better
than 10TB with 10 shards
> increase number of shards we create by default

- testutils/launchnet/launchnet.go
increase wait timeout of network start up to 270 seconds
It's fast fix of tests
> INS-3691: increase wait timeout of network start up to 270 seconds

- functest/migration_shard_test.go
- logicrunner/builtin/contract/migrationadmin/migrationadmin.go
correct logic in getAddressCount with startWithIndex: now it return the rest of shard starting from startWithIndex
> INS-3709: fix-logic-in-getAddressCount-with-startWithIndex

- ledger/light/executor/filaments.go
fix concurrent map usage in filaments
> fix concurrent map usage in filaments

- application/api/requester/requester.go
- application/api/sdk/sdk.go
- application/cmd/benchmark/README.md
- application/cmd/benchmark/main.go
- application/cmd/insolar/add_migration_addresses.go
- application/cmd/insolar/free_migration_addresses.go
- cmd/apirequester/main.go
Added new keys to benchmark:
* `-R`: number of request retries if `ServiceUnavailable` error received
* `-P`: time to wait between retries (accepts go duration format: `0.5s`, `500ms`, `1m30s` etc.)
Run launchnet, kill `keeperd`, and run benchmark: `bin/benchmark -c=1 -r=1 -k=.artifacts/launchnet/configs/ -R=5 -P=0.5s`
> INS-3845: add retry on ServiceUnavailable in benchmark

- README.md
Update readme
**- Why I did it**
I use cmd from readme, but catch an error
```
bin/apirequester -k=.artifacts/launchnet/configs/ -u=http://127.0.0.1:19101/api
unknown shorthand flag: 'u' in -u=http://127.0.0.1:19101/api
Usage of bin/apirequester:
-a, --adminurls string    admin api url (default "http://localhost:19001/admin-api/rpc")
-k, --memberkeys string   path to dir with members keys
-p, --publicurls string   public api url (default "http://localhost:19101/api/rpc")
unknown shorthand flag: 'u' in -u=http://127.0.0.1:19101/api
```
update readme
> NOISSUE: update readme

- application/functest/bloat_test.go
- application/functest/change_loglevel_test.go
- application/functest/common_test.go
- application/functest/deposit_transfer_test.go
- application/functest/logicrunner_test.go
- application/functest/migration_shard_test.go
- application/functest/pressure_test.go
- application/functest/upload_contract_test.go
- application/testutils/launchnet/launchnet.go
Add env variable for functests, so we can run it without launch new insolar net:
INSOLAR_FUNC_RPC_URL - admin url (http://localhost:8001/admin-api/rpc)
INSOLAR_FUNC_RPC_URL_PUBLIC - public url  (http://localhost:8001/api/rpc)
INSOLAR_FUNC_KEYS_PATH - path to keys and configs (/tmp/jepsen-keys/)
Run tests.
> INS-3838: parametrization for functests

- insolar/pulse/db.go
Reduce prefetch of a lot of values in pulse db since we need only few of them
> Noissue reduce iterator prefetch un pulse db

- scripts/insolard/defaults/insolard.yaml
This suppose to fix `last finalized pulse falls behind too much. Stop node` during nightly functests run.
> INS-3925: use the same lightchainlimit as @ prod in launchnet.sh

- application/builtin/contract/deposit/deposit.go
- application/genesis/genesis.go
- ledger/heavy/integration/pulsefinalization_test.go
- ledger/heavy/integration/startstop_test.go
* Added restriction to deposit constructor that only allows creating a deposit if vesting period is a multiple of vesting step. To avoid creating deposits with "fractional" vesting steps.
* Refactored all errors handling in the deposit (`errors.Wrap()` instead of `fmt.Errorf`).
* Rewritten `canTransfer()` method in a clearer way.
> NOISSUE: deposit tweaks

- application/builtin/contract/deposit/deposit.go
this value shouldn't be negative, we have test for this in e2e/autotests
> INS-3929: when deposit is not yet confirmed then holdStartDate was negative

- ledger/light/executor/lightreplicator.go
I pushed `go` in the front of cleaner.Notify, just because It must work independently @nordicdyno 
> INS-3996 add go for the cleaner notifying call

- application/builtin/contract/migrationdaemon/migrationdaemon.go
- application/builtin/contract/wallet/wallet.go
- application/builtin/contract/wallet/wallet.wrapper.go
- application/builtin/proxy/wallet/wallet.go
Fixed race in case when two different migration daemons want to confirm deposit.
Both calls can didn't found deposit. And it will result a race in the AddDeposit to wallet step
New logic with method FindOrCreateDeposit will prevent it
> INS-4042: fix race logic in contract MigrationDaemon

- ledger/light/proc/get_request.go
removed log and updateJet message for virtual, because virtual always goes to latest executor and it should redirect to proper one
> INS-4033: remove updateJet because virtual goes to latest executor

- ledger/light/integration/abandoned_notification_test.go
- ledger/light/integration/getobject_test.go
- ledger/light/integration/jet_split_test.go
- ledger/light/integration/light_replication_test.go
- ledger/light/integration/light_test.go
- ledger/light/integration/requests_test.go
remove t.Parallel() from light's integration tests
> INS-4032: remove t.Parallel() from light's interation tests

- server/internal/heavy/components.go
Fortunately it's not used anywhere.
> INS-4087: dont inject badger in DI

- .github/workflows/tag.yaml
- Dockerfile
- What I did
Added release workflow to the repo
- How I did it
I've added Dockerfile and GH actions workflow pipeline which is being triggered by tag event.
Every tag event will trigger build, after that docker image will be created and pushed to docker registry and new GH release will be added to releases page, w/ binaries produced by build stage.
- Requirements
Those secrets should be added to the repo for workflow to work properly:
```
REGISTRY_URL
REGISTRY_USERNAME
REGISTRY_PASSWORD
```
- How to verify it
You can tag any commit with any tag name like that:
```
$ git tag -a 'v1.0.0' -m 'v1.0.0' 
$ git push origin v1.0.0
```
After steps above you should be able to download artifacts from release page and pull image from registry:
```
docker pull insolar/insolar:v1.0.0
```
- Description …
> GH actions release logic

- ledger/heavy/executor/finalize_pulse.go
- ledger/heavy/executor/metrics.go
measure backup time in `ns`, not in seconds
> backup often takes less than second

- scripts/insolard/launchnet.sh
This patch hides warning of `lsof` if Time Machine is running.
> NOISSUE: minor launchnet.sh fix

- Makefile
- scripts/dev/run-tests-with-repeat.sh
Scripts used in long and nightly TeamCity configurations partially added as a part of Makefile
> MN-127: move long and nightly CI test scripts to makefile

- ledger/object/postgres_index_db.go
- ledger/object/postgres_index_db_test.go
Fixed method UpdateLastKnownPulse of PostgresIndexDB
Changed `ON CONFLICT` clause of SQL script. Related changes are found in https://github.com/insolar/insolar-scripts/pull/10
Run unit test
Fixes MN-308
> MN-308: remove the pulse number from the conflict check

- ledger/heavy/exporter/metrics.go
- ledger/heavy/exporter/pulse_exporter_server.go
- ledger/heavy/exporter/record_exporter_server.go
send id for public observer(exchange-node) and split metrics
https://insolar.atlassian.net/browse/MN-314
send id in metadata and add tag in metrics
launch local Prometheus
change metric addTagsForExporterMethodTiming
and change  pulse and record server gRPC
> MN-314: split exporter metrics

- server/internal/heavy/components.go
- I've changed a metadata key. The correct key is 'authorization'.
> MN-486: fix metadata key to 'authorization'

- log/logmetrics/metrics.go
- log/logmetrics/metrics_helper.go
move metrics initialisation from init function to the constructor 
> Penv-344: move metrics initialisation from init function to the constructor 

- server/internal/heavy/components.go
- I have fixed the modification of the MD. Copy first, then set a new value.
> MN-567: copy a gRPC MD before setting a new value

- ledger/heavy/exporter/pulse_exporter_server.go
```
0 - current pulse
<65537  - genesis
>=65537 - pulse after requested
```
> PENV-347: way to retrieve genesis pulse

- ledger/heavy/exporter/pulse_exporter_server.go
Set correct prev pulse number for NextFinalizedPulse response (we need it for correct process of pulses on BE, if pulsar was down for some time)
> PENV-347: set correct prev pn

- go.mod
- go.sum
- server/internal/heavy/components.go
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/.gitignore
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/.travis.yml
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/CHANGELOG.md
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/LICENSE
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/README.md
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client.go
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_metrics.go
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_reporter.go
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/makefile
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/metric_options.go
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_reporter.go
- vendor/github.com/grpc-ecosystem/go-grpc-prometheus/util.go
- vendor/modules.txt
I have registered useful metrics of the gRPC server.
I have used the go-grpc-prometheus library, it adds counters and histograms via interceptors.
Run the Insolar network and monitoring, and see new metrics with the grpc_ prefix.
Note:
You can see a full list of new metrics here https://insolar.atlassian.net/browse/MN-632?focusedCommentId=23377
> MN-632: add metrics for a gRPC server

- server/internal/heavy/components.go
I have added interceptors for gRPC metrics in a case without auth.
> MN-632: fix gRPC server metrics

- configuration/exporter.go
- ledger/heavy/exporter/errors.go
- server/internal/heavy/components.go
- server/internal/heavy/components_validate_version_test.go
- server/internal/heavy/limits.go
- server/internal/heavy/limits_test.go
- I have added a configuration for rate-limiting into exporter configuration.
- I have added the 'ServerLimiter' structure, it stores limiters per method per client.
- I have added a temporary implementation of the Limiter interface that always allow execution.
In the next task, we can choose and start to use a suitable limiter implementation instead of the current mock limiter.
Linked PR: https://github.com/insolar/insolar-scripts/pull/14
> MN-714: add configuration and interceptors for rate limiting

- server/internal/heavy/components.go
- server/internal/heavy/components_auth_test.go
- server/internal/heavy/components_validate_version_test.go
- server/internal/heavy/limits.go
- server/internal/heavy/limits_test.go
I have placed rate-limiting interceptor after auth interceptors.
A nested map in limiters now correctly check and fill.
> MN-715: put rate-limiting interceptors after auth ones
