insolar/insolar

genesis/README.md, genesis/mock/storage/map_test.go, genesis/model/contract/smart_contract_test.go, genesis/model/factory/factory.go, genesis/model/object/proxy.go, genesis/model/object/reference_test.go, genesis/model/resolver/child.go, genesis/model/resolver/child_test.go, genesis/model/resolver/context.go, genesis/model/resolver/context_test.go, genesis/model/resolver/global.go, genesis/model/resolver/global_test.go, genesis/model/resolver/handler.go, genesis/model/resolver/handler_test.go, genesis/public/core/reference.go
Add ResolverHandler and move Proxy to object package
=> INS-35: add resolver handler

ledger/record/doc.go, ledger/record/record.go, ledger/record/request.go, ledger/record/types.go
Add record ID and PulseNum types. Also, have done some refactoring.
=> Ins 7 record types

ledger/storage/leveldb/leveldb_test.go, ledger/storage/storage_test.go
Added test stubs to ledger/storage and ledger/storage/leveldb packages.
=> INS-7: added test stubs

genesis/mock/storage/map.go, genesis/model/contract/smart_contract.go, genesis/model/contract/smart_contract_test.go, genesis/model/domain/domain.go, genesis/model/domain/domain_test.go, genesis/model/resolver/child.go, genesis/model/resolver/child_test.go, genesis/model/resolver/context.go, genesis/model/resolver/context_test.go, genesis/model/resolver/doc.go, genesis/model/resolver/global.go, genesis/model/resolver/global_test.go, genesis/model/resolver/handler.go, genesis/model/resolver/handler_test.go, genesis/model/resolver/interface.go, genesis/public/core/reference.go, genesis/public/core/reference_test.go
closes INS-34
Resolver interface now gets and returns interface{}
Add InitiateResolver to smart contract & domain
Add tests for InitiateResolver
Fix register method for reference domain
Fixes of tests for reference domain
Run tests
Add GlobalResolver instance
=> INS-34: global resolver

genesis/model/contract/smart_contract.go, genesis/model/contract/smart_contract_test.go, genesis/model/factory/doc.go, genesis/model/factory/factory.go, genesis/model/object/object.go, genesis/public/core/doc.go, genesis/public/core/instance.go, genesis/public/core/instance_test.go, genesis/public/core/reference.go, genesis/public/core/reference_test.go
- `Create` method of Factory and compositeFactory now returns error as second value
- Fix tests
- Fix docs
- Run tests
=> INS-64: factory create may return error

.travis.yml, Gopkg.lock, ledger/hash/doc.go, ledger/hash/hash.go, ledger/hash/hash_test.go, ledger/ledger_test.go, ledger/record/hash_test.go, ledger/record/record.go, ledger/record/record_test.go, ledger/record/request.go, ledger/record/result.go, ledger/record/serialize.go, ledger/record/serialize_test.go, ledger/record/testhelpers_test.go, ledger/record/types.go, ledger/storage/leveldb/leveldb.go, ledger/storage/storage.go, network/host/node/address.go
* Add records hashing and serialization/deserialization methods.
* Add some helper methods for manipulation on common storage types
* Add SHA3-224 hashing for storage records.
* Added SHA3-224 hashing for storage records.
* Added CBOR serialization/deserialization for records.
=> Ins-78 and Ins-53: records hashing and serialization 

.travis.yml, Makefile
=> Add Makefile with lint and test targets

.travis.yml
Added codecov export to travis
=> Code coverage

genesis/model/class/constant.go, genesis/public/core/class.go, genesis/public/core/class_test.go, genesis/public/core/doc.go, genesis/public/core/instance.go, genesis/public/core/instance_test.go, genesis/public/core/reference.go, genesis/public/core/reference_test.go
ClassDomain instance for storing new types of system with its proxy and factory
=> Ins-42 class domain

genesis/model/contract/smart_contract.go, genesis/model/contract/smart_contract_test.go, genesis/model/domain/domain_test.go, genesis/model/factory/doc.go, genesis/model/object/doc.go, genesis/model/object/object.go, genesis/model/object/reference.go, genesis/model/object/reference_test.go, genesis/model/resolver/child.go, genesis/model/resolver/child_test.go, genesis/model/resolver/context.go, genesis/model/resolver/context_test.go, genesis/model/resolver/global.go, genesis/model/resolver/global_test.go, genesis/model/resolver/handler.go, genesis/model/resolver/handler_test.go, genesis/public/core/instance.go, genesis/public/core/instance_test.go, genesis/public/core/reference.go, genesis/public/core/reference_test.go
closes INS-46
Make Reference an interface
Run tests
=> INS-46: reference as interface

ledger/storage/leveldb/leveldb_test.go
Fixed test cleaner for leveldb tests
=> NOISSUE: Fix leveldb test cleaner.

ledger/hash/hash.go, ledger/hash/hash_test.go, ledger/record/hash_test.go, ledger/record/record.go, ledger/record/request.go, ledger/record/result.go, ledger/record/serialize.go, ledger/record/types.go
I have rewritten the code of records hashing, a lot of uneccessary code have been removed as consequence. Some test and comments improvements added.
=> Ins 94 records hashing simplify

.golangci.yml, Makefile
=> NOISSUE: Add golangci config and fix makefile.

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/doc.go, ledger/artifactmanager/types.go, ledger/index/index.go, ledger/storage/leveldb/leveldb.go, ledger/storage/leveldb/leveldb_test.go, ledger/storage/storage.go
Closes INS-84
Implemented class actions in Artifact Manager
Run tests
Implemented basic interface for processing module interacting with storage
=> INS-84: Class actions

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/types.go, ledger/record/result.go, ledger/record/types.go
closes INS-80
Implemented arc preference method for artifact manager
=> INS-80: Add set architechture preference method to artifact manager

Gopkg.lock, ledger/storage/leveldb/leveldb.go, ledger/storage/leveldb/leveldb_test.go
closes INS-79
Implemented initial storage record creation
Run tests
=> INS-79: Add root record on DB init

Gopkg.lock, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/ledger_test.go, ledger/record/doc.go, ledger/record/record.go, ledger/record/request.go, ledger/record/result.go, ledger/record/serialize.go, ledger/record/serialize_test.go, ledger/record/types.go, ledger/storage/leveldb/error.go, ledger/storage/leveldb/leveldb.go, ledger/storage/leveldb/leveldb_test.go, ledger/storage/storage.go
* Implement get/set for records storage.
* Add helpers for encoding/decoding records
* Implement base storage methods.
=> Ins-1 read-write storage records

logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/girpc/girpc.go, logicrunner/goplugin/goplugin.go, logicrunner/goplugin/goplugin_test.go, logicrunner/goplugin/testplugins/secondary/main.go, logicrunner/logicrunner.go, logicrunner/types.go
We now can pass arguments from logicrunner to code we run as go plugins
=> Ins 108 goplugin method arguments

logicrunner/logicrunner.go, logicrunner/types_test.go
Make test system happy via covering packages with interfaces only
=> FIX: tests for package without code

network/host/dht_test.go
=> Deleted broken tests

logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/goplugin_test.go
we hit a few bugs in github.com/2tvenom/cbor and it's known to be
incomplete and outdated
=> INS-128: switch to CBOR from github.com/ugorji/go/codec

logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/goplugin_test.go
we think that returning interfaces should be prohibitted
as it's almost impossible to generate parsing into correct type on the
recieving side
=> INS-108: return values returned by contract's method call

genesis/example/wallet.go, genesis/example/wallet_test.go, genesis/model/class/constant.go
Add Base code for WalletDomain Proxy & Factory
=> Ins 105 make wallet domain proxy and factory

logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/goplugin.go
=> linter says goplugin.GoPluginRPC is butter.Buttery

logicrunner/goplugin/goplugin.go
controlling of duration of the timeout is left out and execution
cancelation is a TODO
=> INS-127: simplest timeout on code execution in ginsider

genesis/model/object/reference.go, genesis/model/object/reference_test.go, genesis/model/resolver/doc.go, genesis/model/resolver/reference_container.go, genesis/model/resolver/reference_container_test.go, genesis/public/core/reference.go
- Reference wrapped up into ReferenceContainer
- Run tests
=> Ins 148 reference container

README.md
Just clickable code coverage badge in README
Click on it
=> codecov.io badge in README.md

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptor_class_test.go, ledger/artifactmanager/descriptor_object_test.go, ledger/storage/leveldb/leveldb.go, ledger/storage/leveldb/leveldb_test.go
Closes INS-165
Refactored artifact manager and descriptor tests to use leveldb storage
Run tests
=> Ins 165 mock to level

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptor_class.go, ledger/artifactmanager/descriptor_object.go, ledger/record/record_test.go, ledger/record/result.go, ledger/storage/leveldb/leveldb.go
=> NOISSUE: Fix linter issues.

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/record/record.go, ledger/record/request.go, ledger/record/result.go, ledger/storage/leveldb/leveldb.go
Closes INS-186
Added domain to artifact manager methods
=> INS-186: Require domain from artifact manager client

messagerouter/messagerouter.go, messagerouter/messagerouter_test.go, network/host/dht.go
messagerouter.Route method which uses DHT network to deliver and run messages on reference node
using Serialization\Deserialization to network RPC
tests with real network DHT node
=> Ins 190 messagerouter network integration

cmd/example/network/host/main.go, messagerouter/messagerouter.go, messagerouter/messagerouter_test.go, network/host/context.go, network/host/dht.go, network/host/dht_test.go, network/host/id/id.go, network/host/id/id_test.go, network/host/message/builder_test.go, network/host/message/message.go, network/host/message/message_test.go, network/host/node/node.go, network/host/node/node_test.go, network/host/node/origin.go, network/host/node/origin_test.go, network/host/relay/relay.go, network/host/relay/relay_test.go, network/host/routing/hashtable.go, network/host/routing/hashtable_test.go, network/host/routing/routeset.go, network/host/routing/routeset_test.go, network/host/routing/routing_test.go
Extend network id with pub key
Changed data type of id.ID.
See id_test.go
Now id.ID is a struct with two fields - Hash and Key. Hash is a 20-byte hash of the key.
=> Ins 191 extend network id with pub key

messagerouter/doc.go, messagerouter/messagerouter.go, messagerouter/messagerouter_test.go, network/host/dht.go
Go Report Card fixes for network module
=> INS-190 messagerouter network integration

ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptor_class_test.go, ledger/artifactmanager/descriptor_object_test.go, ledger/artifactmanager/errors.go, ledger/jetcoordinator/create_drop_test.go, ledger/ledger.go, ledger/ledger_test.go, ledger/record/record.go, ledger/record/serialize.go, ledger/storage/leveldb/internals_test.go, ledger/storage/leveldb/iterate.go, ledger/storage/leveldb/iterate_test.go, ledger/storage/leveldb/leveldb.go, ledger/storage/leveldb/leveldb_test.go, ledger/storage/leveldb/leveltestutils/testutils.go, ledger/storage/leveldb/options.go
* Add methods in LevelDB for iteration over records of one pulse.
* code and tests refactoring
* Add methods in LevelDB for iteration over records of one pulse.
=> Ins-132: get all records in block

ledger/hash/hash.go, ledger/jetcoordinator/create_drop.go, ledger/jetcoordinator/create_drop_test.go, ledger/jetcoordinator/jetcoordinator.go, ledger/jetdrop/jetdrop.go, ledger/jetdrop/jetdrop_test.go, ledger/jetdrop/serialize.go, ledger/ledger_test.go, ledger/record/serialize.go, ledger/storage/leveldb/leveldb.go, ledger/storage/leveldb/leveldb_test.go, ledger/storage/storage.go
Add new jet drop logic.
* store only jetdrop hash (hash on all records hashes)
instead of all hashes of all record for current block
* use iteration on keys for hash calculation
* relay on keys sort order in database
(LevelDB should provide sorted keys)
* refactor code and tests
=> Ins-133: calculate and save jet block.

.travis.yml
Added Go 1.11.x in travis config file.
=> NOISSUE: add go 1.11.x in travis configuration

README.md
add CII Best Practices Badge (https://bestpractices.coreinfrastructure.org/en)
=> INS-232: add CII Best Practices Badge

.codecov.yml
=> set reasonable coverage value

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptor_class_test.go, ledger/artifactmanager/descriptor_object_test.go, ledger/jetcoordinator/create_drop_test.go, ledger/jetcoordinator/jetcoordinator.go, ledger/ledger.go, ledger/storage/leveldb/iterate_test.go, ledger/storage/leveldb/leveldb.go, ledger/storage/leveldb/leveldb_test.go, ledger/storage/storage.go
Closes INS-235
Added entropy storage methods
Run tests
=> INS-235 entropy

network/nodenetwork/node.go, network/nodenetwork/node_test.go
=> hottest fix node tests

.github/CONTRIBUTING.md, README.md
Add Contributing Guidelines as separate file in .github directory.
Added Contributing Guidelines to meet CII Best Practices.
=> Add basic contribution guidelines

core/record.go
=> NOISSUE: Remove methods from core package.

logicrunner/goplugin/preprocessor/main.go, logicrunner/goplugin/preprocessor/templates/proxy.go.tpl
closes INS-220
Add template for proxy generation
Run tests
=> INS-220: template for proxy

configuration/configuration.go, configuration/hostnetwork.go, configuration/ledger.go, core/ledger.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptor_class.go, ledger/artifactmanager/descriptor_class_test.go, ledger/artifactmanager/descriptor_object.go, ledger/artifactmanager/descriptor_object_test.go, ledger/jetcoordinator/jetcoordinator.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/ledger.go, ledger/storage/leveldb/internals_test.go, ledger/storage/leveldb/iterate.go, ledger/storage/leveldb/iterate_test.go, ledger/storage/leveldb/leveldb.go, ledger/storage/leveldb/leveldb_test.go, ledger/storage/leveldb/leveltestutils/testutils.go, messagerouter/messagerouter_test.go, network/hostnetwork/hostnetwork.go, network/hostnetwork/hostnetwork_test.go, network/hostnetwork/transport/kcptransport.go, network/hostnetwork/transport/utptransport.go, network/nodenetwork/node_test.go
Closes INS-241
Created global ledger handler.
=> INS-241: Add global ledger gateway.

Gopkg.lock
=> NOISSUE: fix lockfile version

core/artifactmanager.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/record/result.go, ledger/record/serialize.go
Closes INS-240
Added type record and methods for creating them in artifact manager
Run tests
=> INS-240 type record

logicrunner/goplugin/preprocessor/main.go, logicrunner/goplugin/preprocessor/main_test.go
Wrapper and Proxy Generator: Support bool params in contract methods
Run tests
=> Ins 254 support bool param type in code generator

logicrunner/goplugin/preprocessor/main.go, logicrunner/goplugin/preprocessor/main_test.go, logicrunner/goplugin/preprocessor/templates/wrapper.go.tpl
Preprocessor: add supporting of method with no return values
Run tests
=> INS-253: add supporting of method with no return value

genesis/experiment/allowance/allowance.go, genesis/experiment/member/member.go, genesis/experiment/wallet/wallet.go, logicrunner/goplugin/goplugin_test.go, logicrunner/goplugin/preprocessor/main.go, logicrunner/goplugin/preprocessor/main_test.go, logicrunner/goplugin/testplugins/primary/primary.go, logicrunner/goplugin/testplugins/secondary/main.go
Determine contract by embedding of BaseSmartContract instead of @inscontract
Run tests
=> INS-249: determine contract by embedding of BaseSmartContract

logicrunner/goplugin/goplugin_test.go, logicrunner/goplugin/preprocessor/main.go, logicrunner/goplugin/preprocessor/main_test.go, logicrunner/goplugin/preprocessor/templates/proxy.go.tpl
closes INS-250
Add flag "code-reference" to generate proxy command
Run tests
=> INS-250: add flag to set class ref

logicrunner/goplugin/preprocessor/_real_contracts_test.go, logicrunner/goplugin/preprocessor/main_test.go
=> INS-250: fix new tests

configuration/configuration.go, configuration/logicrunner.go, core/boostraping.go, core/vm.go, logicrunner/builtin/builtin.go, logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/goplugin.go, logicrunner/goplugin/goplugin_test.go, logicrunner/goplugin/rpctypes/rpctypes.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, messagerouter/messagerouter_test.go
**Make logicrunner configurable and runnable from main bootstraping system**
Now we have core.Component interface with start and stop methods. Logicrunner implements it.
=> Ins 265 startup

core/artifactmanager.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go
Closes INS-287
Implemented GetCode method
Run tests
=> [AFTER INS-284] INS-287 get code

logicrunner/logicrunner.go, logicrunner/logicrunner_test.go
Acquired ArtifactManager from Ledger in LogicRunner. Not from core.Components.
=> Ins 294 ledger in logic runner

cmd/insolar/ledger.go, cmd/insolar/main.go, configuration/configuration.go, ledger/ledger.go, ledger/storage/storage.go
* add ledger initialization and teardown code in cmd
* extend Ledger and Store interfaces to support graceful stop.
* add ledger initialization and teardown code in cmd
=> INS-292: add ledger to binary

core/messagerouter.go, messagerouter/messagerouter.go, messagerouter/messagerouter_test.go, network/servicenetwork/servicenetwork.go
**Make MessageRouter an core.Component and fix mess in repo**
=> INS-263: Make MessageRouter an core.Component and fix mess in repo

cmd/insolar/stats.go, core/messagerouter.go, logicrunner/builtin/builtin_test.go, logicrunner/builtin/helloworld/helloworld.go
=> NOISSUE: add missing copyrights

configuration/logicrunner.go, logicrunner/builtin/builtin.go, logicrunner/builtin/builtin_test.go, logicrunner/goplugin/goplugin.go, logicrunner/goplugin/goplugin_test.go, logicrunner/logicrunner.go
**Start LogicRunner Executor if it presented in configuration**
=> INS-265: Start of executors based on config

core/artifactmanager.go, ledger/artifactmanager/artifactmanager.go
=> NOISSUE: Update artifact manager docs.

core/artifactmanager.go, core/vm.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/descriptors.go, ledger/artifactmanager/descriptors_test.go, ledger/record/record_test.go, ledger/record/result.go, logicrunner/goplugin/goplugin.go, logicrunner/goplugin/testutil/utils.go
Closes INS-298
Made GetCode return machine type.
Run tests
=> INS-298: Return machine type from GetCode.

ledger/storage/drop_test.go, ledger/storage/storage_test.go, ledger/storage/store.go, ledger/storage/transaction.go
now Store.SetDrop waits for complete all update transactions what runs via TransactionManager
run test `go test -v ./ledger/storage/. -run=DropWaitWrites`
safe mechanism for Jet drop save
=> Ins-267: stop on drop

core/artifactmanager.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, logicrunner/goplugin/testutil/utils.go
Closes INS-302
Implemented GetLatestClass method on artifact manager.
Run tests
=> INS-302 latest class

cmd/insolar/main.go, configuration/configuration.go, configuration/configuration_test.go
fixed bug with load configuration from env
separated method for LoadEnv
unit test, manual test with docker compose
=> INS-311 configuration load env config bugfix

core/artifactmanager.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/index/index.go, ledger/ledger.go, ledger/record/result.go, ledger/storage/db.go, logicrunner/builtin/builtin_test.go, logicrunner/goplugin/goplugin.go, logicrunner/goplugin/testutil/utils.go
Closes INS-304
Implemented children mechanics and root record bootstrap.
Run tests
=> INS-304: Add parents to records. Add root record bootstrap.

logicrunner/goplugin/preprocessor/main_test.go
=> INS-259: fixes

core/messagerouter.go, core/network.go, logicrunner/goplugin/goplugin.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, messagerouter/message/base.go, messagerouter/message/callconstructor.go, messagerouter/message/callmethod.go, messagerouter/messagerouter.go, messagerouter/messagerouter_test.go, network/servicenetwork/servicenetwork.go
**core.Message now an interface that hides family of message classes**
=> INS-263: make message an interface

configuration/ledger.go, ledger/ledger.go, ledger/storage/db.go, ledger/storage/errors.go, ledger/storage/storagetest/utils.go, ledger/storage/transaction.go, ledger/storage/transaction_test.go
Add transactions retry logic, configuration and tests for.
Run tests.
better support of concurrent transactions.
=> Ins-268: transactions retries

core/artifactmanager.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/errors.go, ledger/index/index.go, ledger/record/result.go, logicrunner/goplugin/testutil/utils.go
Closes INS-305
Implemented delegate methods.
Run tests
=> INS-305, INS-306 delegates and children

logicrunner/builtin/builtin.go, logicrunner/builtin_test.go, logicrunner/goplugin/testutil/utils.go
**Improve testing utils**
**Builtin uses names of packages as code on ledger**
=> INS-242: Tidy up tests

core/artifactmanager.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptors.go, ledger/artifactmanager/descriptors_test.go, ledger/index/index.go, ledger/storage/storage_test.go, logicrunner/goplugin/testutil/utils.go
=> NOISSUE: Remove redundant AM methods.

core/jetcoordinator.go
**interface core.JetCoordinator**
=> Start of jetcoordinator

README.md, configuration/README.md, network/hostnetwork/README.md
Write configuration package readme doc
Write paragraph about Host Network configuration
=> INS-279-configuration-network-readme

ledger/ledger.go, ledger/ledgertestutil/doc.go, ledger/ledgertestutil/ledgertestutil.go, logicrunner/builtin_test.go
add ledgertestutil.TmpLedger helper for share in tests
=> Ins-291: ledger test utils

.gitignore, core/artifactmanager.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptors.go, logicrunner/goplugin/testutil/utils.go
=> INS-385: Add children iterator to artifact manager.

.travis.yml
* set GOMAXPROCS to 2 in Travis config (try to control the  level of parallelism)
* set GORACE="halt_on_error=1" - the try to understand how it could be useful
=> travis ci config improvements

configuration/log.go, core/logger.go, log/doc.go, log/log.go, log/log_test.go, log/logrus.go, log/sourceinfo.go
Logger adapter for logrus
core interface and adapter implementation.
unit tests
=> INS-340-logger-adapter

cmd/insolard/main.go, cmd/pulsard/main.go, configuration/configuration.go, configuration/pulsar.go, pulsar/entropygenerator.go, pulsar/entropygenerator_test.go, pulsar/pulsar.go, pulsar/pulse.go, pulsar/pulse_test.go
I created a draft prototype of the pulsar. In the nearest future I am going to extend it and remove some mock code like `handleRequest`
Pulsar's prototype
=> Ins 373 pulsar daemon

logicrunner/goplugin/preprocessor/real_contracts_test.go, logicrunner/goplugin/testutil/utils.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go
**Contract builder is reenterable now**
=> INS382: Creating childs

core/pulse.go, network/cascade/cascade.go, network/cascade/cascade_test.go, network/hostnetwork/dht.go, network/hostnetwork/dht_test.go, network/hostnetwork/hostnetwork.go, network/hostnetwork/hostnetwork_test.go, network/hostnetwork/packet/packet.go, network/hostnetwork/packet/request.go, network/hostnetwork/packet/response.go, network/nodenetwork/nodenetwork.go, network/servicenetwork/servicenetwork.go, pulsar/entropygenerator.go, pulsar/pulse_test.go
Implemented cascade sending feature
run tests in cascade package
=> Ins 310 cascade send

genesis/experiment/rootdomain/rootdomain.insgoc, genesis/experiment/wallet/wallet.insgoc, logicrunner/goplugin/foundation/foundation.go, logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/goplugin.go, logicrunner/goplugin/preprocessor/templates/proxy.go.tpl, logicrunner/goplugin/proxyctx/proxyctx.go, logicrunner/goplugin/rpctypes/rpctypes.go, logicrunner/goplugin/testutil/utils.go, logicrunner/logicrunner_test.go
=> Ins 407 get implementation for method

ledger/jetcoordinator/jetcoordinator.go, ledger/jetcoordinator/jetnode.go
=> INS-384: Add method for getting jet ref from record ref.

configuration/logicrunner.go, logicrunner/goplugin/goplugin.go
Fix config param for proper binary Start()
=> INS-405: config default values

.gitignore, configuration/testdata/changed.yml, configuration/testdata/default.yml, configuration/testdata/invalid.yml
=> HOTFIX: fix config testdata

genesis/experiment/rootdomain/rootdomain.insgoc, genesis/experiment/wallet/wallet.insgoc, logicrunner/goplugin/foundation/foundation.go, logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/goplugin.go, logicrunner/goplugin/proxyctx/proxyctx.go, logicrunner/goplugin/rpctypes/rpctypes.go, logicrunner/goplugin/testutil/utils.go, logicrunner/logicrunner_test.go
**Iterate over contract children refs**
childs, err := c.GetChildrenTyped(child.GetClass())
for _, chref := range childs {
o := child.GetObject(chref)
}
=> Ins 382 iterate childs

genesis/experiment/rootdomain/rootdomain.insgoc
- SendMoney calls Transfer with member reference
- getUserInfoMap returns map with values
=> INS-409: root domain fixed

ledger/storage/transaction_test.go
fix of flaky ledger transaction tests
complete refactor tests code, use the same transactions conflict scenario
in all tests without relation on time-based events
=> NOISSUE: try to fix flaky ledger transaction tests

core/ledger.go, core/pulse.go, core/record.go, ledger/artifactmanager/artifactmanager_test.go, ledger/jetcoordinator/jetcoordinator.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/jetcoordinator/jetnode.go, ledger/jetcoordinator/utils.go, ledger/ledger.go, ledger/pulsemanager/doc.go, ledger/pulsemanager/pulsemanager.go, ledger/record/record.go, ledger/record/record_test.go, ledger/record/result.go, ledger/record/serialize.go, ledger/record/testhelpers_test.go, ledger/storage/db.go, ledger/storage/iterate.go, ledger/storage/iterate_test.go, ledger/storage/storage_test.go, ledger/storage/transaction.go, ledger/storage/utils_test.go
=> INS-410: Add pulse manager. Move pulse related types to core.

network/hostnetwork/hostnetwork.go, network/hostnetwork/id/id.go, network/hostnetwork/id/id_test.go, network/nodenetwork/nodenetwork.go
=> NOISSUE: fix host id generation

bootstrap/bootstrap.go, configuration/apirunner.go, messagerouter/message/base.go, messagerouter/message/delegate.go, messagerouter/messagerouter.go
=> Noissue make binary work

api/main_test.go, api/request_handler.go
=> INS-428: fix dump user handler

logicrunner/goplugin/goplugin.go, logicrunner/logicrunner.go, messagerouter/message/base.go, messagerouter/message/child.go
We need this in order to move data from virtual executer to material
one for data to be saved. We know that this message is similar to
DelegateMessage, no difference at all, but we believe it's fine
=> INS-427: ChildMessage

api/main.go, api/main_test.go, api/query_params.go, api/request_handler.go, api/serialization.go, configuration/apirunner.go, messagerouter/messagerouter.go
=> INS-432: fix linter warnings in api

ledger/ledgertestutil/ledgertestutil.go, ledger/storage/storagetest/utils.go, logicrunner/goplugin/testutil/utils.go, logicrunner/logicrunner_test.go
=> Benchmark for contract calling

cmd/insolar/main.go
Add tool to gen default config
=> INS-438: add tool to gen default config

ledger/storage/db.go
=> NOISSUE: Fix bootstrap ledger.

configuration/ledger.go, core/ledger.go, ledger/jetcoordinator/jetcoordinator.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/jetcoordinator/utils.go, ledger/pulsemanager/pulsemanager_test.go, ledger/storage/db.go, ledger/storage/storagetest/utils.go, messagerouter/messagerouter.go
=> INS-386 jet cordinator

messagerouter/messagerouter.go
=> HOTFIX: merge error

network/hostnetwork/dht.go, network/hostnetwork/requesthandler.go
Documentation for packet manager, packet handler, request handler, response handler and small code fixes
see https://insolar.atlassian.net/wiki/spaces/DEV/pages/160366632/DHT+Components
=> INS 347 DHT doc

api/main.go
use common logger instead of logrus
=> INS-420: use common logger

network/cascade/cascade.go, network/hostnetwork/dht_test.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/servicenetwork_test.go
Added integration tests for cascade message sending
Run tests in servicenetwork_test.go
=> INS-402: cascade tests

messagerouter/messagerouter.go
=> NOISSUE: add cascade message send

cmd/insgocc/insgocc.go
- added spf23/cobra to insgocc
=> INS-301: spf23/cobra arrived

ledger/storage/db.go, ledger/storage/errors.go, ledger/storage/storage_test.go, ledger/storage/transaction.go
add storage.ErrOverride error on attempt to write in Record in storage.SetRecord method
added protection on records override on storage level
=> Ins-462: deny record override

bootstrap/bootstrap.go, core/network.go, network/servicenetwork/servicenetwork.go
closes INS-441
Bootstrap creates new rootDomain only if there isn't already one
=> INS-441: bootstrap check root domain existence

core/record.go, genesis/experiment/rootdomain/rootdomain.insgoc, ledger/jetcoordinator/jetcoordinator.go, ledger/jetcoordinator/jetcoordinator_test.go, logicrunner/artifactmanager_test.go, logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/goplugin.go, logicrunner/goplugin/preprocessor/main_test.go, logicrunner/goplugin/preprocessor/templates/proxy.go.tpl, logicrunner/logicrunner_test.go, messagerouter/messagerouter_test.go, network/cascade/cascade_test.go, network/nodenetwork/nodenetwork.go, network/nodenetwork/nodenetwork_test.go, network/servicenetwork/servicenetwork_test.go, toolkit/go/foundation/foundation.go
Renamed String2Ref to NewRefFromBase58
Shift+F6
=> INS-449: rename String2Ref to NewRefFromBase58

core/ledger.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptors.go, logicrunner/goplugin/testutil/utils.go
Closes INS-459
Used descriptors in AM methods.
Implemented missing methods in descriptors for internal usage.
Run tests
=> INS-459: Use descriptors in AM.

api/main_test.go, api/request_handler.go, core/eventbus.go, core/vm.go, eventbus/event/base.go, eventbus/event/callconstructor.go, eventbus/event/callmethod.go, eventbus/event/child.go, eventbus/event/delegate.go, eventbus/event/getobject.go, eventbus/event/handles.go, eventbus/event/updateobject.go, eventbus/eventbus.go, eventbus/eventbus_test.go, eventbus/reaction/base.go, eventbus/reaction/common.go, eventbus/reaction/objectbody.go, eventbus/response/base.go, logicrunner/builtin_test.go, logicrunner/goplugin/goplugin.go, logicrunner/goplugin/rpctypes/rpctypes.go, logicrunner/goplugin/testutil/messagerouter.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, pulsar/pulsar.go
=> INS-453: Event reactions

configuration/configuration.go, configuration/configuration_test.go, core/logger.go, ledger/hash/hash_test.go, ledger/storage/db.go, ledger/storage/drop_test.go, ledger/storage/iterate_test.go, ledger/storage/transaction_test.go, log/log.go, log/log_test.go, log/logrus.go
* improve logger configuration on startup and refactor logger tests
* use global logger in ledger's code
=> Ins 419 ledger logs

ledger/storage/drop_test.go
simplify storage DropWaitWrites test, try to stabilize it in CI environments
it should not fail in CI (appveyor, travis)
=> NOISSUE: simplify storage DropWaitWrites test, try to stabilize it

cmd/insolar/main.go
=> INS-476: new command for insolar binary

network/hostnetwork/packet/packet.go, network/hostnetwork/packet/packet_test.go, network/hostnetwork/packet/request.go, network/hostnetwork/packet/response.go, network/hostnetwork/packethandler.go, network/hostnetwork/packethandler_test.go, network/hostnetwork/packetmanager.go, network/hostnetwork/routing/hashtable.go, network/hostnetwork/routing/hashtable_test.go, network/servicenetwork/servicenetwork_test.go
Added handle that returns N random hosts for the pulsars
Currently it returns first N hosts from the DHT routing table
Run tests
=> INS-375: get random DHT hosts

functest/.insolar.yaml, functest/main_test.go
closes INS-360
Add func tests for check insolard binary work
Run tests
=> INS-360: positive func test

logicrunner/goplugin/testutil/utils.go
=> NOISSUE: fix func tests

logicrunner/goplugin/preprocessor/real_contracts_test.go
Fix TestCompilingRealSmartContracts on mac os
=> NOISSUE: fix iccDir path

configuration/logicrunner.go, logicrunner/goplugin/ginsider-cli/main.go, logicrunner/goplugin/goplugin.go
- Creating temporary directory for cached code dir and emptying it if not set in config
=> INS-442: clear cachedCode dir

.travis.yml
use debug level for logs in CI
=> use debug level for logs in CI

Gopkg.toml
=> INS-498: ugorji/go updated

api/main.go, api/main_test.go, bootstrap/bootstrap.go, cmd/insolard/main.go, core/components.go, eventbus/event/handles.go, eventbus/event/ledger.go, eventbus/eventbus.go, eventbus/eventbus_test.go, ledger/artifactmanager/artifactmanager.go, logicrunner/artifactmanager_test.go, logicrunner/builtin_test.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, metrics/metrics_test.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/servicenetwork_test.go
Use struct for core components registry
refactoring init code and tests
tests should pass
=> INS-474: define components as struct instead map

.gitignore, .travis.yml, Makefile, network/hostnetwork/packet/packettype_string.go
One makefile to build all insolar binaries
See changes in Makefile and .travis.yml
Run _make_ with one of the options: lint, clean, install-deps, install, build, test, test_with_coverage
=> INS-491: makefile

Gopkg.lock
=> INS-498: Gopkg.lock updated

network/hostnetwork/dht.go, network/hostnetwork/hosthandler/hosthandler.go, network/hostnetwork/packet/packet.go, network/hostnetwork/store/key.go, network/hostnetwork/store/key_test.go
Fixed all network warnings from golangCI
Try to start golangCI linters
=> INS-494: Goreport fix

cmd/insolard/main.go
Make all components stop after start again
Add log for diagnostic reasons
=> NOISSUE: update stop component condition and add log

bootstrap/bootstrap.go, functest/.insolar.yaml, functest/main_test.go, logicrunner/goplugin/testutil/utils.go
closes INS-488
Wrap errors in func tests prestart routine
Add some logs
Print stderr of insolard
Run tests
=> INS-488: cool error messages in func tests

Makefile, cmd/insolar/main.go, cmd/insolard/main.go, cmd/pulsard/main.go, metrics/metrics.go, version/doc.go, version/version.go
Display information about version and build params
package version
makefile ldflags
manual test
=> INS-353: show version

network/hostnetwork/context.go, network/hostnetwork/dht.go, network/hostnetwork/host/address.go, network/hostnetwork/host/origin.go, network/hostnetwork/hostnetwork.go, network/hostnetwork/packet/packet.go, network/hostnetwork/packethandler.go, network/hostnetwork/requesthandler.go, network/hostnetwork/resolver/resolver.go, network/hostnetwork/resolver/stun.go, network/hostnetwork/responsehandler.go, network/hostnetwork/transport/base.go, network/hostnetwork/transport/kcp.go, network/hostnetwork/transport/transport.go, network/hostnetwork/transport/utp.go, network/servicenetwork/servicenetwork.go
Errors was wrapped in network subsystem
errors.Wrap()
tests pass
=> INS-472: network errors wrap

core/ledger.go, eventbus/event/base.go, eventbus/event/ledger.go, eventbus/reaction/base.go, eventbus/reaction/ledger.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/descriptors.go
=> INS-484: Update docs.

ledger/jetcoordinator/jetnode.go
Closes INS-526
Made JC calculate role from affinity ref.
=> INS-526: Calculate jet affinity from affinity part of the ref.

configuration/ledger.go, core/ledger.go, core/pulse.go, eventbus/reaction/ledger.go, ledger/artifactmanager/descriptors.go, ledger/artifactmanager/handler.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/jetcoordinator/jetnode.go, ledger/ledger.go, ledger/pulsemanager/pulsemanager.go
=> NOISSUE: add godoc to ledger code, make goreportcard happier

network/hostnetwork/mockutils.go
fixed data race in servicenetwork tests
run tests in servicenetwork_test.go
=> NOISSUE: fix data race in servicenetwork tests

core/eventbus.go, core/vm.go, eventbus/event/base.go, eventbus/event/callconstructor.go, eventbus/event/callmethod.go, eventbus/event/handles.go, eventbus/eventbus_test.go, logicrunner/casebind.go, logicrunner/goplugin/foundation/foundation.go, logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/preprocessor/main.go, logicrunner/goplugin/preprocessor/templates/wrapper.go.tpl, logicrunner/goplugin/testutil/messagerouter.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, logicrunner/service.go
**We use gls for propagating CallContext and CaseBind magically start works**
=> Ins 533 glscontext

core/message/base.go, core/message/ledger.go, core/message/logicrunner.go, core/messagebus.go, core/reply/base.go, core/reply/ledger.go, core/vm.go, logicrunner/goplugin/testutil/messagerouter.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, messagebus/messagebus_test.go
**calm disturbances after refactoring of MessageRouter**
=> NOISSUE: hide difference between logicmessage and message

ledger/ledgertestutil/ledgertestutil.go, ledger/record/result.go
=> NOISSUE: FIx goreport.

logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/preprocessor/templates/wrapper.go.tpl
**simplier contract code calling**
=> NOISSUE: use proxyctx.Current in wrappers

ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/index/index.go, ledger/record/result.go, ledger/storage/db.go, ledger/storage/storage_test.go, ledger/storage/store.go, ledger/storage/transaction.go
Closes INS-558
Refactored storage to use ID as key.
Run tests
=> INS-558: Refactor storage to use ID as key.

.gitignore, .goreleaser.yml
=> INS-418: GoReleaser

api/main_test.go, core/ledger.go, core/message/base.go, core/message/ledger.go, core/messagebus.go, core/reply/ledger.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptors.go, ledger/artifactmanager/handler.go, ledger/index/index.go, ledger/ledgertestutil/ledgertestutil.go, ledger/record/generic.go, ledger/record/meta.go, ledger/record/record.go, ledger/record/request.go, ledger/record/result.go, ledger/record/serialize.go, logicrunner/goplugin/testutil/utils.go, logicrunner/logicrunner_test.go, messagebus/messagebus.go
Closes INS-564
Made activate object make records in parents lifeline
Run tests.
=> INS-564. Child activate

functest/register_node_test.go, functest/utils_test.go
Add functional tests for register_node API query type
Run tests
=> INS-546: register node func tests

Gopkg.lock, core/message/logicrunner.go, core/vm.go, ledger/storage/drop_test.go, logicrunner/casebind.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, logicrunner/service.go, messagebus/messagebus_test.go
**Now we have validation of a series of contract execution**
See ValidateAllResults() in logicrunner_test.go
=> Ins 312 validation

api/main.go, api/query_params.go, api/request_handler.go, api/seedmanager/seedgenerator.go, api/seedmanager/seedmanager.go, functest/get_seed_test.go, functest/utils_test.go, scripts/insolard/launch.sh
1) Add seed pool
2) Add get_seed request to api
Run tests
=> INS-540: add seedmanager

genesis/bootstrapcertificate/testdata/cert.json
=> Test was broken after refactoring of package cryptohelpers

network/consensus/consensus.go
=> NOISSUE: fix consensus interface

core/record.go, cryptohelpers/ecdsa/ecdsa.go, cryptohelpers/hash/hash.go, genesis/bootstrapcertificate/testdata/cert.json, ledger/jetcoordinator/utils.go, ledger/storage/db.go, ledger/storage/transaction.go, pulsar/pulsarhelpers.go
- switch back on sha3-256 hash in certs signing
- refactor helper names
=> Ins 579 fix sign hash algo

.gitignore, bootstrap/bootstrap.go, cmd/insolar/main.go, configuration/bootstrap.go, configuration/configuration.go, functest/.insolar.yaml, functest/main_test.go, genesis/experiment/rootdomain/rootdomain.go, genesis/proxy/rootdomain/rootdomain.go, logicrunner/logicrunner_test.go, scripts/insolard/insolar.yaml, scripts/insolard/launch.sh
- bin/insolar generates keys for root member
- bootstrap creates root member and his wallet
- removed setRoot from rootDomain contract
- fixed tests
=> INS-596: root member creating

ledger/jetcoordinator/jetcoordinator_test.go, ledger/pulsemanager/pulsemanager_test.go, pulsar/pulsar_integration_test.go
**i broken the tests, i'm sorry*
=> FIX: Ledger tests

Makefile, genesis/proxy/member/member.go
**Proxy tests are fixed, also, we have new make target named regen_proxyes**
=> FIX: make proxy generator for test

bootstrap/bootstrap.go, core/ledger.go, core/message/base.go, core/message/bootstrap.go, core/message/ledger.go, core/message/logicrunner.go, core/messagebus.go, core/record.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/record/meta.go, ledger/record/result.go, ledger/record/serialize.go, ledger/storage/db.go, logicrunner/builtin_test.go, logicrunner/goplugin/testutil/utils.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, logicrunner/service.go
Closes INS-470
Made request objects head.
Run tests.
Request is now objects head.
=> INS-470 request head

logicrunner/logicrunner_test.go
=> FIX: do not use real case bind records in tests

Makefile
=> TEMP: do not check race on tests

network/consensus/base.go, network/consensus/base_test.go
fix race bug fix
mutex
tests with --race
=> Noissue consensus datarace fix

network/hostnetwork/transport/base.go
small fix for log output format
=> NOISSUE: transport log format fix

cmd/pulsard/main.go, cryptohelpers/ecdsa/ecdsa.go, pulsar/networking.go, pulsar/pulsar.go, pulsar/pulsar_integration_test.go
=> Ins 568 tests and pulsar networking

pulsar/networking.go, pulsar/pulsar.go
=> INS-568 fix master

core/networkcoordinator.go, network/hostnetwork/hosthandler/hosthandler.go, network/hostnetwork/packet/packettype_string.go, network/hostnetwork/packethandler.go, network/hostnetwork/packethandler_test.go, network/servicenetwork/servicenetwork.go, networkcoordinator/networkcoordinator.go
Adding active node list to ledger when we receive new pulse
=> INS-517: mock for writing active node list to ledger

core/vm.go, logicrunner/casebind.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go
**Now our validation stores object body and uses it from casebind, not last state from ledger**
=> INS-576: use intermediate object state in validation

context/context.go, log/log.go
Created context object with embedded logger
=> INS-591: insolar context

cmd/insolard/interactive.go
insolard cli improved, added commands
- active nodes - shows active nodes list
- pulse - shows current pulse
manual test
=> NOISSUE: added activenodes and pulse commands in cli

Gopkg.lock, configuration/metrics.go, core/message/base.go, network/hostnetwork/dht.go, network/hostnetwork/dht_test.go, network/hostnetwork/hosthandler/hosthandler.go, network/hostnetwork/hostnetwork.go, network/hostnetwork/hostnetwork_test.go, network/hostnetwork/packet/packet.go, network/hostnetwork/packet/request.go, network/hostnetwork/packet/response.go, network/hostnetwork/packethandler.go, network/hostnetwork/packethandler_test.go, network/hostnetwork/requesthandler.go, network/hostnetwork/responsehandler.go, network/hostnetwork/signhandler.go, network/hostnetwork/signhandler/noncesignhandler.go, network/hostnetwork/signhandler/signhandler.go, network/servicenetwork/servicenetwork.go
NetworkCoordinator integrated to service network; authorization on discovery node.
=> INS-587, INS-585: Remove authorization dummy

functest/main_test.go, scripts/insolard/insolar.yaml
fix race in func tests
Run tests
=> INS-630: fix race in functests

logicrunner/goplugin/ginsider/ginsider.go, logicrunner/logicrunner_test.go
don't crash whole daemon when a panic happens in a contract, return an
RPC error
=> INS-623: recover on panics in insgorund

Makefile, api/requesters/requesters_test.go, application/contract/wallet/wallet.go, application/proxy/allowance/allowance.go, application/proxy/member/member.go, application/proxy/nodedomain/nodedomain.go, application/proxy/noderecord/noderecord.go, application/proxy/rootdomain/rootdomain.go, application/proxy/wallet/wallet.go, logicrunner/goplugin/preprocessor/main.go, logicrunner/goplugin/preprocessor/main_test.go, logicrunner/goplugin/preprocessor/templates/proxy.go.tpl, scripts/insolard/insolar.yaml
Update comments for proxies
Run tests
=> Ins 633 linter fixes fir proxies

pulsar/networking.go, pulsar/payload.go, pulsar/pulsar.go, pulsar/pulsar_integration_test.go, pulsar/pulsarconsensus.go, pulsar/pulsarhelpers.go, pulsar/pulsartimers.go, pulsar/state_string.go, pulsar/statemachine.go
Add checking for pulsar's state and pulse number. I think than the ifs allow us to be sure of impossibility of any damage to pulsar's state machine
Add ifs to the handler's methods
Run tests
=> INS-568 add checks for states and pulse's number

core/message/ledger.go, ledger/artifactmanager/handler.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/db.go, ledger/storage/drop_test.go, ledger/storage/storage_test.go
- send indexes with JetDrop message (temporary solution)
=> Ins-652: send indexes with drop

network/hostnetwork/dht_test.go, network/hostnetwork/hostnetwork.go, network/hostnetwork/packet/packet.go
Hostnetwork can starts at 0.0.0.0 IP
Fixed recv type ping
=> INS-645: Starting at 0.0.0.0 ip

logicrunner/logicrunner.go
=> INS-655: proper execution context removal in logicrunner calls

cryptohelpers/hash/hash.go, cryptohelpers/hash/hash_test.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/record/hash_test.go, ledger/record/meta.go, ledger/record/record.go, ledger/record/request.go, ledger/record/result.go, ledger/record/serialize.go, ledger/record/serialize_test.go, ledger/storage/storage_test.go, ledger/storage/transaction.go
Closes INS-651
Simplified record hashing and serialization.
Run tests.
=> INS-651. Simplify record serialization.

core/vm.go, logicrunner/casebind.go, logicrunner/logicrunner.go
=> Fix request registration

bootstrap/bootstrap.go, core/ledger.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptors.go, logicrunner/builtin/builtin.go, logicrunner/goplugin/goplugintestutils/utils.go, logicrunner/logicrunner.go, logicrunner/service.go
pass core.Context to all Get* ArtifactManager methods
=> Ins-586: am getters with context

logicrunner/logicrunner.go
ad hoc, need more work in INS-666
mutex lock requests to the same object
=> INS-664 "queue" of requests

bootstrap/bootstrap.go, core/ledger.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, logicrunner/builtin_test.go, logicrunner/goplugin/goplugintestutils/utils.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, logicrunner/service.go
pass context to core.ArtifactManager methods
=> Ins-586: am all methods with context

inscontext/context.go
return context copy on WithLog call
=> Ins-586: fix context race

core/logger.go, inscontext/context.go, log/log_test.go, log/logrus.go, testutils/recorder.go, testutils/recorder_test.go
add traceid to logger fields in context
=> Ins 584 trace in log

api/request_handler.go, bootstrap/bootstrap.go, core/ledger.go, core/message/base.go, core/message/ledger.go, core/messagebus.go, functest/utils_test.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/index/index.go, ledger/record/result.go, ledger/storage/db.go, ledger/storage/storage_test.go, ledger/storage/transaction.go, ledger/storage/transaction_test.go, logicrunner/builtin_test.go, logicrunner/casebind.go, logicrunner/goplugin/goplugintestutils/utils.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go
Refactored AM methods for CRUD handler.
Run tests.
=> INS-649. Crud handler

api/main.go, api/request_handler.go, api/requesters/config.go, api/requesters/requesters.go, logicrunner/logicrunner_test.go, networkcoordinator/responseextractors.go, scripts/insolard/launch.sh
=> Noissue: fix linter wishes

api/call.go, api/seedmanager/seedgenerator.go, api/seedmanager/seedmanager.go, api/seedmanager/seedmanager_test.go
Remove seed from pool after using
Run tests
=> Ins 621 remove seed from pool after access

.gitignore, api/request_handler.go, application/contract/member/member.go, application/contract/member/signer/signer.go, application/contract/nodedomain/nodedomain.go, application/contract/noderecord/noderecord.go, application/contract/rootdomain/rootdomain.go, application/contract/wallet/wallet.go, cryptohelpers/ecdsa/ecdsa.go
Remove panic from SCs
Unify returning errors
Run tests
=> Ins 636 remove panics from scs

network/servicenetwork/servicenetwork.go
removed unnecessary message serialize code duplication
=> NOISSUE: remove unnecessary message serialize code duplication

bootstrap/helpers.go, functest/.insolar.yaml
Fix absolute patches in rootKeys
Use standard Abs func
Run tests
=> Ins 701 fix absolute paths

ledger/artifactmanager/handler.go, ledger/record/meta.go, ledger/record/record.go, ledger/record/result.go
Closes INS-650
Added records validation to preserve chain records.
Run tests.
=> INS-650: Add record validation.

bootstrap/helpers.go, core/errors.go, core/ledger.go, core/message/ledger.go, core/messagebus.go, core/messagetype_string.go, core/reply/base.go, core/reply/generic.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/errors.go, ledger/artifactmanager/handler.go, ledger/index/index.go, ledger/storage/db.go, ledger/storage/storage_test.go, ledger/storage/transaction_test.go, logicrunner/goplugin/goplugintestutils/utils.go, logicrunner/logicrunner.go, logicrunner/service.go
Closes INS-687.
Implemented RegisterValidation method.
Run tests.
Object records can be validated in storage.
=> INS-687. Record approve.

core/ledger.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/record/record.go, logicrunner/goplugin/goplugintestutils/utils.go
Closes INS-709
Made UpdateObject return descriptor.
Run tests
=> INS-709. Descriptor update.

api/request_handler.go, cmd/insolard/main.go, core/networkcoordinator.go, network/dhtnetwork/signhandler/noncesignhandler.go, network/servicenetwork/servicenetwork.go, networkcoordinator/networkcoordinator.go
closes INS-708
Add context in NetworkCoordinator.
Run tests.
=> INS-708: add context in networkcoordinator

instrumentation/inslogger/logger.go
the first step of moving on standard context usage
=> INS-710: add log instrumentation helpers

scripts/insolard/launch.sh
=> Add creating required dirs

cmd/insolard/main.go
Don't try to read cert in bootstrap mode
=> Don't try to read cert in bootstrap mode

api/main.go, cmd/pulsard/main.go, pulsar/networking.go, pulsar/pulsar.go, pulsar/pulsar_integration_test.go, pulsar/pulsar_test.go, pulsar/pulsarbroadcasters.go, pulsar/pulsarconsensus.go, pulsar/pulsarhelpers.go, pulsar/pulsartimers.go, pulsar/state_switcher_mock_test.go, pulsar/statemachine.go
I added a context to the all methods of pulsar
=> Ins 582 pulsar trace

logicrunner/logicrunner.go
=> FIX: Logicrunner es.Unlock() now deffered everywhere

application/contract/noderecord/noderecord.go, application/contract/wallet/wallet.go, certificate/certificate.go, docker/Dockerfile.insolard
Add jq and other soft to docker
=> Noissue add jq to docker

core/message/base.go, core/message/serialize_test.go, core/messagetype_string.go, messagebus/messagebus.go, network/dhtnetwork/wrappers.go
fix signed message deserialization issue
=> Ins-730: fix sign message serialization

logicrunner/goplugin/preprocessor/templates/wrapper.go.tpl, logicrunner/logicrunner_test.go
closes INS-692
Add check if nil in sc constructor wrapper.
Run tests.
=> INS-692: new return nil

core/ledger.go, core/reply/ledger.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptors.go, ledger/artifactmanager/handler.go, logicrunner/goplugin/goplugintestutils/utils.go
Closes INS-724.
Added parent to object descriptor.
Run tests.
=> INS-724. Get parent.

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptors.go, ledger/artifactmanager/handler.go, ledger/ledgertestutils/ledgertestutils.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/db.go, ledger/storage/transaction.go
pass real context in AM's descriptors and most internal and public methods
=> Ins-489: flowing context in AM

messagebus/messagebus.go
fix of message bus initialization
=> NOISSUE: init expiry queue on MessageBus creation

application/contract/rootdomain/rootdomain.go, application/proxy/allowance/allowance.go, application/proxy/member/member.go, application/proxy/nodedomain/nodedomain.go, application/proxy/noderecord/noderecord.go, application/proxy/rootdomain/rootdomain.go, application/proxy/wallet/wallet.go, bootstrap/bootstrap.go, cmd/benchmark/api_request.go, functest/get_info_test.go, functest/utils_test.go, logicrunner/goplugin/preprocessor/templates/proxy.go.tpl
closes INS-736
Replace "class" with "prototype"
Run tests.
=> INS-736: remove class from code

messagebus/expiryqueue.go, network/servicenetwork/servicenetwork_test.go
=> INS-722-Expiry-queue

ledger/storage/transaction.go
=> NOISSUE: Fix transaction discard.

core/ledger.go, ledger/artifactmanager/artifactmanager.go, logicrunner/goplugin/goplugintestutils/utils.go
Closes INS-723.
Added state stub function to AM.
Run tests.
=> INS-723: Add state stub to AM.

cmd/insolard/components.go, cmd/insolard/main.go, instrumentation/pprof/doc.go, instrumentation/pprof/pprof.go, metrics/metrics.go
Add pprof handlers instrumentation
=> Noissue: add pprof to insolard

core/record.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/ledgertestutils/ledgertestutils.go, network/consensus/base_test.go, network/consensus/consensus_test.go, network/consensus/hash_test.go, network/consensus/helpers_test.go, network/dhtnetwork/dht.go, network/dhtnetwork/dht_test.go, network/dhtnetwork/hostnetwork_test.go, network/dhtnetwork/packethandler.go, network/dhtnetwork/packethandler_test.go, network/dhtnetwork/requesthandler.go, network/dhtnetwork/wrappers.go, network/nodekeeper/node.go, network/nodekeeper/nodekeeper.go, network/nodekeeper/nodekeeper_test.go, network/nodekeeper/unsync_list.go, network/servicenetwork/servicenetwork_test.go, network/transport/packet/request.go, network/transport/packet/response.go, pulsar/pulsar_integration_test.go, testutils/core.go, testutils/nodekeeper/nodekeeper.go
Extract network node to interface
=> NET-59: node interface

cmd/insolard/components.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/ledgertestutils/ledgertestutils.go, network/consensus/helpers_test.go, network/dhtnetwork/dht.go, network/dhtnetwork/dht_test.go, network/dhtnetwork/hostnetwork_test.go, network/dhtnetwork/packethandler_test.go, network/nodenetwork/node.go, network/nodenetwork/nodekeeper.go, network/nodenetwork/nodekeeper_test.go, network/nodenetwork/unsync_list.go, network/servicenetwork/servicenetwork_test.go, pulsar/pulsar_integration_test.go, testutils/nodekeeper/nodekeeper.go
=> NET-60: rename nodekeeper package to nodenetwork

core/message/signed.go, logicrunner/builtin_test.go, logicrunner/casebind.go, logicrunner/logicrunner_test.go, messagebus/messagebus.go, network/dhtnetwork/dht_test.go, network/servicenetwork/servicenetwork_test.go, testutils/testmessagebus/testmessagebus.go
Contributes to INS-741.
Added pulse to signed message.
=> INS-741. Pulse in messages.

pulsar/pulsarbroadcasters.go
add timeout for pulsar's calls to network
=> add timeouts

api/call.go, api/info.go, api/main.go, cmd/insolard/main.go, core/utils/utils.go, core/vm.go, logicrunner/accessors.go, logicrunner/builtin_test.go, logicrunner/casebind.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go
added loop detection and test for contract calling itself recursive
added check of current trace, that executor process right now. Also refactor tests.
run tests
=> INS-559 loop detection

core/ledger.go, core/message/signed.go, core/messagebus.go, ledger/ledger.go, ledger/ledgertestutils/ledgertestutils.go, ledger/localstorage/doc.go, ledger/localstorage/localstorage.go, ledger/storage/db.go, ledger/storage/transaction.go, logicrunner/logicrunner_test.go, network/dhtnetwork/mockutils.go, network/servicenetwork/servicenetwork_test.go
Contributes to INS-741.
Added local storage.
=> INS-741. Localstorage

api/main.go, api/main_test.go, api/query_params.go, api/request_handler.go
=> INS-603: old api removed

consensus/phases/data.go, consensus/phases/data_serializers.go, consensus/phases/data_test.go, network/transport/udp.go
1) Add serialization for consensus packets
2) Add tests
Run tests
=> NET-36: first phase packet

cryptohelpers/ecdsa/ecdsa.go, logicrunner/builtin_test.go, logicrunner/logicrunner_test.go, network/merkle/calculator.go, network/merkle/calculator_test.go, network/merkle/cloudproof.go, network/merkle/globuleproof.go, network/merkle/helpers.go, network/merkle/nodeproof.go, testutils/certificate/certificate.go, testutils/nodekeeper/nodekeeper.go
=> NET-17: merkle tree

application/contract/allowance/allowance.go, core/message/logicrunner.go, core/vm.go, logicrunner/goplugin/ginsider/ginsider.go, logicrunner/goplugin/rpctypes/rpctypes.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, logicrunner/service.go
closes INS-738
Add CallerPrototype to LogicCallContext.
Run tests.
=> INS-738: create allowance by only wallet

Makefile, consensus/phases/communicator.go, consensus/phases/phasemanager.go, consensus/phases/phases.go, consensus/phases/phases_test.go, core/nodenetwork.go, testutils/network/node_network_mock.go
Consensus communicator interface proposal
Using DI in phases package
initial tests
=> NET-40, Net-41 phase1 exchange interface

Gopkg.lock, Gopkg.toml, cmd/insolard/components.go, cmd/insolard/main.go, instrumentation/insmetrics/doc.go, instrumentation/insmetrics/insmetrics.go, instrumentation/instracer/examples/clientserver_test.go, instrumentation/pprof/doc.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/metrics.go, ledger/artifactmanager/metrics_test.go, metrics/metrics.go, metrics/metrics_test.go, testutils/testmetrics/testmetrics.go
Add metrics support (via opencensus tools) in most of the public Artifact manager methods
(Prometheus client rollback to 0.8.0)
=> Ins 742 storage metrics

metrics/metrics.go, testutils/testmetrics/testmetrics.go
fix the race for metrics server port binding in tests (just use any available port)
=> NOISSUE: fix race for metrics server port binding in tests

instrumentation/insmetrics/insmetrics.go, metrics/metrics.go
improve metrics errors logging
=> NOISSUE: improve metrics errors logging

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/instrument.go, ledger/artifactmanager/metrics.go, ledger/artifactmanager/metrics_test.go, metrics/metrics.go
- in metrics don't use default http server mux for easier testing 
- make AM's instrumentation code cleaner
=> NOISSUE: refactor instrumentation code

instrumentation/hack/hack.go, ledger/artifactmanager/handler.go, ledger/pulsemanager/pulsemanager.go, messagebus/messagebus.go, pulsar/pulsar_integration_test.go, pulsar/pulsar_test.go
- don't send drop from non material nodes
- disable validation on the same node as a sender
=> INS-744: disable validation for local way of a message and skip send drop on non materials

consensus/phases/phasemanager.go, consensus/phases/phases.go, consensus/phases/states.go
=> NET-32: phase timeout

Gopkg.lock, configuration/metrics.go, metrics/metrics.go, metrics/metrics_test.go, testutils/testmetrics/testmetrics.go
Add zpages support in metrics server.
More info:
- https://opencensus.io/zpages/
- https://github.com/rakyll/opencensus-grpc-demo
=> add zpages to instrumentation 

ledger/localstorage/localstorage.go
- fix localstorage serialization
=> NOISSUE: fix localstorage serialization

Gopkg.lock, configuration/metrics.go, instrumentation/insmetrics/insmetrics.go, metrics/badger.go, metrics/metrics.go, metrics/metrics_test.go, testutils/testmetrics/testmetrics.go
add badger metrics to Prometheus exporter
=> add badger metrics

core/record.go, instrumentation/inslogger/doc.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/instrument.go, ledger/storage/db.go, ledger/storage/drop_test.go, ledger/storage/storage_test.go, ledger/storage/transaction.go, ledger/storage/transaction_test.go
pass context and improve logs in ledger
=> Ins 489 ledger debug logs

consensus/phases/phases_test.go, core/nodenetwork.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/ledgertestutils/ledgertestutils.go, network/consensus/hash.go, network/consensus/helpers_test.go, network/controller/auth/authorization_controller.go, network/interfaces.go, network/nodenetwork/node.go, network/nodenetwork/nodekeeper.go, network/nodenetwork/nodekeeper_test.go, network/servicenetwork/servicenetwork_test.go, pulsar/pulsar_integration_test.go, testutils/nodekeeper/nodekeeper.go, version/manager/utils_test.go
Added short ID in nodes to use it for communications inside one globe
run tests
=> Net-84: add short ID to Node & NodeKeeper

README.md, api/requesters/requesters.go, api/requesters/requesters_test.go, application/contract/member/member.go, cmd/insolar/README.md, cmd/insolar/main.go
closes INS-763
Add "use root as caller flag" to insolar.
Run tests.
=> INS-763: add root as caller flag

core/messagebus.go, ledger/artifactmanager/artifactmanager.go
Closes INS-767.
Made AM use message bus from context.
=> INS-767. Use bus from context in AM.

core/pulse.go, pulsar/pulsarbroadcasters.go
Add additional fields to pulse
=> NET-88 add additional fields to pulsar

logicrunner/builtin_test.go, logicrunner/casebind.go, logicrunner/logicrunner_test.go, messagebus/player.go, messagebus/player_test.go, messagebus/recorder.go, messagebus/recorder_test.go, messagebus/sender_mock_test.go, messagebus/tape_mock_test.go, network/servicenetwork/servicenetwork_test.go, testutils/local_storage_mock.go, testutils/message_bus_mock.go, testutils/pulse_manager_mock.go, testutils/testmessagebus/testmessagebus.go
=> Noissue some refactorings

application/contract/member/member.go, application/contract/rootdomain/rootdomain.go, application/contract/wallet/wallet.go, application/proxy/wallet/wallet.go
=> INS-772: getBalance

logicrunner/goplugin/preprocessor/main.go, logicrunner/logicrunner_test.go
Now you can build contracts without methods.
If there is no methods except constructors we doesn't import foundation in proxy.
I change broken test and now it works without hacks
=> INS-737 build proxy without methods

consensus/packets/data.go, consensus/packets/data_serializers.go, consensus/packets/data_test.go, consensus/packets/interfaces.go
Implement ExtractPacket
Run tests
=> Net 109 implementation extract packet

cmd/insolard/components.go, cmd/insolard/main.go, component/lifecycle.go, component/manager.go, core/ledger.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/jetcoordinator/jetcoordinator.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/ledger.go, ledger/ledgertestutils/ledgertestutils.go, ledger/localstorage/localstorage.go, ledger/pulsemanager/pulsemanager.go, ledger/pulsemanager/pulsemanager_test.go, ledger/storage/db.go, ledger/storage/storagetest/utils.go, logicrunner/builtin_test.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, messagebus/messagebus.go, network/merkle/calculator.go, network/merkle/calculator_test.go, pulsar/pulsar_integration_test.go
Closes INS-768.
Implemented Ledger DI for component manager.
Run tests.
=> INS-768. Ledger DI.

functest/register_node_test.go, logicrunner/accessors.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go
added es.ErrorWrapper
add new method and new data for it, change old tests
run tests
=> INS-733 new ES Error Wrapper

logicrunner/logicrunner.go
=> NOISSUE fix error wrapping

core/ledger.go, ledger/jetcoordinator/jetcoordinator.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/db.go
Closes INS-777
Implemented active node in-memory history.
=> INS-777. Node history.

cmd/insolard/main.go
fix traceid propagation in insolard
=> NOISSUE: fix traceid propagation in insolard

network/controller/auth/authorization_controller.go, network/controller/bootstrap_controller.go, network/controller/common/interfaces.go, network/controller/controller.go, network/controller/rpc_controller.go, network/hostnetwork/transport_base.go, network/hostnetwork/transport_consensus_test.go, network/hostnetwork/transport_resolvable.go, network/hostnetwork/transport_test.go, network/interfaces.go, network/nodenetwork/nodekeeper.go, network/servicenetwork/servicenetwork.go, network/transport/kcp.go, network/transport/transport.go, network/transport/transport_test.go, network/transport/udp.go, network/transport/utp.go, pulsar/pulsarbroadcasters.go
Added context with TraceID to all network calls
check logs
=> Net-89: added context to all calls

pulsar/pulsar.go, pulsar/pulsar_test.go, pulsar/pulsarbroadcasters.go, pulsar/pulsarconsensus.go, pulsar/pulsarhelpers.go
I fixed dataraces in tests.
A few locks were added
Also I tried to reproduce INS-779, but failed in the attempts.
=> INS-779 fix pulsar's tests

Gopkg.lock, component/manager.go, consensus/phases/phases.go, core/ledger.go, network/merkle/calculator.go, network/merkle/calculator_test.go, network/merkle/entry.go, network/merkle/errors_test.go, network/merkle/hashes_test.go, network/merkle/helpers.go, network/merkle/helpers_test.go, network/merkle/interfaces.go, network/merkle/tree.go, network/merkle/tree_test.go, testutils/artifact_manager_mock.go, testutils/ledger/artifact_manager_mock.go, testutils/merkle/calculator_mock.go
=> NET-106: Merkle proof and tests

application/contract/member/member.go, application/contract/nodedomain/nodedomain.go, application/contract/noderecord/noderecord.go, application/contract/rootdomain/rootdomain.go, logicrunner/accessors.go, logicrunner/goplugin/ginsider/ginsider.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go
**Now we can use special annotation on methods to allow call it from api (Without initial caller and request)**
=> Ins 764 start validation chain

network/state/fsm.go, network/state/switcher.go, network/switcher.go
=> NET-116: Interface fsm

logicrunner/accessors.go, logicrunner/builtin_test.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go
**Use new injection system in logicrunner**
=> Noissue lr pulsemanager

logicrunner/logicrunner.go
lowers race condition possibility
=> we already have required data in a variable, use it

cmd/pulsard/main.go
Fix pulsar config reading and DI
=> NOISSUE: pulsar config and DI fix

network/controller/rpc_controller.go
=> rpc controller scheme init

logicrunner/casebind.go
**Satisfy message buss internal behavior**
=> FIX: Validation response is a reply now

core/message/base.go, core/message/ledger.go
=> gob message registration

configuration/ledger.go, core/ledger.go, core/message/heavy.go, core/message/messagehelpers.go, core/messagebus.go, core/nodenetwork.go, core/vm.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/heavy_test.go, ledger/ledgertestutils/ledgertestutils.go, ledger/pulsemanager/heavy.go, ledger/pulsemanager/heavy_test.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/db.go, ledger/storage/drop_test.go, ledger/storage/logger.go, ledger/storage/logger_debug.go, ledger/storage/replica.go, ledger/storage/replica_iter.go, ledger/storage/replica_iter_test.go, ledger/storage/replica_test.go, ledger/storage/storage_test.go, ledger/storage/storagetest/utils.go, ledger/storage/transaction.go, ledger/storage/transaction_test.go, metrics/metrics_test.go, testutils/logic_runner_mock.go, testutils/network/node_mock.go
Add support aggregation of records by pulse number with current indexes in HeavyRecords messages.
Also, add handling HeavyRecords in the Artifact Manager.
=> Ins 755 heavy replica

consensus/packets/bitset.go
Added bitset interface for phase 2 packets of the consensus
=> NET-121: bitset interface

core/record.go, instrumentation/hack/hack.go
- Changed default strign representation of RecordID to base58
- Added Hash() method to RecordID returning a copy of hash part of ID
- Added minor check to SkipValidation context value
=> NOISSUE: minor RecordID updates

network/nodenetwork/nodekeeper.go, network/nodenetwork/nodekeeper_test.go, network/nodenetwork/recordref_set.go
Fixed bug that caused to nodes duplication in nodekeeper role index
run tests
=> NET-163: nodekeeper fix

consensus/phases/firstphase.go, consensus/phases/secondphase.go, consensus/phases/states.go, network/interfaces.go, network/nodenetwork/nodekeeper.go, testutils/network/node_keeper_mock.go
Added separate unsync list interface
=> NET-149: nodekeeper sync list

cmd/insolard/components_test.go, consensus/packets/claim_serializers.go, consensus/packets/data.go, consensus/packets/data_serializers.go, consensus/packets/data_test.go, consensus/packets/vote.go, consensus/packets/vote_test.go
Vote structs for consensus binary protocol
unit tests
=> NET-144 NET-145 NET-146 vote structs, serializers, tests

certificate/certificate.go, functest/genesis.yaml, genesis/config.go
=> [WIP] NET-138: pulsars pKeys added to certificates

component/manager.go
set debug log level for debugging messages in component manager (to suppress unnecessary info)
=> NOISSUE: fix log level for component manager

application/contract/rootdomain/rootdomain.go, application/proxy/rootdomain/rootdomain.go
closes NET-164
Add method Info() to RoorDomain contract
Run tests
=> NET-164: add Info() to RootDomain

ledger/pulsemanager/heavy_test.go, ledger/storage/replica_iter.go, ledger/storage/replica_iter_test.go
Add blob and jetdrop key values to heavy replication
=> Ins-792: replicate all records

Gopkg.lock, consensus/packets/bitset.go, consensus/packets/data.go, consensus/packets/data_serializers.go, consensus/packets/data_test.go, consensus/packets/devianbitset.go, consensus/packets/tristatebitset.go, consensus/packets/tristatebitset_test.go
=> NET-123: bitset implementation

network/controller/auth/authorization_controller.go, network/controller/controller.go, network/hostnetwork/transport_test.go, network/interfaces.go, network/nodenetwork/nodekeeper.go, network/routing/table.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/servicenetwork_test.go, pulsar/pulsar_integration_test.go
old component manager removed from network
=> Net-160 remove old component manager

consensus/phases/communicator_mock.go, core/messagetype_string.go, messagebus/sender_mock_test.go, messagebus/tape_mock_test.go, testutils/artifact_manager_mock.go, testutils/cryptography_service_mock.go, testutils/key_processor_mock.go, testutils/local_storage_mock.go, testutils/merkle/calculator_mock.go, testutils/message_bus_mock.go, testutils/network/consensus_network_mock.go, testutils/network/host_network_mock.go, testutils/network/node_network_mock.go, testutils/network/pulse_handler_mock.go, testutils/pulse_manager_mock.go
=> NOISSUE: rebuild stringer and mocks

core/message/heavy.go, core/message/messagehelpers.go, core/messagebus.go, core/messagetype_string.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/heavy_test.go, ledger/pulsemanager/heavy.go, ledger/pulsemanager/heavy_test.go, ledger/pulsemanager/pulsemanager.go
add start/stop messages to heavy sync routine
=> INS-793: start and end records for heavy sync

api/call.go, api/info.go, api/main.go, api/main_test.go, certificate/certificate.go, cmd/insolard/components.go, core/certificate.go, core/genesis.go, core/genesisdataprovider.go, functest/get_info_test.go, functest/utils_test.go, genesis/genesis.go, genesisdataprovider/genesisdataprovider.go, networkcoordinator/networkcoordinator.go
closes NET-166
Add new component GenesisDataProvider, which get access to basic genesis data
Run tests
=> NET-166: genesisdataprovider component

logicrunner/logicrunner.go
**Bug with disapearing objectdescriptor is fixed**
=> INS-819: Do not think, that AM can not to broke objectbody.

Makefile, cmd/exporter/main.go
Closes INS-820.
Implemented exporter binary service.
=> INS-820: Add exporter binary.

core/message/messagehelpers.go, core/record.go, logicrunner/goplugin/ginsider/ginsider.go, logicrunner/logicrunner.go
**Now any node can be an api**
=> FIX: api can be on any node

logicrunner/logicrunner.go
fix Unlock with correct Lock order
change order of lock and counter increment
ask Shibitov
=> INS-822 correct lock of es

logicrunner/goplugin/goplugin.go
add loging
with great diligence
run tests, watch to logs
=> INS-809 add write to log while reconnecting to insgorund

certificate/certificate.go, certificate/certificate_test.go, core/certificate.go, genesis/genesis.go
Added GetBootstrapNodes to core Certificate interface
=> NOISSUE: added GetBootstrapNodes to core Certificate interface

consensus/packets/bitarray.go, consensus/packets/tristatebitset.go, consensus/packets/tristatebitset_test.go
bitset serialization/deserialization
=> NET-122, NET-125: bitset (de)serialization

logicrunner/goplugin/ginsider/ginsider.go
* one level lock blocks everybody when somebody touches network
* use core.RecordRef as map's key, it was not possible at some point,
but it is now and there is no point to do otherwise
=> two level locking of code cache in ginsider

core/heavy.go, core/message/heavy.go, core/pulse.go, core/reply/base.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/heavy_test.go, ledger/heavy/doc.go, ledger/heavy/heavysync.go, ledger/heavy/heavysync_test.go, ledger/ledger.go, ledger/pulsemanager/heavy.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/db.go, ledger/storage/replica.go, ledger/storage/replica_test.go, testutils/heavy_sync_mock.go
Add locks at heavy node synchronization.
=> Ins 794 heavy sync lock

configuration/ledger.go, ledger/ledger.go, ledger/ledgertestutils/ledgertestutils.go, ledger/pulsemanager/heavy_test.go, ledger/pulsemanager/pulsemanager.go
switch from functional options to common configuration logic in pulse manager
=> Ins-830 replication config

logicrunner/goplugin/goplugin.go
=> NOISSUE_more_logs

configuration/ledger.go, core/delegationtoken.go, core/delegationtoken/base.go, core/delegationtoken/factory.go, core/messagebus.go, core/reply/base.go, core/reply/redirect.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptors.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, testutils/delegation_token_factory_mock.go
Closes INS-714.
Implementer get children redirects.
Run tests.
=> INS-714. Iterate children redirect.

scripts/insolard/bootstrap_keys.json, scripts/insolard/certificate.json, scripts/insolard/insolar.yaml, scripts/insolard/launch.sh, scripts/insolard/one_node_genesis.yaml, scripts/insolard/one_node_insolar.yaml
closes NET-185
Update script for start insolard
Run script, make requests to api
=> NET-185: update launch script

Makefile, cmd/apirequester/README.md, cmd/apirequester/api_request.go, cmd/apirequester/main.go, cmd/apirequester/scenario.go
closes NET-176
apirequester makes several requests to API and return results of them.
Run tests.
=> NET-176: apirequester

ledger/exporter/exporter.go, ledger/exporter/exporter_test.go
=> INS-42: Fix exporter memory JSON serialization.

core/ledger.go, core/message/base.go, core/message/ledger.go, core/message/messagehelpers.go, core/messagebus.go, core/reply/base.go, core/reply/ledger.go, functest/dump_test.go, functest/get_balance_test.go, functest/send_money_test.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go
Closes INs-826.
Implemented index fetching for Get and update object methods.
Run tests.
=> INS-826. Update redirect

.travis.yml, Gopkg.lock, Gopkg.toml, Makefile, functest/common_test.go, functest/create_member_test.go, functest/dump_test.go, functest/get_balance_test.go, functest/get_info_test.go, functest/get_seed_test.go, functest/main_test.go, functest/new_api_test.go, functest/reconnect_test.go, functest/register_node_test.go, functest/send_money_test.go, functest/utils_test.go
=> Noissue functest separate build

component/manager.go, configuration/hostnetwork.go, consensus/phases/phasemanager.go, core/networkcoordinator.go, network/servicenetwork/integr_test.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/servicenetwork_test.go, testutils/network_coordinator_mock.go
- servicenetwork refactoring
- integration test 
- old service network tests commented
=> NET-165: consensus integration tests

consensus/packets/bitarray.go, consensus/packets/tristatebitset.go, consensus/packets/tristatebitset_test.go
de/serialize compressed bitset
=> NET: bitset compress

logicrunner/logicrunner_test.go
=> FIX: Skip test for execution queue releasing

core/components.go, pulsar/pulsar_integration_test.go
=> NET-14 pulsar inject fix

core/delegationtoken.go, core/delegationtoken/base.go, core/delegationtoken/factory.go, core/messagebus.go, core/reply/base.go, core/reply/redirect.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, testutils/delegation_token_factory_mock.go
Closes INS-24
Implemented index fetching and redirects in get code and register child.
Run tests
=> INS-24. Index fetch.

ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go
=> INS-24: Fix merge defects.

.travis.yml, Makefile
=> NO-ISSUE fix func test on travis

api/call.go, api/requester/requester.go, certificate/certificate.go
=> Noissue logger crypto fix

api/call.go, functest/create_member_test.go, functest/dump_test.go, functest/get_balance_test.go, functest/main_test.go, functest/new_api_test.go, functest/send_money_test.go
1) little refactoring of callHandler
Run tests
=> Net 137 health check

certificate/certificate.go, configuration/hostnetwork.go, network/hostnetwork/transport_consensus.go, network/servicenetwork/integr_test.go, network/servicenetwork/servicenetwork.go, network/transport/transport.go
test node join
workaround for consensus transport address port+1
test don't pass
=> NET-8 testcase node connect

Makefile
=> Noissue go generate target

.travis.yml, Makefile
check if git repo unchanged in CI before build stage (try to catch forgotten generated files)
=> NOISSUE: check repo working dir on changes in CI

api/main.go, api/main_test.go, api/requester/requester.go, api/requester/requester_test.go, api/requester/responses.go, api/status.go, core/nodenetwork.go, functest/get_status_test.go, functest/utils_test.go, network/controller/bootstrap/network_bootstrap.go, network/interfaces.go, network/nodenetwork/nodekeeper.go, network/servicenetwork/servicenetwork.go
Add status request to api
Run tests
=> Ins 123 health api check

core/networkswitcher.go, network/servicenetwork/integr_test.go, pulsar/pulsar_integration_test.go, testutils/network_switcher_mock.go
=> No issue updates

logicrunner/goplugin/ginsider/ginsider_test.go
=> NOISSUE: fix ginsider test

network/controller/bootstrap/bootstrap.go
Correct node serialization & deserialization during genesis bootstrap
Run launchnet.sh
=> NET-25: pk serialize

api/main.go, consensus/phases/communicator_test.go, consensus/phases/firstphase_test.go, ledger/jetcoordinator/jetcoordinator_test.go, network/controller/bootstrap/bootstrap.go, pulsar/pulsar_integration_test.go, version/manager/utils_test.go
=> No issue fixes

scripts/insolard/check_status.sh
=> Fix check_status script

certificate/certificate.go, certificate/certificate_test.go
closes INS-858
Add ReadCertificateFromReader func 
Run tests
=> INS-858: new cert from reader

core/message/ledger.go, core/message/messagehelpers.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, ledger/pulsemanager/pulsemanager.go, ledger/pulsemanager/pulsemanager_test.go
I added a previous drop to hot records. So, when ME is given them, it saves jd to db
=> Ins 20 drop inside hot records

logicrunner/goplugin/ginsider/ginsider_test.go
check for binary file exists in test
=> FIX: tests for healthcheck may fail without make build

network/controller/bootstrap/network_bootstrap.go, network/controller/bootstrap/session_manager.go, network/servicenetwork/integr_test.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/wrappers_test.go
integration test -  node join
NodeNetwork and PhaseManager wrappers for test usage
nope
=> NET-8 NET-29 testcase node connect

cmd/insgocc/insgocc.go
The support of --keep-temp flag was added to insgocc utility. When user provides this flag, insgocc keeps temporary files created during `insgocc compile`, which includes files generated from templates (.go.tpl). This is useful during debugging.
=> NOISSUE: add --keep-temp flag to insgocc

Makefile
excluded mocks from test coverage report
=> NOISSUE: exclude mocks from coverage report

scripts/insolard/launchnet.sh
- added genesis to launchnet.sh
=> Ins 879 rerun launchnet

messagebus/messagebus.go, messagebus/tape.go, messagebus/tape_test.go
**Switch messagebus from storage tape to in memory tape**
=> Ins 57 messagebus without disk

certificate/manager.go
=> NOUSSUE: update NewUnsignedCertificate func

network/nodenetwork/nodekeeper.go
=> NET-23: gracefully stop on deleting self node from active list

Makefile, fetchminimock.sh, scripts/build/fetchdeps
=> fix problems with mock

scripts/build/fetchdeps
=> fix for cd $path

cmd/pulsard/main.go, pulsar/pulsar.go
=> fix small problems with stopping and logs

scripts/build/fetchdeps
Fixed some not obvious problems in fetchdeps
=> NOISSUE: fix fetchdeps

cmd/insolard/main.go, log/log.go, scripts/insolard/launchnet.sh
Now all loggers ( even old ones ) can read config from file
=> Ins 874 fix logging

scripts/build/fetchdeps
- bash strict mode
- add comments in code
- fetch fresh code
- check arguments count, provides help
=> NOISSUE: fetchdeps UX improvements

ledger/ledgertestutils/ledgertestutils.go, ledger/pulsemanager/heavy_test.go, ledger/pulsemanager/pulsemanager.go, ledger/pulsemanager/pulsemanager_test.go, testutils/active_list_swapper_mock.go
=> NET-24: swap active list in pulse manager

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/db.go, ledger/storage/pulse.go, ledger/storage/storage_test.go, ledger/storage/storagetest/utils.go, ledger/storage/store.go, ledger/storage/transaction.go
=> Ins 845 refactor lastest pulse

core/ledger.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, ledger/exporter/exporter.go, ledger/exporter/exporter_test.go, ledger/pulsemanager/heavy.go, ledger/pulsemanager/heavy_test.go, ledger/pulsemanager/pulsemanager.go, ledger/pulsemanager/pulsemanager_test.go, ledger/storage/db.go, ledger/storage/drop_test.go, ledger/storage/replica_iter.go, ledger/storage/replica_iter_test.go, ledger/storage/storage_test.go, ledger/storage/store.go, ledger/storage/transaction.go, ledger/storage/transaction_test.go
add a jet id to storage methods
=> Ins 862 db jetscope

scripts/insolard/genesis.yaml, scripts/insolard/insolar_1.yaml, scripts/insolard/insolar_2.yaml, scripts/insolard/insolar_3.yaml, scripts/insolard/launchnet.sh
=> Noiisue fix functests

cmd/insolard/components.go, consensus/phases/phasemanager.go, network/servicenetwork/integr_test.go, network/servicenetwork/servicenetwork.go
Testcase for network integration test with full timeout node
=> NET-10: testcase full timeout

ledger/storage/record/typeid_string.go, utils/entropy/entropy_test.go
=> INS-30: Fix tests.

ledger/jetcoordinator/jetcoordinator.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/jetcoordinator/utils_test.go, ledger/storage/jet/tree.go, ledger/storage/jet/tree_test.go, ledger/storage/transaction.go
=> INS-30. Refactor jet tree.

network/fakepulsar/fakepulsar.go, network/nodenetwork/nodekeeper.go, network/servicenetwork/integr_test.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/wrappers_test.go
=> Net 8 testcase node connect

ledger/artifactmanager/handler.go, ledger/jetcoordinator/jetcoordinator.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/storage/jet/tree.go, ledger/storage/jet/tree_test.go
Closes INS-917.
Made hard-coded tree saved each pulse.
Run tests.
=> INS-917. Hard tree.

contractrequester/contractrequester_test.go, core/nodenetwork.go, network/state/switcher.go, network/state/switcher_test.go, testutils/network/switcher_work_around_mock.go
=> Ins 878 switcher test

ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, ledger/artifactmanager/heavy_test.go, ledger/ledger.go, ledger/ledgertestutils/ledgertestutils.go, ledger/pulsemanager/heavy_test.go, ledger/pulsemanager/pulsemanager.go, ledger/pulsemanager/pulsemanager_test.go, ledger/recentstorage/provider_mock.go, ledger/recentstorage/recentstorage.go, ledger/storage/recentstorage.go, ledger/storage/recentstorage_test.go, logicrunner/builtin_test.go, logicrunner/logicrunner_test.go
Every jet has its own recent storage
=> Ins 915 recentstorage jets

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler_test.go
=> INS-910. Tree update tests.

ledger/artifactmanager/handler_test.go, ledger/storage/jet.go
=> fix problems with saving jets

consensus/phases/secondphase.go, core/network.go, core/nodenetwork.go, logicrunner/logicrunner.go, messagebus/messagebus.go, network/nodenetwork/hash.go, network/nodenetwork/node.go, network/servicenetwork/servicenetwork.go, pulsar/pulsar_integration_test.go, testutils/network/network.go, testutils/network/node_mock.go, testutils/nodekeeper/nodekeeper.go
=> NOISSUE: remove duplicate methods

Gopkg.lock, Gopkg.toml, core/heavy.go, core/message/heavy.go, core/message/ledger.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, ledger/artifactmanager/handlers_syncheavy.go, ledger/artifactmanager/heavy_test.go, ledger/heavy/heavysync.go, ledger/heavy/heavysync_test.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/db.go, ledger/storage/jet/jetid.go, ledger/storage/replica.go, ledger/storage/replica_test.go, testutils/heavy_sync_mock.go
some progress with adding JetID support
=> Ins 933 heavy handlers with jetid

configuration/hostnetwork.go, network/controller/bootstrap/authorization.go, network/controller/bootstrap/network_bootstrap.go, network/controller/bootstrap/session_manager.go, network/controller/bootstrap/session_manager_test.go, network/controller/common/options.go, network/controller/controller.go
=> NET-18: handshake session ttl

network/controller/bootstrap/helper.go, network/controller/bootstrap/helper_test.go
=> NET-19: fix uint32 overflow

ledger/exporter/exporter.go, ledger/exporter/exporter_test.go
=> INS-938 exporter

Makefile, network/controller/bootstrap/session_manager.go, network/controller/bootstrap/session_manager_test.go
=> NOISSUE: fix session manager race

configuration/ledger.go, core/message/ledger.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, ledger/pulsemanager/heavy_test.go, ledger/pulsemanager/pulsemanager.go, ledger/pulsemanager/pulsemanager_test.go, ledger/storage/db.go, ledger/storage/drop_test.go, ledger/storage/jet.go, ledger/storage/jet/jetdrop_size.go, ledger/storage/replica_iter_test.go, ledger/storage/storage_test.go, ledger/storage/storagetest/jet_test.go, ledger/storage/storagetest/utils.go, scripts/insolard/genesis.yaml, testutils/core.go
Add forwarding of drop sizes
Run tests
=> Ins 23 forward last block size to next lme

configuration/hostnetwork.go, network/controller/bootstrap/bootstrap.go, network/controller/bootstrap/bootstrap_test.go, network/controller/common/options.go, network/controller/controller.go
Added infinity bootstrap retry and customisation it from config
=> NET-16: Bootstrap connect retry

api/exporter.go, ledger/exporter/exporter.go, ledger/exporter/exporter_test.go
=> Ins 35 miltiple drops export

cmd/pulsard/main.go, network/hostnetwork/transport_base.go, network/pulsenetwork/distributor.go, network/transport/kcp.go, network/transport/quic.go, network/transport/tcp.go, network/transport/transport.go, network/transport/transport_test.go, network/transport/udp.go, network/transport/utp.go
=> Fix pulsar

core/ledger.go, core/message/ledger.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, ledger/artifactmanager/heavy_test.go, ledger/artifactmanager/metrics_test.go, ledger/artifactmanager/middleware.go, ledger/heavy/heavysync.go, ledger/jetcoordinator/jetcoordinator.go, ledger/recentstorage/recentstorage.go, ledger/storage/db.go, ledger/storage/recentstorage.go, ledger/storage/replica.go, ledger/storage/replica_iter.go, ledger/storage/replica_iter_test.go, ledger/storage/transaction.go, logicrunner/goplugin/goplugintestutils/utils.go
Closes INS-916.
Calculate jet id from records.
Run tests.
=> INS-916: Use jet in handlers.

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/descriptors.go
- added code cache to artefact manager's GetCode()
- removed descriptors cache
- wrote unit test for GetCode()
- run artefact manager's unit test
=> INS-940: code caching in artifact manager

consensus/packets/bitarray.go, consensus/packets/data_test.go, consensus/packets/tristatebitset.go, consensus/packets/tristatebitset_test.go
Fixed a uint8 state overflow in bitset
=> NET-49: bitset states overflow

core/ledger.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/jet.go
Close INS-964.
Save jet on handle hot and drop.
Run tests.
=> INS-964: Save jet on hot records and drop handle.

genesis/config.go, genesis/genesis.go, scripts/insolard/genesis.yaml
- added cert_name to genesis.yaml
- modified genesis/config
- modified genesis's makeCertificates()
- run functest
=> INS-951: added cert_name in genesis.yaml

ledger/artifactmanager/handler_test.go
=> NOISSUE: FIx tests.

ledger/storage/db.go, ledger/storage/errors.go, ledger/storage/pulse.go, ledger/storage/storage_test.go, ledger/storage/transaction.go
Attempts to use closed DB now return proper errors.
Added isClosed flag which is raised on closing DB. Check this flag in BeginTransaction() and iterate() methods.
=> INS-957: closed db returns error

api/main.go, api/status.go, functest/get_status_test.go, functest/main_test.go, functest/utils_test.go, scripts/insolard/launchnet.sh
add  ActiveListSize to api status request
Run tests
=> INS-946: The Roochka with activenodelist len

contractrequester/contractrequester.go, contractrequester/contractrequester_test.go, core/ledger.go, ledger/ledger.go, ledger/ledgertestutils/ledgertestutils.go, ledger/pulsemanager/heavy.go, ledger/pulsemanager/pulse_storage_pm_mock.go, ledger/pulsemanager/pulsemanager.go, ledger/pulsemanager/pulsemanager_test.go, ledger/pulsemanager/pulsestoragepm.go, ledger/storage/pulsestorage.go, ledger/storage/pulsestorage_test.go, logicrunner/accessors.go, logicrunner/builtin_test.go, logicrunner/casebind.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, logicrunner/service.go, network/servicenetwork/servicenetwork.go, networkcoordinator/networkcoordinator.go, networkcoordinator/networkcoordinator_test.go, networkcoordinator/real.go, networkcoordinator/real_test.go, pulsar/pulsar_integration_test.go, testutils/pulse_manager_mock.go, testutils/pulse_storage_mock.go
=> Ins 905 PulseStorage

cmd/benchmark/README.md, cmd/benchmark/api_request.go, cmd/benchmark/main.go, cmd/benchmark/scenario.go
add api url flag for benchmark
=> Ins 983 benchmark add api flag

network/transport/packet/packet.go, network/transport/tcp.go, network/transport/transport_test.go
=> NOISSUE: tcp pool

application/contract/wallet/wallet.go, application/proxy/wallet/wallet.go, functest/send_money_test.go
- changed wallet.Accept() to wallet.AcceptNoWait()
- fixed wallet's proxy
- add checkBalanceFewTimes() to functest
- fixed functest to use checkBalanceFewTimes()
- run functest
=> INS-115: transfer notification call

core/message/logicrunner.go, logicrunner/casebind.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
add sending pending flag and execution queue to next executor, add unit tests
add check of pending in OnPulse(), add new message and send it from OnPulse() 
run tests
=> INS-973 send pending data

consensus/packets/phase3packet.go, consensus/phases/common.go, consensus/phases/communicator.go, consensus/phases/firstphase.go, consensus/phases/firstphase_test.go, consensus/phases/phasemanager.go, consensus/phases/secondphase.go, consensus/phases/states.go, consensus/phases/thirdphase.go, network/interfaces.go, network/nodenetwork/unsync_list.go, testutils/network/unsync_list_mock.go
Reworked phase 3 of consensus and fixed phase 2 bugs and edge cases
=> Net 64 phase3

cmd/benchmark/README.md, cmd/benchmark/api_request.go, cmd/benchmark/main.go
- Benchmark can use few nodes for roundrobin requests
=> INS-1000: benchmark load multiple nodes

Makefile, log/sourceinfo.go, network/controller/bootstrap/session_manager.go, network/pulsenetwork/distributor.go, network/transport/base.go, network/transport/tcp.go
=> Ins 969 update network for pulsar

core/ledger.go, messagebus/messagebus.go
skip tokens check for VM messages (until VM implements proper logic)
=> INS-986: skip token check for VM messages

core/ledger.go, messagebus/messagebus.go
=> Revert "INS-986: skip token check for VM messages"

ledger/artifactmanager/handler.go
skip jet checks on the heavy material node
=> INS-923: don't check jet on heavy messages

logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
resolve deadlock
don't send message on next executor if it is me
run tests
=> INS-1008 resolve deadlock when we are new executor

logicrunner/logicrunner.go
we should unset QueueProcessorActive in the same Lock block where we
decide to return.
old code:
1) lock in the begin of "endless" for loop
2) lock before "check QueueProcessorActive to before start"
3) check of queue length, it's zero
4) unlock+return
5) "check QueueProcessorActive to before start" from 2) wakes up,
checks QueueProcessorActive, queue processor is not started, unlock
6) defer in queue processor sets QueueProcessorActive to false under
lock/unlock pair
As result: no race access to data, but as well no active queue
processor with not empty queue
=> execution queue processor could go away with request in the queue

core/message/logicrunner.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
add return mode of queueElement to executorResults sending and parsing
run tests
=> NO_ISSUE_add_return_mode in sending and receiving message

application/contract/rootdomain/rootdomain.go, application/proxy/rootdomain/rootdomain.go
Changed output error in DumpUserInfo method
=> NOISSUE: Fix DumpUserInfo error output

network/transport/pool/connectionpool.go, network/transport/pool/utils.go, network/transport/tcp.go
=> NOISSUE: fix read deadline race

keystore/keystore.go
=> Noissue cache private key

logicrunner/goplugin/ginsider/ginsider_test.go, logicrunner/logicrunner_test.go
skip ginsider test in race environment
=> NO_ISSUE_ignore_ginsider_test_in_race_environment

ledger/pulsemanager/pulsemanager.go, ledger/storage/db.go, ledger/storage/jet.go
Closes INS-1013.
Copy jet tree between pulses.
Run tests.
=> INS-1013. Optimize tree.

logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
=> NOISSUE: proposal for pending requests deadlock fix

logicrunner/logicrunner.go
=> NOISSUE: fix race condition

logicrunner/logicrunner.go
* don't access es.Current without lock
* we could SendResult and recieve new request faster than we clear
es.Current. We can not clear es.Current at the place where we send
result, so we set a flag instead
* again: fake loop detection could happen if a contract calls the
same contract several times and some of these calls can hit target
before es.Current is cleared
* use goroutine to send reply, not only for performance reasons, but
also to avoid deadlock in setup with one virtual executor
* it's hard to write a test for this, our benchmark hits the problem
=> INS-1023: avoid false positives in loop detection

api/main.go, api/status.go
=> NOISSUE: extend status api

ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, ledger/exporter/exporter.go, ledger/pulsemanager/pulsemanager.go, ledger/pulsemanager/pulsemanager_test.go, ledger/recentstorage/recent_storage_mock.go, ledger/recentstorage/recentstorage.go, ledger/storage/db.go, ledger/storage/pulse.go, ledger/storage/recentstorage.go, ledger/storage/recentstorage_test.go, ledger/storage/remove.go, ledger/storage/remove_test.go
remove outdated indexes per jets on LM nodes
=> Ins 1016 fix outdated indexes removal

ledger/storage/db.go
Serialized access to db.dropWG
Protected calls to db.dropWG.Add() and .Wait() with mutex
=> NOISSUE: serialize access to db.dropWG

pulsar/pulsar_integration_test.go
=> Pulsar fix

logicrunner/logicrunner.go
emprove repfomance of OnPulse
move unlock of lr.stateMutex, make sending message in goroutines
=> INS-985 OnPulse multithread messages send

messagebus/messagebus.go
Refactored scope rlock/runlock to readBarrier
=> NOISSUE: readbarrier

ledger/artifactmanager/middleware.go, messagebus/messagebus.go
=> NOISSUE: fix and comments

logicrunner/logicrunner.go
=> INS-1048: turn off validatiion

logicrunner/casebind.go
**Even More turn of the validation**
=> INS-1048: turn off validatiion even more

ledger/artifactmanager/handler.go
=> NOISSUE: update handler

component/manager.go, functest/get_status_test.go, functest/main_test.go, functest/reconnect_test.go, scripts/insolard/genesis.yaml, scripts/insolard/insolar_5.yaml, scripts/insolard/launchnet.sh
=>  5 node net functors

ledger/storage/jet/tree.go, ledger/storage/jet/tree_test.go
Add String method on jet tree struct for debug friendly visualization
=> NOISSUE: add JetTree visualization

application/contract/member/member.go, application/proxy/member/member.go, functest/send_money_test.go
=> INS-1028: float removed from transfer

pulsar/networking.go, pulsar/pulsar.go, pulsar/pulsar_integration_test.go, pulsar/pulsar_test.go, pulsar/pulsarbroadcasters.go, pulsar/pulsarhelpers.go
=> Noissue increase timouts integration pulsar

ledger/artifactmanager/handlers_syncheavy.go, ledger/heavyclient/sync.go, ledger/heavyserver/heavysync.go, ledger/heavyserver/heavysync_test.go, ledger/storage/replica_iter.go, ledger/storage/transaction.go, ledger/storage/utils.go, scripts/glogs, scripts/stats
Fix heavy replication:
* remove heavy handlers skip 
* fix some bugs on pulse check 
* fix bug with passing Jet Id to HeavyPayload message
* improve logging
=> Ins 1061 heavy messages fix

core/message/logicrunner.go, logicrunner/casebind.go, logicrunner/logicrunner.go
=> NOISSUE: err->string

logicrunner/logicrunner_test.go
fix tets (i hope)
replace sleep with loop for a minute
run tests
=> INS-1045 refactor test, loop instead of sleep

functest/main_test.go
Remove insolard process stop when running test in CI environment
=> DEV-6 dont stop insolard in CI environment

pulsar/pulsar_integration_test.go, pulsar/pulsarbroadcasters.go
=> fix passing error

Gopkg.lock, contractrequester/contractrequester.go, contractrequester/contractrequester_test.go, core/message/logicrunner.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, logicrunner/casebind.go, logicrunner/consensus.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, testutils/testmessagebus/testmessagebus.go
**contract requester requestid is request id now**
**am.RegisterRequest uses msg again instead of parcel when creating request ref**
=> Ins 1048 restore validation

core/message/heavy.go, core/message/message.go, core/messagebus.go, core/messagetype_string.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handlers_syncheavy.go, ledger/heavyserver/heavyjetsync.go, ledger/ledger.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/heavy/heavyjetsync.go, ledger/storage/jet.go, ledger/storage/jet/tree.go, ledger/storage/jet/tree_test.go
trees merge
sending tree to heavy
=> Ins 1062 send jet tree to heavy

ledger/storage/jet.go
=> fix deadlock jet-tree

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/component_test.go, ledger/artifactmanager/metrics_test.go, network/merkle/errors_test.go
Use PulseStorage instead of direct access to db
Will be used for caching of pulse
Run tests
=> INS-1079: use PulseStorage in AM

ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/component_test.go, ledger/ledgertestutils/ledgertestutils.go, ledger/pulsemanager/pulse_storage_pm_mock.go, ledger/pulsemanager/pulsemanager.go, ledger/pulsemanager/pulsemanager_test.go, ledger/pulsemanager/pulsestoragepm.go, ledger/storage/pulsestorage.go, ledger/storage/pulsestorage_test.go
Add caching to PulseStorage
Run tests
=> INS-1078: cache in PulseStorage

core/record.go, functest/main_test.go, genesis/builder.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/component_test.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/middleware.go, ledger/exporter/exporter_test.go, ledger/heavyclient/heavy_test.go, ledger/ledgertestutils/ledgertestutils.go, ledger/pulsemanager/pulsemanager_test.go, ledger/storage/db.go, ledger/storage/replica_iter_test.go, ledger/storage/storagetest/utils.go
=> Noissue hard jet tree

core/delegationtoken/base.go, core/delegationtoken/factory.go, core/reply/base.go, core/reply/redirect.go, ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler_test.go
=> NOISSUE: added type suffixes

core/delegationtoken/base.go, core/message/message.go, scripts/insolard/check_status.sh
=> NOISSUE: updates

network/routing/table.go
=> NET-91: get all hosts workaround

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/artifactmanager_test.go
=> NOISSUE: retry-on-jetmiss

README.md, cmd/insolar/README.md
Fixed some readme documentation bugs
used MD linters
=> fix readme stylish

core/delegationtoken/base.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_dropwaitermiddleware_test.go, ledger/artifactmanager/jetdropwaitermiddleware.go, ledger/artifactmanager/middleware.go
=> Ins 850 wait for hot data

network/servicenetwork/servicenetwork.go, network/servicenetwork/servicenetwork_test.go
fix incrementPort() for ipv6 addresses
unit test
=> Noissue: increment port

core/message/heavy.go
=> INS-1091: update HeavyReset type

cmd/benchmark/api_request.go
=> Noissue benchmark retries create member

messagebus/messagebus.go, messagebus/messagebus_test.go
=> INS-1107: update check pulses logic

ledger/artifactmanager/jetdropwaitermiddleware.go
=> Fix problems with fetching state of existing objects

ledger/artifactmanager/jetdropwaitermiddleware.go, ledger/pulsemanager/pulsemanager.go
=> Noissue logs for a hot data

logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
add delete of objects from object state map
add checks in OnPulse method, fix tests, add tests
run tests
=> INS-1029 clear object state on pulse

api/requester/requester.go, api/seedmanager/seedmanager.go, cmd/benchmark/api_request.go, cmd/benchmark/main.go, cmd/benchmark/scenario.go
=> Ins-1103 benchmark connection pool

cmd/benchmark/api_request.go
=> NOISSUE: update create members logic in benchmark"

docker/Dockerfile.builder
=> fix builds

Makefile, cmd/certgen/README.md, cmd/certgen/main.go
Added command line util to generate keys and certificate for a new node that is connecting to a working network of insolar nodes
Run this util according to README.md on a working insolar network
=> INS-1114: command line util to generate certificate

cmd/pulsard/main.go, pulsar/pulsar.go, pulsar/pulsartimers.go, scripts/insolard/pulsar.yaml
=> Ins 1093 fix pulsar deadlock

cmd/pulsard/main.go
=> make pulsar start stateless

genesis/config.go
Add light check of existence of 3 different roles in genesis config
Run tests
=> Noissue light check role in genesis

network/pulsenetwork/distributor.go
=> Noissue-fix-troubles-with-pulse-distribution

network/pulsenetwork/distributor.go
=> Send pulses in routines

network/pulsenetwork/distributor.go
=> fix issue with pulse dist

logicrunner/logicrunner_test.go
Look at TestContractCallingContract()
=> TEST: Add test for transfering structs from contract to another

component/manager.go, component/manager_test.go, component/subcomponents_test.go
ComponentManager added subcomponents feature
`inject:"subcomponent"` annotation
unit tests
=> Ins 1126 subcomponent manager

api/call.go, api/call_test.go, api/main.go, api/main_test.go, api/requester/requester.go, configuration/apirunner.go, scripts/insolard/insolar.yaml
=> INS-1111: api timeout

application/contract/member/member.go, application/proxy/member/member.go, functest/get_balance_test.go, functest/get_node_ref_test.go
Renamed called methods in member contract.
=> DOCD18-153: rename called methods in member contract

component/manager.go, component/subcomponents_test.go
Fixed bugs in subcomponent manager feature that led to endless loops + incorrect dependency injection; fixed component manager tests
Run tests in component package
=> INS-1126: subcomponent manager fixes

scripts/insolard/insolar.yaml, scripts/insolard/insolar_1.yaml, scripts/insolard/insolar_2.yaml, scripts/insolard/insolar_3.yaml, scripts/insolard/insolar_4.yaml, scripts/insolard/insolar_5.yaml
=> INS-1130: trim insolard config

ledger/pulsemanager/pulsemanager.go
=> Possible fix for unlocking parent’s jets

ledger/ledgertestutils/ledgertestutils.go, ledger/pulsemanager/pulsemanager.go, logicrunner/logicrunner_test.go
=> reset dirty hack and possible fix tests

api/exporter.go
Added special error code in exporter.Export when pulse is not found
=> NOISSUE: added exporter error code

cmd/insolard/components.go, network/controller/bootstrap/bootstrap.go, network/controller/bootstrap/network_bootstrap.go, network/controller/controller.go, network/hostnetwork/transport.go, network/interfaces.go, network/servicenetwork/integr_test.go, network/servicenetwork/servicenetwork.go
Various bugfixes in genesis bootstrap
With workarounds and big pain
=> INS-1137: genesis bootstrap fixes

network/hostnetwork/transport_base.go, network/hostnetwork/transport_test.go, network/pulsenetwork/distributor.go, network/transport/quic.go, network/transport/tcp.go, network/transport/transport.go, network/transport/transport_test.go, network/transport/udp.go
=> NOISSUE: extend transport listen

network/transport/future.go, network/transport/future_test.go
=> NOISSUE: fix future write in closed channel

network/transport/packet/packet.go
fixed bug that caused network connection to be in an inconsistent state that in the end led to panic
removed extra wrap of network error
=> NOISSUE: remove wrap of gob serialization error

ledger/pulsemanager/pulsemanager.go, scripts/glogs
=> INS-1131 remove hot data

functest/utils_test.go
=> NOISSUE: retry func test

.gitignore, cmd/benchmark/README.md, cmd/benchmark/main.go, cmd/benchmark/scenario.go
=> Noissue use members from file

ledger/artifactmanager/middleware.go
after this we report situation when multiple nodes said different actual
jets for the same object
=> analyze replies to GetJet message for problems and report them

ledger/storage/jet.go, ledger/storage/jet/tree.go
=> Quick fix of ErrType:3

network/transport/base.go, network/transport/tcp.go
=> NOISSUE: channel closed bug

application/contract/rootdomain/rootdomain.go, application/proxy/rootdomain/rootdomain.go, core/pulse.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/middleware.go, ledger/jetcoordinator/jetcoordinator.go, ledger/storage/pulse.go, ledger/storage/pulsestorage.go, ledger/storage/store.go, messagebus/messagebus.go, scripts/insolard/genesis.yaml
Added current pulse to context before executing message handler.
=> Context pulse

logicrunner/logicrunner_test.go
this will actualize JetTree in DB and we wouldn't error out with
"impossible situations"
=> send HotData via message bus after setting pulse in tests

core/message/message.go, ledger/artifactmanager/handler.go, ledger/exporter/exporter.go, ledger/storage/storage_test.go
Fixed payload deserialization in exporter
=> INS-991: fix exporter

cmd/benchmark/main.go, cmd/benchmark/scenario.go, functest/dump_test.go, functest/get_balance_test.go
=> NOISSUE: speed without timeout

scripts/insolard/launchnet.sh
**Script now creates symlinks for node logs**
=> NOISSUE: allow to easely find log for specific node

scripts/insolard/launchnet.sh
=> FIX: jq finder exitst

cmd/insolard/main.go, core/message/parcel.go, core/utils/utils.go, instrumentation/inslogger/logger.go, messagebus/messagebus.go, network/controller/rpc_controller.go, network/servicenetwork/servicenetwork.go, pulsar/pulsar.go
=> Ins-1120 fix double trace

messagebus/messagebus.go
=> log for old pulse

ledger/pulsemanager/pulsemanager.go
deadlock: hot data is send, we wait for reply, we keep message bus from
delivering incoming messages, the same happens on other node that sends
hot data to us. this is just an idea, but we believe this solution is
more correct than what we had before.
=> send jet hot data in goroutines to avoid deadlocks

ledger/pulsemanager/pulsemanager.go, ledger/storage/pulsestorage.go
=> INS-1131 remove possible race

network/controller/rpc_controller.go, network/hostnetwork/transport.go, network/hostnetwork/transport_consensus.go, network/pulsenetwork/distributor.go, network/transport/base.go, network/transport/tcp.go, network/transport/transport.go, network/transport/transport_test.go
Added missed traceid in network logs
read logs
=> NOISSUE: network traceid

cmd/benchmark/main.go
=> NOISSUE: bench logging

cmd/insolard/main.go
=> NOISSUE: log role

ledger/storage/remove_test.go
=> fix zero jet case for RemoveJetIndexesUntil tests

ledger/artifactmanager/instrument.go
=> race when you print ctx

cmd/insolard/main.go, instrumentation/instracer/examples/clientserver_test.go, instrumentation/instracer/tracer.go, instrumentation/instracer/tracer_test.go
=> add node roles and nodeRef to trace

cmd/benchmark/scenario.go
=> NOISSUE-bench-pretty-output done

logicrunner/service.go
=> NOISSUE: fix concurrent map write logicrunner rpc

core/pulse.go, ledger/storage/pulsestorage_test.go
=> NOISSUE: fix context pulse

log/log.go
somebody broke this and it's in every log message
=> remove a field from logger that should have remind us to refactor

logicrunner/logicrunner.go
**now we use generic messagebus again**
=> NOISSUE: saw out recording messagebus

cmd/exporter/main.go, configuration/ledger.go, core/pulse.go, ledger/exporter/exporter.go, ledger/exporter/exporter_test.go, ledger/ledger.go
Added configurable lag to exporter.Export
=> Noissue add export lag

network/servicenetwork/servicenetwork.go
Fixed discovery nodes bootstrap process to have synchronized first pulse on each node
=> NOISSUE: added missed SetLastIgnoredPulse on bootstrap

functest/dump_test.go, functest/get_balance_test.go, functest/send_money_test.go
=> NOISSUE: skip several func tests

cmd/benchmark/main.go
=> NOISSUE: add member creation time

network/controller/bootstrap/bootstrap.go, network/servicenetwork/servicenetwork.go
Another iteration of fixing bootstrap for testnet. Blocking until first pulse on bootstrap, then exchange pulses between nodes, choose max pulse, start network from maxPulse.NextPulse + 1
With lots of locks and big pain
Try to start network on 20 nodes
=> NOISSUE: fix bootstrap

ledger/exporter/exporter.go, ledger/heavyserver/heavysync.go
Added search for pulse in exporter
Iterating through first pulses
=> HOTFIX: exporter pulse search

api/call.go, cmd/insolard/main.go, configuration/tracer.go, contractrequester/contractrequester.go, instrumentation/instracer/examples/clientserver_test.go, instrumentation/instracer/tracer.go, instrumentation/instracer/tracer_test.go, ledger/artifactmanager/artifactmanager.go, logicrunner/builtin/builtin.go, logicrunner/logicrunner.go, logicrunner/service.go, messagebus/messagebus.go
=> Noissue add traces

Makefile, cmd/pulsewatcher/README.md, cmd/pulsewatcher/config/pulsewatcher.go, cmd/pulsewatcher/pulsewatcher.go, scripts/generate_insolar_configs.go
=> INS-1144: pulsewatcher

functest/dump_test.go, functest/get_balance_test.go, functest/send_money_test.go
=> Noissue unskip func tests

ledger/artifactmanager/metrics.go, ledger/heavyclient/heavy_client.go, ledger/heavyclient/metrics.go
* add synced pulses count by heavy client
* better histogram for AM's methods (remove zero bucket)
=> improve metrics

metrics/network.go, network/transport/future.go
=> HOTFIX net timeout metric release

configuration/log.go, log/log.go, log/log_test.go, log/logrus.go
logger formatter config
old text formatter by default, json formatter as option
=> Noissue log formatter config

ledger/pulsemanager/pulsemanager.go, ledger/storage/pulse.go, ledger/storage/replica.go
simplify error processing, git rid of ineffectual vars assignment
=> Simplify error processing

cmd/insolard/main.go, cmd/pulsard/main.go, pulsar/metrics.go, pulsar/networking.go, pulsar/pulsar.go, pulsar/pulsarbroadcasters.go, pulsar/pulsarconsensus.go, pulsar/pulsartimers.go, pulsar/statemachine.go, scripts/insolard/launchnet.sh, scripts/insolard/pulsar.yaml
=> NOISSUE: Pulsar metrics

metrics/insolar.go, metrics/network.go, network/state/switcher.go
=> NOISSUE: send metric to prometheus when node reaches complete network state

functest/send_money_test.go, functest/utils_test.go
Retry func test if created data was corrupted by errored tx
=> NOISSUE: retry func tests if data was corrupted by errored tx

metrics/insolar.go, metrics/network.go, network/transport/future.go
Commit and PR by @dmitry-panchenko
=> HOTFIX: net timeout metric

ledger/artifactmanager/artifactmanager_test.go, ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, ledger/artifactmanager/heavy_test.go, ledger/heavyclient/heavy_test.go, ledger/ledgertestutils/ledgertestutils.go, ledger/pulsemanager/pulsemanager.go, ledger/recentstorage/provider_mock.go, ledger/recentstorage/recent_storage_mock.go, ledger/recentstorage/recentstorage.go, ledger/storage/recentstorage.go, ledger/storage/recentstorage_test.go, logicrunner/logicrunner_test.go, scripts/insolard/pulsar_template.yaml
=> Possible fix to hot data

ledger/pulsemanager/pulsemanager.go, logicrunner/logicrunner.go, network/state/switcher.go
Add several spans in jaeger for OnPulse logic
=> INS-1191: add some spans for jaeger

core/record.go, core/record_test.go
Improved RecordID.DebugString() method performance by 20 times.
Replaced fmt.Sprintf() with strconv.AppendInt()
=> INS-1186: RecordID.DebugString() prefomance

core/pulse.go, ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/handler.go, ledger/storage/pulsestorage.go, ledger/storage/pulsestorage_test.go, messagebus/messagebus.go
This reverts commit 5c76f084e9d8d524b24d598a6bf44279e2c61603, reversing
changes made to a89b781fd850d6edfa5802b430b72596daa06510.
=> Revert "Merge pull request #1036 from insolar/context-pulse"

logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
improve onPulse performance
remove wait group on sending ExecutorResults messages
run tests, watch metrics
=> INS-1172 onPulse doesn't wait for sending messages

configuration/ledger.go, ledger/jetcoordinator/jetcoordinator.go, ledger/jetcoordinator/jetcoordinator_test.go, ledger/ledger.go
Remove `roleCount` from jetcoordinator
Remove it and hardcode as constants like this:
```
const (
VirtualValidatorCount  = 3
MaterialValidatorCount = 3
VirtualExecutorCount  = 1
MaterialExecutorCount = 1
)
```
=> INS-1208: remove roleCounts from jetcoordinator (and hardcode it)

core/components.go, core/ledger.go, ledger/ledger.go
=> INS-1209: mark deprecated stuff

ledger/artifactmanager/artifactmanager.go, ledger/artifactmanager/descriptors.go
=> Ins 1165 Change "unexpected reply" to a concrete message

cmd/benchmark/README.md
=> INS-1194: update docs

ledger/artifactmanager/hotdatawaiter.go, ledger/artifactmanager/hotdatawaiter_test.go
=> Fix of small issues

ledger/artifactmanager/handler.go, ledger/artifactmanager/jettreeupdater.go, ledger/artifactmanager/jettreeupdater_test.go, ledger/artifactmanager/middleware.go, ledger/storage/jet/tree.go
account for pulse, we can actulize tree for any object and pulse
=> INS-1185: extract combined jet tree updater into one place

ledger/artifactmanager/handler.go, ledger/artifactmanager/middleware.go, logicrunner/casebind.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
Add fields to logger
1) target to logicRunner and ledger
2) getId to ledger
=> INS-1196: add target to logicRunner and jetid to ledger

ledger/exporter/exporter.go, ledger/exporter/exporter_test.go
Fix bad pulseStorage in Exporter
Delete NewPulseStorage in Exporter.
Inject fields into Exporter
=> INS-1167: bug-fix - bad pulseStorage in Exporter

logicrunner/logicrunner.go
OnPulse code improvement
make one function that response for sending messages in OnPulse
run tests
=> NO_ISSUE OnPulse code improvement

consensus/phases/communicator_test.go, consensus/phases/phasemanager.go, consensus/phases/secondphase.go, network/controller/bootstrap/authorization.go, network/controller/bootstrap/bootstrap.go, network/controller/bootstrap/network_bootstrap.go, network/hostnetwork/transport_consensus.go, network/hostnetwork/transport_consensus_test.go, network/interfaces.go, network/servicenetwork/integr_pulsar.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/suite_test.go, testutils/network/consensus_network_mock.go
Fixed integration tests and network bootstrap with consensus
Run integration and functional tests
=> INS-1260: consensus integration tests fixed

instrumentation/instracer/tracer.go, ledger/pulsemanager/pulsemanager.go
* make it possible to set span options
* set AlwaysSample sampler for pulse change span
* extract GIL part into a separate function - simplify code and correct
spans
=> INS-1270: send jaeger on pulse all the time and change spans

ledger/artifactmanager/handler.go, ledger/artifactmanager/handler_test.go, ledger/storage/index/lifeline.go, ledger/storage/storage_test.go
I add a pulse number to index. Now when we store index, we store pulse number of updating moment also.
=> Ins 1308 Add pulse number to Index

logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
add handling of AbandonedRequestsNotification message
add handler, register it
run tests
=> INS-1295 handle AbandonedRequestsNotification message

Makefile
Added the test agrs 
Created new make steps 
changed makefile 
in the TC
These changes need to for running tests with coverage and special arguments
=> Ins 1266 makefile test args

consensus/packets/phase3packet.go, consensus/phases/communicator.go, consensus/phases/firstphase.go, consensus/phases/secondphase.go, consensus/phases/thirdphase.go
=> INS-1264: jaeger consensus

logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
add test on uncovering code of logicRunner
add tests, remove dead code
run tests
=> INS-1275 moar logicRunner tests

logicrunner/logicrunner_test.go, network/merkle/calculator_test.go, network/merkle/errors_test.go, network/merkle/hashes_test.go, network/servicenetwork/integr_test.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/suite_test.go, testutils/terminationhandler/test_termination.go
Fail-fast in servicenetwork when the node does not pass the consensus
Run unit and integration tests
=> INS-1291: consensus fail path

ledger/storage/cleaner_test.go
=> NOISSUE: fix cleaner test

ledger/pulsemanager/pulsemanager.go, ledger/storage/jet/tree.go, ledger/storage/jet_storage_mock.go, ledger/storage/jetstorage.go, ledger/storage/jetstorage_test.go
no point for lights materials to store anything on disk, use in memory
trees.
=> INS-1348: jet trees in memory

logicrunner/logicrunner_unit_test.go
Used `testify.suite` in LogicRunner unit tests (to remove duplication of code)
=> Move all LogicRunner unit tests to suite (testify.suite)

scripts/generate_insolar_configs.go, scripts/insolard/profile.sh, scripts/insolard/start_nodes.sh, scripts/monitor/grafana/dashboards/consensus.json
Fixed scripts for monitoring and profiling insolar network in NET-integration branch. Also, added dashboard in grafana for consensus.
Run launchnet.sh, monitor.sh, profile.sh
=> INS-1422: monitor consensus

contractrequester/contractrequester.go, core/message/logicrunner.go, logicrunner/logicrunner.go
Renamed Name field to Method in CallConstructor
=> INS-1370: renamed Name field to Method in CallConstructor

Makefile, network/servicenetwork/integr_test.go
added tag "network" for network integration tests
=> INS-1424: tag to tests

logicrunner/logicrunner_unit_test.go
* Added comments
* Removed duplicated tests
* Added suits for OnPulse tests
* Every OnPulse call now is in its own subtest
* Redo LedgerHasMoreRequests test
=> race-condition in OnPulse tests fixes

Makefile
One format of targets for all built binaries
=> NOISSUE: one format for all binary targets

Makefile
=> [INS-1407] Add integrtest

network/transport/pool/connectionpool.go, network/transport/pool/entry.go, network/transport/pool/holder.go, network/transport/pool/interfaces.go
=> NOISSUE: connection pool entry

genesis/genesis.go, scripts/generate_insolar_configs.go, scripts/insolard/genesis.yaml
=> NOISSUE: update keys name format

logicrunner/logicrunner_unit_test.go
also reformatted 'TestReleaseQueue' to standard "table test" representation
=> INS-1316: Add LogicRunner testcases

ledger/pulsemanager/pulsemanager.go, ledger/recentstorage/recentstorage_concrete.go, ledger/recentstorage/recentstorage_concrete_test.go, scripts/insolard/launchnet.sh
=> NOISSUE fix panic with wrong index while removing pendings

scripts/glogs
=> NOISSUE modify glogs

genesis/genesis.go, scripts/generate_insolar_configs.go
=> NOISSUE: update index

ci/local-dev/manifests/ks/components/insolar/genesis.libsonnet, ci/local-dev/manifests/ks/components/insolar/launch.sh, ci/local-dev/manifests/ks/environments/dev/params.libsonnet
=> fix templates

network/servicenetwork/integr_test.go
Fixed typo in consensus integration test
=> NOISSUE: fixed consensus integration test

README.md
=> NOISSUE: fix readme

consensus/metrics.go, network/controller/metrics.go, network/transport/pool/entry.go
=> NOISSUE: fix licence

ledger/jetcoordinator/jetcoordinator.go
=> INS-1542: fix isBeyondLimit for in-memory pulseTracker

ledger/recentstorage/recentstorage_concrete.go
=> INS-1543 fix race

scripts/insolard/start_nodes.sh
=> NOISSUE: generate cert with custom roles

ledger/pulsemanager/pulsemanager.go
=> NOISSUE: allow light material join network

cmd/benchmark/main.go, cmd/benchmark/scenario.go, scripts/insolard/launchnet.sh
=> INS-1549 add count of pending retries to benchmark

metrics/metrics.go, metrics/metrics_test.go, metrics/status.go, scripts/dev/cover-filter.sh
`/_status` page with build info and useful debug links
=> Admtsks 73 status page

cmd/benchmark/main.go, cmd/benchmark/scenario.go, scripts/insolard/launchnet.sh
=> Noissue fix bench output

scripts/insolard/genesis.yaml
=> NOISSUE: update genesis conf

.golangci.yml, certificate/manager.go, core/message/heavy.go, core/message/nodesign.go, core/message/parcel.go, ledger/artifactmanager/descriptors.go, ledger/artifactmanager/middleware.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/db.go, ledger/storage/jet/jetdrop.go, logicrunner/consensus.go, logicrunner/goplugin/goplugin.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, logicrunner/service.go, metrics/status.go, network/controller/bootstrap/bootstrap.go, network/pulsenetwork/distributor.go, network/transport/base.go, testutils/core.go, testutils/testmetrics/testmetrics.go, version/manager/versionmanager.go
=> NOISSUE: fix golang ci

.golangci.yml, ledger/recentstorage/recentstorage_concrete.go, network/transport/quic.go
=> NOISSUE: fix missing linter errors

README.md
=> NOISSUE: add golangci badge

logicrunner/logicrunner.go
=> NOISSUE: revert error check

api/status.go
=> NOISSUE: fix origin status

logicrunner/logicrunner.go
=> NOISSUE: add activate object check

consensus/packets/phase1packet.go
=> INS-1565: fix copy paste

cmd/pulsewatcher/pulsewatcher.go
=> NOISSUE: color insolar state

functest/send_money_test.go, ledger/artifactmanager/handler.go, ledger/pulsemanager/pulsemanager.go, ledger/storage/cleaner_test.go, ledger/storage/dropstorage.go, ledger/storage/errors.go, ledger/storage/genesisinitializer.go, ledger/storage/jetstorage.go, ledger/storage/pulsetrackerdb.go, ledger/storage/replica_iter_test.go, ledger/storage/replicastorage.go, ledger/storage/storage_test.go, ledger/storage/transaction.go
=> Noissue change errnotfound in storage package

scripts/insolard/launchnet.sh
=> NOISSUE: clear nodes data

api/call.go
=> NOISSUE: golangci fix

core/errors.go, functest/send_money_test.go
=> NOISSUE: fix upper-case error-msg

api/status.go, cmd/pulsewatcher/pulsewatcher.go, configuration/hostnetwork.go, core/networkswitcher.go, core/termination_handler.go, core/utils/utils.go, network/controller/bootstrap/bootstrap.go, network/nodenetwork/nodekeeper.go, network/servicenetwork/integr_networkswitcher.go, network/servicenetwork/integr_test.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/suite_test.go, network/state/switcher.go, network/state/switcher_test.go, testutils/core.go, testutils/network_switcher_mock.go, testutils/termination_handler_mock.go, testutils/terminationhandler/test_termination.go
=> NOISSUE: fix majority

.dockerignore, .gitignore, Makefile, configuration/pulsar.go, configuration/testdata/default.yml, docker/Dockerfile.pulsar, scripts/insolard/pulsar_template.yaml
=> Ins 1574 change pulsar dir

core/components.go, core/ledger.go
=> INS-1641 remove old evil

application/contract/member/member.go, application/proxy/member/member.go, cmd/insolar/main.go
./bin/insolar -c create_member <username>
=> INS-1460: make create_member single command

conveyor/interfaces/slot/slot.go, conveyor/interfaces/slot/slot_element_helper_mock.go, conveyor/interfaces/slot/slot_element_read_only_mock.go, conveyor/interfaces/slot/slot_element_restricted_helper_mock.go
=> INS-1508: add slot interface

network/pulsenetwork/distributor.go
=> INS-1644 resolve address of bootstraps every distribution

logicrunner/logicrunner_test.go, logicrunner/logicrunner_unit_test.go
Please do not use singltones in parallel environment
=> INS-1652: move logger initialization code into a common place

README.md
=> NO_ISSUE_fix_readme

conveyor/conveyor.go, conveyor/conveyor_test.go, conveyor/slot.go, conveyor/slot_test.go, conveyor/slotstate_string.go, core/pulse.go
- add InitiateShutdown method
- move AntiquePulseNumber const to core.Pulse
- get info about new future pulse number from futurePulseData
- if createElement returns error, push element back to EmptyList
- PreparePulse/ActivatePulse check only ShuttingDown states, which allows init conveyer by doing PreparePulse and ActivatePulse calls 
- stateMachine is field in Slot struct now
- if we can't push signal into slots queue, panic
Run tests
=> Ins 1845 updates for conveyor

conveyor/slot.go, conveyor/slot_test.go
1) Add more helpful functions 
2) change pushElement
3) tests
=> refactoring of slot

network/controller/bootstrap/authorization.go, network/controller/bootstrap/metrics.go
Added more logs and metrics for case when the joining node conflicts with network active list
Used opencensus and insolar logger with Warn level
Run launchnet.sh
=> INS-1916: more logging for auth conflict case

Makefile, network/nodenetwork/node.go, network/servicenetwork/servicenetwork.go
cleanup and split dependency target in two in Makefile,  improve error messages
=> Noissue random refactoring

conveyor/slot.go, conveyor/slot_element.go, conveyor/slot_test.go
Add len and remove func to element list
Make element list doubly
Run tests
=> Ins 1915 update elements list

api/exporter.go, ledger/exporter/exporter.go, ledger/exporter/exporter_test.go
=> Ins 1999 cherry pick tolerant exporter for release

network/controller/bootstrap/authorization.go, network/controller/bootstrap/metrics.go
=> INS-1916: to release

core/jet.go, ledger/artifactmanager/jettreeupdater.go, ledger/heavyclient/heavy_pool.go, ledger/heavyserver/heavysync.go, ledger/jetcoordinator/jetcoordinator.go, ledger/storage/cleaner.go, ledger/storage/db.go, ledger/storage/drop/db.go, ledger/storage/jet.go, ledger/storage/jet/tree.go, ledger/storage/jet/tree_test.go, ledger/storage/objectstorage.go, ledger/storage/replica_iter.go, ledger/storage/transaction.go
=> INS-1644 prefix/depth for jets

ledger/artifactmanager/handler.go
=> INS-2104 register getrequest for a heavy node

ledger/artifactmanager/artifactmanager.go, logicrunner/logicrunner.go
* wrap error so it's clear what operation we do
* warn when we failed to execute a contract
=> INS-2025: improve logging in all users of UpdateObject message

conveyor/generator/generator/templates/matrix.go.tpl, conveyor/generator/generator/templates/state_machine.go.tpl, conveyor/generator/matrix/matrix.go, conveyor/generator/matrix/matrix_base.go, conveyor/generator/state_machines/sample/sample_state_machine_generated.go
1) add iface for matrix
2) fix tmpls in generate
=> INS-1513: add iface for matrix + fix tmpls

conveyor/conveyor.go, conveyor/conveyor_test.go, conveyor/generator/generator/templates/matrix.go.tpl, conveyor/generator/generator/templates/state_machine.go.tpl, conveyor/generator/matrix/matrix.go, conveyor/generator/matrix/matrix_base.go, conveyor/generator/state_machine_test.go, conveyor/generator/state_machines/sample/sample_state_machine_generated.go, conveyor/interfaces/statemachine/state_machine.go, conveyor/slot.go, conveyor/worker.go, conveyor/worker_test.go
=> Ins 2165 new matrix structure

conveyor/adapter/base.go, conveyor/adapter/catalog.go, conveyor/adapter/id.go, conveyor/adapter/response.go, conveyor/adapter/response_test.go, conveyor/adapter/type.go, core/conveyor.go, messagebus/future.go, messagebus/messagebus.go
=> Ins 1913 adapter helpers

ledger/storage/db/db.go, ledger/storage/object/lifeline.go, ledger/storage/object/lifeline_cmp_test.go
DB implementation for index storage added
=> INS-1710: DB implementation for index storage added

ledger/storage/object/lifeline.go
=> NOISSUE: fix master

network/servicenetwork/integr_pulsar.go, network/servicenetwork/suite_test.go
=> Revert "NOISSUE: USE TBN env to choose testing ip"

ledger/artifactmanager/handler_test.go, ledger/heavyclient/heavy_test.go, ledger/ledger.go, ledger/storage/cleaner_test.go, ledger/storage/db/badger.go, ledger/storage/db/badger_test.go, ledger/storage/db/db_cmp_test.go, ledger/storage/drop/db.go, ledger/storage/drop/db_test.go, ledger/storage/drop/drop_cmp_test.go, ledger/storage/object/lifeline.go, ledger/storage/object/lifeline_cmp_test.go, ledger/storage/object/record.go, ledger/storage/object/record_cmp_test.go, ledger/storage/pulse/db.go, ledger/storage/pulse/pulse_cmp_test.go, ledger/storage/replica_iter_test.go, ledger/storage/storage_test.go, ledger/storage/storagetest/utils.go, logicrunner/artifacts/client_test.go, logicrunner/artifacts/tmpledger.go
explicit backend pass in advance to implicit one
=> Ins 2131 explicit DI in new Ledger packages

conveyor/adapter/adapterstorage/storage.go, conveyor/adapter/adapterstorage/storage_test.go, conveyor/conveyor_test.go, server/internal/genesis/components.go, server/internal/light/components.go, server/internal/light/testdata/certificate.json, server/internal/virtual/components.go, server/internal/virtual/testdata/certificate.json
Divide register of adapters for static roles
=> Ins 2226 divide inject adapters

cmd/insgorund/insgorund.go, metrics/metrics.go, server/internal/genesis/components.go, server/internal/light/components.go, server/internal/virtual/components.go, testutils/testmetrics/testmetrics.go
Update metric constructor, so no certificate is needed if role is set
Run tests
=> INS-2228: use role from constructor if provided

Makefile
I added the parameter LEDGER_ENTITY at build step for enabling/disabling LEDGER contracts endpoint
Added parameter LEDGER_ENTITY with empty value as default and pass it in the build stage 
In the CI 
=> INS-2140: add parameter LEDGER_ENTITY to makefile

network/controller/pulsecontroller.go, network/hostnetwork/packet/packet.go, network/hostnetwork/packet/request.go, network/hostnetwork/packet/response.go, network/hostnetwork/packet/types/packettype_string.go, network/hostnetwork/packet/types/types.go, network/hostnetwork/transport_test.go, network/interfaces.go, network/routing/table.go
remove GetRandomHosts and GetRandomNodes
=> Noissue remove get random hosts

insolar/flow/flow.go, insolar/flow/internal/thread/thread.go
=> add 'continue' logic to flow

core/termination_handler.go, network/controller/pulsecontroller.go, network/nodenetwork/nodekeeper.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/suite_test.go, testutils/terminationhandler/test_termination.go
Fixed bug that caused reconnecting discovery node to hang forever
=> INS-2245: reconnect discovery bug

insolar/flow/integration_test.go, insolar/flow/intergrationtest/integration_test.go
=> add 'INS-2259: add integration tests

consensus/phases/communicator.go, insolar/certificate.go, insolar/contractrequester.go, insolar/flow/flow.go, insolar/heavy.go, insolar/ledger.go, insolar/messagebus.go, insolar/network.go, insolar/networkcoordinator.go, insolar/networkswitcher.go, insolar/nodenetwork.go, insolar/termination_handler.go, insolar/vm.go, ledger/artifactmanager/hotdatawaiter.go, ledger/recentstorage/recentstorage.go, ledger/storage/db.go, ledger/storage/node/node.go, ledger/storage/replicastorage.go, messagebus/sender.go, messagebus/tape.go, network/interfaces.go, network/storage/cloudhash.go
=> fix minimock generator annotations codestyle

insolar/flow/handler/handler.go, insolar/flow/handler/handler_test.go
=> NOISSUE: timeout removed from WrapBusHandle

api/healthcheck.go, api/healthcheck_test.go, api/main.go, certificate/manager.go, pulsar/pulsar.go, pulsar/pulsar_test.go
Backported #1576 to version 0.8
=> INS-2310 healthcheck to 0.8 branch

network/servicenetwork/integr_pulsar.go, network/servicenetwork/integr_test.go
Simplified testPulsar in network integration tests
Run integration tests with --race flag
=> INS-2342: concurrency simplification

insolar/flow/internal/thread/thread.go
=> fix_rename more consistent names

insolar/flow/handler/handler.go
=> NOISSUE: WrapBusHandle refactored

insolar/flow/internal/thread/thread_test.go
it's not synchronization primitive, use another channel to exit from
procedure
you could reproduce test failure with the following command:
go test ./insolar/flow/internal/thread -run TestThread_Procedure_CancelledWhenProcedureWorks -count 1000000 -failfast
=> INS-2356: Gosched() can return execution to the same goroutine

insolar/flow/handler/handler_test.go, insolar/flow/internal/thread/thread_test.go
=> Noissue flow tests fixes

logicrunner/handle_init.go, logicrunner/handle_still_executing.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
**IMPORTANT! it's just for review, it needs to be merged into master, or firstly merge it into INS_2345 and only after that merge INS-2345 into master**
move HandleStillExecuting to flow
write handler on flow, remove old one
run tests
=> INS-2346 still executing to flow

logicrunner/handle_init.go, logicrunner/handle_pending_finished.go, logicrunner/handle_still_executing.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go
move pendingFinished handler to flow
write new handler with Flow
run tests
=> INS-2345 pending finished to flow

logicrunner/artifacts/client.go, messagebus/senders.go
I believe that in most cases virtual  node will do exactly this after
getting "delegation token" to finish what virtual started
=> INS-2378: retry on "Incorrect message pulse"

.gitignore, bootstrap/genesis/genesis.go, bootstrap/genesis/init.go, cmd/insolar/README.md, cmd/insolar/certgen.go, cmd/insolar/main.go, cmd/insolard/main.go, cmd/pulsewatcher/config/pulsewatcher.go, functest/main_test.go, scripts/bench.sh, scripts/docker-compose.yml, scripts/generate_insolar_configs.go, scripts/glogs, scripts/insolard/check_status.sh, scripts/insolard/genesis_template.yaml, scripts/insolard/insolard_template.yaml, scripts/insolard/launchnet.sh, scripts/insolard/pulsar_template.yaml, scripts/insolard/start_nodes.sh, scripts/monitor.sh
* write dynamic files to .artifacts/launchnet directory by default
* remove a lot of outdated logic, try to simplify that's left
=> INS-1576: cleanup and simplify launchnet

scripts/insolard/launchnet.sh, scripts/insolard/start_nodes.sh
remove log level overwrite in launchnet
cleanup certs dir
=>  some fixes in launchnet

ledger/light/artifactmanager/handler.go, ledger/light/proc/get_index.go, ledger/light/replication/gatherer.go, ledger/light/replication/gatherer_test.go
=> Fix index replication

contractrequester/contractrequester.go, contractrequester/contractrequester_test.go, contractrequester/handle_init.go, contractrequester/handle_return_results.go
move TypeReturnResults to flow
add flow into contract requester, add handler generation and handler for message ReturnResults. Add tests.
Run tests
=> INS-2382 move ReturnResults to Flow

ledger/light/hot/waiter_test.go, ledger/light/replication/cleaner_test.go, ledger/light/replication/lightreplicator_test.go
=> Fix hot tests

configuration/servicenetwork.go, consensus/phases/phasemanager.go, network/servicenetwork/servicenetwork.go, network/servicenetwork/suite_test.go
Added configuration for consensus phases timeouts. Increased timeouts fractions in integration tests.
integration tests
=> INS-2412: configuration for consensus phases timeouts

network/hostnetwork/future/future_test.go
TestFuture_GetResult checks timeout without async now
Run tests
=> NOISSUE: update net future test

README.md
remove Travis build badge
remove broken link
=> Noissue readme fix

Makefile, logicrunner/builtin_test.go, logicrunner/logicrunner_test.go
=> Revert "Noissue ci testing"

network/gateway/base.go, network/gateway/gateway_test.go
=> INS-2092: invalid state when certificate validation is ok =(

network/gateway/complete.go
Add missed method in complete network state
=> INS-2092: Implement missed method for joiner nodes

Makefile, network/tests/communication_policy_test.go, network/tests/gateway_test.go, network/tests/main_test.go, network/tests/pulsar_test.go, network/tests/suite_test.go, network/tests/wrappers_test.go
=> NOISSUE: move integr tests from service network

network/gateway/base.go, network/hostnetwork/future/handler_test.go, network/hostnetwork/future/manager_test.go, network/hostnetwork/resolver/exact_test.go, network/hostnetwork/resolver/resolver_test.go, network/sequence/sequence_test.go
=> NOISSUE: update network copyright

network/consensus/claimhandler/claimhandler_test.go, network/consensus/packets/claim.go, network/consensus/packets/claim_serializers.go, network/consensus/packets/claim_test.go, network/consensus/packets/claimtype_string.go, network/consensus/packets/data.go, network/consensus/packets/data_test.go, network/consensus/packets/init.go, network/consensus/packets/phase2packet.go, network/consensus/packets/vote.go, network/consensus/packets/vote_test.go, network/consensus/phases/bitsetmapper_test.go, network/consensus/phases/communicator.go, network/consensus/phases/secondphase.go, network/nodenetwork/claimqueue_test.go, network/nodenetwork/utils_test.go
=> INS-1595: remove copypaste

network/consensus/packets/claim.go, network/consensus/packets/claimtype_string.go
=> INT-1596: remove unused claim type

ledger/light/artifactmanager/handler.go, ledger/light/proc/update_object.go
Fixed null pointer exception and added fix from Egor
monkey-patch
run launchnet + benchmark
=> NOISSUE: fix update object

cmd/benchmark/README.md, functest/utils_test.go, logicrunner/goplugin/goplugintestutils/insgorund.go, scripts/insolard/README.md
more pretty functest output (insgorund loglevel) and couple of little fixes
=> Ins 2456 functests log level

network/hostnetwork/future/handler_test.go, network/transport/udp.go, network/transport/udp_test.go
=> INS-2478: send packets from one socket

README.md, docs/requirements.txt, docs/source/about.rst, docs/source/architecture.rst, docs/source/conf.py, docs/source/connect-or-setup.rst, docs/source/features.rst, docs/source/glossary.rst, docs/source/index.rst
- Wrote how-tos: how to connect to test net and set it up locally.
- Fixed some mistakes in README.
=> Integration chapter: how to connect or set up a net

insolar/bus/bus_test.go, log/watermill_adapter.go, logicrunner/logicrunner.go, logicrunner/logicrunner_unit_test.go, server/internal/heavy/components.go, server/internal/light/components.go, server/internal/virtual/components.go
=> INS-2443: add watermill adapter

insolar/message/ledger.go, ledger/heavy/handler/handler.go, ledger/light/proc/send_object.go, logicrunner/artifacts/artifacts.go, logicrunner/artifacts/client.go, logicrunner/artifacts/client_mock.go, logicrunner/goplugin/goplugintestutils/utils.go, logicrunner/logicrunner.go, logicrunner/logicrunner_test.go, logicrunner/logicrunner_unit_test.go, logicrunner/service.go
we don't use these and don't plan to use soon
=> INS-2484: drop not used arguments in GetObject

cmd/insolar/certgen.go
Added error handler 
Added error handler 
Return error to RegisterNode method in NodeDomain contract
=> INS-2487: Added error handler

functest/utils_test.go, ledger/object/lock_test.go
1) Redo Test_IDLockTheSame
2) Add retry exceeded error to func tests
=> Ins 2483 floating idlockthesame
